<?php

namespace App\Service;

use App\Entity\DataProvider;
use App\Entity\DatasetResource;
use App\Entity\IngestionRun;
use App\Entity\ProviderPackage;
use App\Repository\DatasetResourceRepository;
use App\Repository\ProviderPackageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Contracts\HttpClient\Exception\ExceptionInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;

// Generated by GitHub Copilot
final class CkanProviderService
{
    public function __construct(
        private readonly HttpClientInterface $httpClient,
        private readonly EntityManagerInterface $entityManager,
        private readonly ProviderPackageRepository $packageRepository,
        private readonly DatasetResourceRepository $resourceRepository,
        private readonly LoggerInterface $logger,
    ) {
    }

    /**
     * @return array{message: string, synced: int, deactivated: int}
     */
    public function syncPackageList(DataProvider $provider): array
    {
        $run = $this->createRun($provider, null, null, 'Sincronização da lista de pacotes iniciada.');

        try {
            $payload = $this->requestCkanAction($provider->getPackageListUrl());
            $result = $payload['result'] ?? null;

            if (!is_array($result)) {
                throw new \RuntimeException('A resposta do CKAN não trouxe uma lista de pacotes válida.');
            }

            $seenPackages = [];
            $synced = 0;

            foreach ($result as $packageId) {
                if (!is_string($packageId) || '' === trim($packageId)) {
                    continue;
                }

                $seenPackages[] = $packageId;
                $package = $this->packageRepository->findOneByProviderAndPackageId($provider, $packageId) ?? (new ProviderPackage())
                    ->setDataProvider($provider)
                    ->setPackageId($packageId)
                ;

                $package
                    ->setIsActive(true)
                    ->setRawMetadata([
                        'package_id' => $packageId,
                        'synced_from' => 'package_list',
                    ])
                ;

                $this->entityManager->persist($package);
                ++$synced;
            }

            $deactivated = 0;
            foreach ($this->packageRepository->findBy(['dataProvider' => $provider]) as $storedPackage) {
                if (!in_array($storedPackage->getPackageId(), $seenPackages, true) && $storedPackage->isActive()) {
                    $storedPackage->setIsActive(false);
                    ++$deactivated;
                }
            }

            $provider->setLastSyncedAt(new \DateTimeImmutable());
            $run
                ->setStatus(IngestionRun::STATUS_SUCCESS)
                ->setFinishedAt(new \DateTimeImmutable())
                ->setMessage(sprintf('%d pacotes sincronizados com sucesso.', $synced))
                ->addLog([
                    'event' => 'sync_package_list',
                    'synced' => $synced,
                    'deactivated' => $deactivated,
                    'provider' => $provider->getName(),
                ])
            ;

            $this->entityManager->flush();

            return [
                'message' => sprintf('Sincronização concluída: %d pacotes atualizados e %d desativados.', $synced, $deactivated),
                'synced' => $synced,
                'deactivated' => $deactivated,
            ];
        } catch (\Throwable $exception) {
            $this->markRunAsFailed($run, $exception);

            throw $exception;
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function fetchPackageDetails(DataProvider $provider, string $packageId): array
    {
        $payload = $this->requestCkanAction($provider->getPackageShowUrl($packageId));
        $result = $payload['result'] ?? null;

        if (!is_array($result)) {
            throw new \RuntimeException('A resposta do CKAN não trouxe metadados válidos para o pacote solicitado.');
        }

        return $result;
    }

    /**
     * @return array{package: ProviderPackage, resources_synced: int, message: string, metadata: array<string, mixed>}
     */
    public function syncPackageResources(ProviderPackage $package): array
    {
        $provider = $package->getDataProvider();
        $run = $this->createRun($provider, $package, null, sprintf('Atualização de detalhes do pacote %s iniciada.', $package->getPackageId()));

        try {
            $metadata = $this->fetchPackageDetails($provider, $package->getPackageId());
            $resources = $metadata['resources'] ?? [];

            $package
                ->setTitle($this->extractString($metadata, 'title') ?? $this->extractString($metadata, 'name'))
                ->setDescription($this->extractString($metadata, 'notes') ?? $this->extractString($metadata, 'description'))
                ->setRawMetadata($metadata)
                ->setLastCheckedAt(new \DateTimeImmutable())
                ->setIsActive(true)
            ;

            $seenResources = [];
            $syncedResources = 0;

            if (is_array($resources)) {
                foreach ($resources as $resourceData) {
                    if (!is_array($resourceData)) {
                        continue;
                    }

                    $resourceId = $this->extractString($resourceData, 'id');
                    $resourceUrl = $this->extractString($resourceData, 'url');

                    if (null === $resourceId || null === $resourceUrl) {
                        continue;
                    }

                    $seenResources[] = $resourceId;
                    $resource = $this->resourceRepository->findOneByPackageAndResourceId($package, $resourceId) ?? (new DatasetResource())
                        ->setProviderPackage($package)
                        ->setResourceId($resourceId)
                    ;

                    $resource
                        ->setName($this->extractString($resourceData, 'name'))
                        ->setFormat($this->extractString($resourceData, 'format'))
                        ->setUrl($resourceUrl)
                        ->setSize($this->extractInt($resourceData, 'size'))
                        ->setHash($this->extractString($resourceData, 'hash'))
                        ->setCreatedAtSource($this->extractDateTime($resourceData, 'created'))
                        ->setLastModifiedSource($this->extractDateTime($resourceData, 'last_modified'))
                        ->setRawMetadata($resourceData)
                    ;

                    $this->entityManager->persist($resource);
                    ++$syncedResources;
                }
            }

            foreach ($package->getResources() as $storedResource) {
                if (!in_array($storedResource->getResourceId(), $seenResources, true)) {
                    $this->entityManager->remove($storedResource);
                }
            }

            $run
                ->setStatus(IngestionRun::STATUS_SUCCESS)
                ->setFinishedAt(new \DateTimeImmutable())
                ->setMessage(sprintf('Pacote %s atualizado com %d recurso(s).', $package->getPackageId(), $syncedResources))
                ->addLog([
                    'event' => 'sync_package_resources',
                    'package' => $package->getPackageId(),
                    'resources_synced' => $syncedResources,
                ])
            ;

            $this->entityManager->flush();

            return [
                'package' => $package,
                'resources_synced' => $syncedResources,
                'message' => sprintf('Detalhes do pacote %s atualizados.', $package->getPackageId()),
                'metadata' => $metadata,
            ];
        } catch (\Throwable $exception) {
            $this->markRunAsFailed($run, $exception);

            throw $exception;
        }
    }

    /**
     * @return array<string, mixed>
     */
    private function requestCkanAction(string $url): array
    {
        try {
            $response = $this->httpClient->request('GET', $url, [
                'headers' => [
                    'Accept' => 'application/json',
                ],
                'timeout' => 30,
            ]);

            $payload = $response->toArray(false);
        } catch (ExceptionInterface $exception) {
            $this->logger->error('Falha de conexão com provedor CKAN.', [
                'url' => $url,
                'exception' => $exception,
            ]);

            throw new \RuntimeException('Não foi possível conectar ao provedor CKAN informado.', 0, $exception);
        }

        if (!is_array($payload)) {
            throw new \RuntimeException('O provedor CKAN respondeu em um formato inválido.');
        }

        if (($payload['success'] ?? false) !== true) {
            $message = 'O provedor CKAN respondeu sem sucesso.';
            if (isset($payload['error']) && is_array($payload['error'])) {
                $message = sprintf('Erro CKAN: %s.', json_encode($payload['error'], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
            }

            throw new \RuntimeException($message);
        }

        return $payload;
    }

    private function createRun(DataProvider $provider, ?ProviderPackage $package, ?DatasetResource $resource, string $message): IngestionRun
    {
        $run = (new IngestionRun())
            ->setDataProvider($provider)
            ->setProviderPackage($package)
            ->setDatasetResource($resource)
            ->setStatus(IngestionRun::STATUS_RUNNING)
            ->setStartedAt(new \DateTimeImmutable())
            ->setMessage($message)
            ->setLogs([])
        ;

        $this->entityManager->persist($run);

        return $run;
    }

    private function markRunAsFailed(IngestionRun $run, \Throwable $exception): void
    {
        $run
            ->setStatus(IngestionRun::STATUS_FAILED)
            ->setFinishedAt(new \DateTimeImmutable())
            ->setMessage($exception->getMessage())
            ->addLog([
                'event' => 'failure',
                'message' => $exception->getMessage(),
                'type' => $exception::class,
            ])
        ;

        $this->logger->error('Falha ao sincronizar provedor CKAN.', [
            'exception' => $exception,
            'message' => $exception->getMessage(),
        ]);

        $this->entityManager->flush();
    }

    private function extractString(array $data, string $key): ?string
    {
        if (!array_key_exists($key, $data) || null === $data[$key]) {
            return null;
        }

        if (!is_scalar($data[$key])) {
            return null;
        }

        $value = trim((string) $data[$key]);

        return '' === $value ? null : $value;
    }

    private function extractInt(array $data, string $key): ?int
    {
        if (!array_key_exists($key, $data) || null === $data[$key] || '' === $data[$key]) {
            return null;
        }

        if (is_numeric($data[$key])) {
            return (int) $data[$key];
        }

        return null;
    }

    private function extractDateTime(array $data, string $key): ?\DateTimeImmutable
    {
        $value = $this->extractString($data, $key);

        if (null === $value) {
            return null;
        }

        try {
            return new \DateTimeImmutable($value);
        } catch (\Exception) {
            return null;
        }
    }
}