<?php

namespace App\Service;

use App\Entity\Accommodation;
use App\Entity\DataSource;
use App\Entity\Indicator;
use App\Entity\TourismEvent;
use App\Entity\TouristGuide;
use App\Entity\TouristSpot;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;

// Generated by GitHub Copilot
final class McpContextService
{
    public const RESOURCE_REQUIREMENT = 'tourist-spots|events|accommodations|guides|indicators';
    public const TOOL_REQUIREMENT = 'search-tourism|search-events|recommend-itinerary|get-city-indicators';
    public const CONTEXT_REQUIREMENT = 'tourism|city';

    private const DEFAULT_LIMIT = 10;
    private const MAX_LIMIT = 25;

    /**
     * Receives the entity manager used to assemble MCP resources and contexts.
     */
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
    ) {
    }

    /**
     * Returns the MCP gateway home payload for AI-ready discovery.
     *
     * @return array<string, mixed>
     */
    public function getHomePayload(): array
    {
        return [
            'name' => 'Olinda360 MCP Gateway',
            'platform' => 'Olinda360',
            'version' => 'v1',
            'status' => 'online',
            'description' => 'Camada MCP preparada para integracao futura com IA generativa, agentes inteligentes e assistentes turisticos urbanos.',
            'resources' => $this->getResourcesCatalog(),
            'tools' => $this->getToolsCatalog(),
            'contexts' => $this->getContextsCatalog(),
            'docs' => '/mcp/v1/docs',
            'capabilities' => [
                'resource_gateway' => true,
                'tool_invocation' => true,
                'context_delivery' => true,
                'ai_ready_architecture' => true,
            ],
        ];
    }

    /**
     * Returns the resources catalog exposed by the MCP gateway.
     *
     * @return list<array<string, mixed>>
     */
    public function getResourcesCatalog(): array
    {
        $resources = [];

        foreach ($this->resourceDefinitions() as $resource => $definition) {
            $resources[] = [
                'resource' => $resource,
                'name' => $definition['label'],
                'path' => sprintf('/mcp/v1/resources/%s', $resource),
                'description' => $definition['description'],
                'status' => 'available',
            ];
        }

        return $resources;
    }

    /**
     * Returns a paginated MCP resource payload.
     *
     * @param array<string, mixed> $query
     *
     * @return array{data: list<array<string, mixed>>, meta: array<string, mixed>}
     */
    public function getResourcePayload(string $resource, array $query = []): array
    {
        $definition = $this->getResourceDefinition($resource);
        [$page, $limit] = $this->resolvePagination($query);

        $queryBuilder = $this->createResourceQueryBuilder($resource, $query);
        $countQueryBuilder = clone $queryBuilder;
        $countQueryBuilder->select('COUNT(item.id)');
        $countQueryBuilder->resetDQLPart('orderBy');

        $total = (int) $countQueryBuilder->getQuery()->getSingleScalarResult();
        $items = $queryBuilder
            ->setFirstResult(($page - 1) * $limit)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult()
        ;

        return [
            'data' => array_map($definition['normalizer'], $items),
            'meta' => [
                'page' => $page,
                'limit' => $limit,
                'total' => $total,
                'resourceLabel' => $definition['label'],
                'aiReady' => true,
                'gateway' => 'Olinda360 MCP',
            ],
        ];
    }

    /**
     * Executes one MCP tool and returns the normalized result payload.
     *
     * @param array<string, mixed> $input
     *
     * @return array{data: mixed, meta: array<string, mixed>}
     */
    public function executeTool(string $tool, array $input = []): array
    {
        return match ($tool) {
            'search-tourism' => $this->searchTourismTool($input),
            'search-events' => $this->searchEventsTool($input),
            'recommend-itinerary' => $this->recommendItineraryTool($input),
            'get-city-indicators' => $this->getCityIndicatorsTool($input),
            default => throw new \InvalidArgumentException(sprintf('Unknown MCP tool "%s".', $tool)),
        };
    }

    /**
     * Returns a higher-level context payload for LLMs and agent flows.
     *
     * @return array{data: array<string, mixed>, meta: array<string, mixed>}
     */
    public function getContextPayload(string $context): array
    {
        return match ($context) {
            'tourism' => $this->getTourismContextPayload(),
            'city' => $this->getCityContextPayload(),
            default => throw new \InvalidArgumentException(sprintf('Unknown MCP context "%s".', $context)),
        };
    }

    /**
     * Returns the documentation payload used by the MCP docs page.
     *
     * @return array<string, mixed>
     */
    public function getDocumentationPayload(): array
    {
        return [
            'resources' => $this->getResourcesCatalog(),
            'tools' => $this->getToolsCatalog(),
            'contexts' => $this->getContextsCatalog(),
            'examples' => [
                'GET /mcp/v1',
                'GET /mcp/v1/resources/tourist-spots?search=igreja&limit=5',
                'POST /mcp/v1/tools/search-tourism',
                'POST /mcp/v1/tools/recommend-itinerary',
                'GET /mcp/v1/context/tourism',
                'GET /mcp/v1/context/city',
            ],
            'responseExample' => [
                'status' => 'success',
                'type' => 'resource',
                'resource' => 'tourist-spots',
                'data' => [],
            ],
        ];
    }

    /**
     * Returns the tools catalog exposed by the MCP gateway.
     *
     * @return list<array<string, mixed>>
     */
    public function getToolsCatalog(): array
    {
        return [
            [
                'tool' => 'search-tourism',
                'method' => 'POST',
                'path' => '/mcp/v1/tools/search-tourism',
                'description' => 'Pesquisa recursos turisticos relevantes para assistentes, chats e agentes urbanos.',
            ],
            [
                'tool' => 'search-events',
                'method' => 'POST',
                'path' => '/mcp/v1/tools/search-events',
                'description' => 'Pesquisa eventos por tema, texto livre e filtros simples.',
            ],
            [
                'tool' => 'recommend-itinerary',
                'method' => 'POST',
                'path' => '/mcp/v1/tools/recommend-itinerary',
                'description' => 'Sugere um roteiro inicial com heuristicas para agentes conversacionais.',
            ],
            [
                'tool' => 'get-city-indicators',
                'method' => 'POST',
                'path' => '/mcp/v1/tools/get-city-indicators',
                'description' => 'Entrega indicadores urbanos e turisticos para respostas analiticas e contextualizadas.',
            ],
        ];
    }

    /**
     * Returns the contexts catalog exposed by the MCP gateway.
     *
     * @return list<array<string, mixed>>
     */
    public function getContextsCatalog(): array
    {
        return [
            [
                'context' => 'tourism',
                'path' => '/mcp/v1/context/tourism',
                'description' => 'Contexto curado do ecossistema turistico para assistentes e agentes.',
            ],
            [
                'context' => 'city',
                'path' => '/mcp/v1/context/city',
                'description' => 'Contexto urbano-institucional com sinais de cidade, governanca e indicadores.',
            ],
        ];
    }

    /**
     * Returns one resource definition.
     *
     * @return array<string, mixed>
     */
    private function getResourceDefinition(string $resource): array
    {
        $definitions = $this->resourceDefinitions();

        if (!isset($definitions[$resource])) {
            throw new \InvalidArgumentException(sprintf('Unknown MCP resource "%s".', $resource));
        }

        return $definitions[$resource];
    }

    /**
     * Builds the query builder used by MCP resource listings.
     *
     * @param array<string, mixed> $query
     */
    private function createResourceQueryBuilder(string $resource, array $query): QueryBuilder
    {
        $definition = $this->getResourceDefinition($resource);
        $queryBuilder = $this->entityManager->getRepository($definition['entity'])->createQueryBuilder('item');
        $metadata = $this->entityManager->getClassMetadata($definition['entity']);

        if ($metadata->hasField('active')) {
            $queryBuilder
                ->andWhere('item.active = :active')
                ->setParameter('active', true)
            ;
        }

        foreach ($definition['filters'] as $parameter => $field) {
            $value = trim((string) ($query[$parameter] ?? ''));

            if ('' === $value || !$metadata->hasField($field)) {
                continue;
            }

            $queryBuilder
                ->andWhere(sprintf('item.%s = :%s', $field, $parameter))
                ->setParameter($parameter, $value)
            ;
        }

        $search = trim((string) ($query['search'] ?? $query['query'] ?? ''));
        if ('' !== $search) {
            $expression = $queryBuilder->expr()->orX();

            foreach ($definition['search_fields'] as $index => $field) {
                if (!$metadata->hasField($field)) {
                    continue;
                }

                $parameter = sprintf('search_%d', $index);
                $expression->add(sprintf('LOWER(item.%s) LIKE :%s', $field, $parameter));
                $queryBuilder->setParameter($parameter, '%'.mb_strtolower($search).'%');
            }

            if ([] !== $expression->getParts()) {
                $queryBuilder->andWhere($expression);
            }
        }

        foreach ($definition['order_by'] as $field => $direction) {
            if ($metadata->hasField($field)) {
                $queryBuilder->addOrderBy(sprintf('item.%s', $field), $direction);
            }
        }

        return $queryBuilder;
    }

    /**
     * Resolves pagination parameters with defensive limits for MCP consumers.
     *
     * @param array<string, mixed> $query
     *
     * @return array{0: int, 1: int}
     */
    private function resolvePagination(array $query): array
    {
        $page = max(1, (int) ($query['page'] ?? 1));
        $limit = min(self::MAX_LIMIT, max(1, (int) ($query['limit'] ?? self::DEFAULT_LIMIT)));

        return [$page, $limit];
    }

    /**
     * Returns a compact list of normalized items for tool execution.
     *
     * @param array<string, mixed> $query
     *
     * @return list<array<string, mixed>>
     */
    private function fetchResourceItems(string $resource, array $query, int $limit): array
    {
        $definition = $this->getResourceDefinition($resource);
        $items = $this->createResourceQueryBuilder($resource, $query)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult()
        ;

        return array_map($definition['normalizer'], $items);
    }

    /**
     * Executes a cross-resource tourism search for AI assistants.
     *
     * @param array<string, mixed> $input
     *
     * @return array{data: list<array<string, mixed>>, meta: array<string, mixed>}
     */
    private function searchTourismTool(array $input): array
    {
        $query = trim((string) ($input['query'] ?? $input['search'] ?? ''));
        $limit = min(12, max(1, (int) ($input['limit'] ?? 6)));
        $perResourceLimit = max(1, (int) ceil($limit / 3));

        $spots = array_map(
            static fn (array $item): array => $item + ['resource' => 'tourist-spots'],
            $this->fetchResourceItems('tourist-spots', ['query' => $query, 'district' => $input['district'] ?? null], $perResourceLimit),
        );
        $accommodations = array_map(
            static fn (array $item): array => $item + ['resource' => 'accommodations'],
            $this->fetchResourceItems('accommodations', ['query' => $query, 'district' => $input['district'] ?? null], $perResourceLimit),
        );
        $guides = array_map(
            static fn (array $item): array => $item + ['resource' => 'guides'],
            $this->fetchResourceItems('guides', ['query' => $query], $perResourceLimit),
        );

        $data = array_slice(array_merge($spots, $accommodations, $guides), 0, $limit);

        return [
            'data' => $data,
            'meta' => [
                'query' => $query,
                'limit' => $limit,
                'sources' => ['tourist-spots', 'accommodations', 'guides'],
                'purpose' => 'tourism-discovery',
            ],
        ];
    }

    /**
     * Executes an event-focused search for AI assistants.
     *
     * @param array<string, mixed> $input
     *
     * @return array{data: list<array<string, mixed>>, meta: array<string, mixed>}
     */
    private function searchEventsTool(array $input): array
    {
        $limit = min(12, max(1, (int) ($input['limit'] ?? 6)));
        $data = $this->fetchResourceItems('events', [
            'query' => $input['query'] ?? $input['search'] ?? '',
            'category' => $input['category'] ?? '',
            'district' => $input['district'] ?? '',
        ], $limit);

        return [
            'data' => $data,
            'meta' => [
                'query' => trim((string) ($input['query'] ?? $input['search'] ?? '')),
                'category' => $input['category'] ?? null,
                'limit' => $limit,
                'purpose' => 'event-discovery',
            ],
        ];
    }

    /**
     * Recommends a lightweight itinerary using available tourism resources.
     *
     * @param array<string, mixed> $input
     *
     * @return array{data: list<array<string, mixed>>, meta: array<string, mixed>}
     */
    private function recommendItineraryTool(array $input): array
    {
        $interests = $this->normalizeList($input['interests'] ?? $input['query'] ?? '');
        $district = trim((string) ($input['district'] ?? ''));
        $search = implode(' ', $interests);
        $spots = $this->fetchResourceItems('tourist-spots', ['query' => $search, 'district' => $district], 3);

        if ([] === $spots) {
            $spots = $this->fetchResourceItems('tourist-spots', ['district' => $district], 3);
        }

        $events = $this->fetchResourceItems('events', ['query' => $search, 'district' => $district], 2);
        $accommodations = $this->fetchResourceItems('accommodations', ['district' => $district], 1);

        $itinerary = [];
        $order = 1;

        foreach ($spots as $spot) {
            $itinerary[] = [
                'order' => $order++,
                'type' => 'tourist-spot',
                'title' => $spot['name'] ?? 'Ponto turistico',
                'summary' => $spot['category'] ?? 'Atrativo turistico',
                'reason' => 'Incluido por aderencia ao perfil e relevancia para a experiencia turistica urbana.',
            ];
        }

        foreach ($events as $event) {
            $itinerary[] = [
                'order' => $order++,
                'type' => 'event',
                'title' => $event['title'] ?? 'Evento',
                'summary' => $event['category'] ?? 'Programacao cultural',
                'reason' => 'Complementa o roteiro com agenda local e dinamismo territorial.',
            ];
        }

        foreach ($accommodations as $accommodation) {
            $itinerary[] = [
                'order' => $order++,
                'type' => 'accommodation',
                'title' => $accommodation['name'] ?? 'Hospedagem',
                'summary' => $accommodation['category'] ?? 'Apoio operacional',
                'reason' => 'Oferece apoio logistico para permanencia e deslocamento no destino.',
            ];
        }

        return [
            'data' => $itinerary,
            'meta' => [
                'profile' => $input['profile'] ?? 'visitante-geral',
                'district' => '' === $district ? null : $district,
                'interests' => $interests,
                'durationHours' => (int) ($input['durationHours'] ?? 6),
                'strategy' => 'heuristic-curated-itinerary',
            ],
        ];
    }

    /**
     * Returns indicator data prepared for analytical prompts and agents.
     *
     * @param array<string, mixed> $input
     *
     * @return array{data: list<array<string, mixed>>, meta: array<string, mixed>}
     */
    private function getCityIndicatorsTool(array $input): array
    {
        $limit = min(12, max(1, (int) ($input['limit'] ?? 6)));
        $data = $this->fetchResourceItems('indicators', [
            'query' => $input['query'] ?? '',
            'category' => $input['category'] ?? '',
            'source' => $input['source'] ?? '',
        ], $limit);

        return [
            'data' => $data,
            'meta' => [
                'category' => $input['category'] ?? null,
                'source' => $input['source'] ?? null,
                'limit' => $limit,
                'purpose' => 'city-analytics',
            ],
        ];
    }

    /**
     * Returns the tourism context prepared for AI assistants.
     *
     * @return array{data: array<string, mixed>, meta: array<string, mixed>}
     */
    private function getTourismContextPayload(): array
    {
        $featuredSpots = $this->fetchResourceItems('tourist-spots', [], 3);
        $featuredEvents = $this->fetchResourceItems('events', [], 3);

        return [
            'data' => [
                'destination' => 'Olinda',
                'positioning' => 'Destino historico-cultural com forte valor patrimonial, economia criativa e turismo urbano.',
                'assistantUseCases' => [
                    'atendimento turistico conversacional',
                    'recomendacao de roteiro',
                    'respostas contextualizadas sobre atrativos e agenda',
                ],
                'featuredResources' => [
                    'touristSpots' => $featuredSpots,
                    'events' => $featuredEvents,
                ],
            ],
            'meta' => [
                'audience' => 'llms-agents-assistants',
                'focus' => 'tourism',
                'gateway' => 'Olinda360 MCP',
            ],
        ];
    }

    /**
     * Returns the city-level context prepared for AI assistants.
     *
     * @return array{data: array<string, mixed>, meta: array<string, mixed>}
     */
    private function getCityContextPayload(): array
    {
        $indicatorSnapshot = $this->fetchResourceItems('indicators', [], 4);
        $dataSources = $this->entityManager->getRepository(DataSource::class)->count([]);

        return [
            'data' => [
                'city' => 'Olinda',
                'state' => 'PE',
                'governanceModel' => 'Plataforma de governanca e inteligencia turistica preparada para interoperabilidade com IA.',
                'operationalPillars' => [
                    'governanca humana de dados',
                    'integracoes e monitoramento batch',
                    'api interna para integracao',
                    'api publica para dados abertos',
                    'camada MCP para agentes e LLMs',
                ],
                'indicatorSnapshot' => $indicatorSnapshot,
                'dataSourceCount' => $dataSources,
            ],
            'meta' => [
                'focus' => 'city',
                'preparedForAgents' => true,
                'gateway' => 'Olinda360 MCP',
            ],
        ];
    }

    /**
     * Normalizes a scalar or list input into a string list.
     *
     * @return list<string>
     */
    private function normalizeList(mixed $value): array
    {
        if (is_array($value)) {
            return array_values(array_filter(array_map(static fn (mixed $item): string => trim((string) $item), $value), static fn (string $item): bool => '' !== $item));
        }

        $stringValue = trim((string) $value);

        if ('' === $stringValue) {
            return [];
        }

        return array_values(array_filter(array_map('trim', explode(',', $stringValue)), static fn (string $item): bool => '' !== $item));
    }

    /**
     * Returns the MCP resource definitions and normalizers.
     *
     * @return array<string, array<string, mixed>>
     */
    private function resourceDefinitions(): array
    {
        return [
            'tourist-spots' => [
                'entity' => TouristSpot::class,
                'label' => 'Pontos Turisticos',
                'description' => 'Atrativos, infraestrutura e informacoes de visita para assistentes e agentes urbanos.',
                'search_fields' => ['name', 'description', 'history', 'address'],
                'filters' => ['category' => 'category', 'district' => 'district', 'source' => 'source'],
                'order_by' => ['name' => 'ASC'],
                'normalizer' => fn (object $item): array => $this->normalizeTouristSpot($item),
            ],
            'events' => [
                'entity' => TourismEvent::class,
                'label' => 'Eventos',
                'description' => 'Agenda e programacao turistica para copilotos, agentes e assistentes de experiencia.',
                'search_fields' => ['title', 'description', 'location'],
                'filters' => ['category' => 'category', 'district' => 'district', 'source' => 'source'],
                'order_by' => ['startDate' => 'ASC', 'title' => 'ASC'],
                'normalizer' => fn (object $item): array => $this->normalizeEvent($item),
            ],
            'accommodations' => [
                'entity' => Accommodation::class,
                'label' => 'Hospedagens',
                'description' => 'Meios de hospedagem e facilidades operacionais para roteiros e assistentes urbanos.',
                'search_fields' => ['name', 'description', 'address'],
                'filters' => ['category' => 'category', 'district' => 'district'],
                'order_by' => ['name' => 'ASC'],
                'normalizer' => fn (object $item): array => $this->normalizeAccommodation($item),
            ],
            'guides' => [
                'entity' => TouristGuide::class,
                'label' => 'Guias Turisticos',
                'description' => 'Guias e especialistas preparados para atendimento contextualizado e roteiros acompanhados.',
                'search_fields' => ['name', 'serviceRegion'],
                'filters' => [],
                'order_by' => ['name' => 'ASC'],
                'normalizer' => fn (object $item): array => $this->normalizeGuide($item),
            ],
            'indicators' => [
                'entity' => Indicator::class,
                'label' => 'Indicadores',
                'description' => 'Indicadores estrategicos para respostas analiticas, contextualizacao urbana e interoperabilidade inteligente.',
                'search_fields' => ['title', 'description'],
                'filters' => ['category' => 'category', 'source' => 'source'],
                'order_by' => ['referenceDate' => 'DESC', 'title' => 'ASC'],
                'normalizer' => fn (object $item): array => $this->normalizeIndicator($item),
            ],
        ];
    }

    /**
     * Maps a tourist spot to the MCP resource shape.
     *
     * @return array<string, mixed>
     */
    private function normalizeTouristSpot(object $item): array
    {
        /** @var TouristSpot $item */
        return [
            'id' => $item->id,
            'name' => $item->name,
            'slug' => $item->slug,
            'category' => $item->category,
            'description' => $item->description,
            'district' => $item->district,
            'latitude' => $item->latitude,
            'longitude' => $item->longitude,
            'source' => $item->source,
        ];
    }

    /**
     * Maps an event to the MCP resource shape.
     *
     * @return array<string, mixed>
     */
    private function normalizeEvent(object $item): array
    {
        /** @var TourismEvent $item */
        return [
            'id' => $item->id,
            'title' => $item->title,
            'slug' => $item->slug,
            'category' => $item->category,
            'description' => $item->description,
            'location' => $item->location,
            'district' => $item->district,
            'startDate' => $item->startDate->format(\DateTimeInterface::ATOM),
            'endDate' => null === $item->endDate ? null : $item->endDate->format(\DateTimeInterface::ATOM),
            'source' => $item->source,
        ];
    }

    /**
     * Maps an accommodation to the MCP resource shape.
     *
     * @return array<string, mixed>
     */
    private function normalizeAccommodation(object $item): array
    {
        /** @var Accommodation $item */
        return [
            'id' => $item->id,
            'name' => $item->name,
            'slug' => $item->slug,
            'category' => $item->category,
            'description' => $item->description,
            'address' => $item->address,
            'district' => $item->district,
            'latitude' => $item->latitude,
            'longitude' => $item->longitude,
            'accessibility' => $item->accessibility,
            'website' => $item->website,
        ];
    }

    /**
     * Maps a tourist guide to the MCP resource shape.
     *
     * @return array<string, mixed>
     */
    private function normalizeGuide(object $item): array
    {
        /** @var TouristGuide $item */
        return [
            'id' => $item->id,
            'name' => $item->name,
            'languages' => $item->languages ?? [],
            'specialties' => $item->specialties ?? [],
            'serviceRegion' => $item->serviceRegion,
            'instagram' => $item->instagram,
        ];
    }

    /**
     * Maps an indicator to the MCP resource shape.
     *
     * @return array<string, mixed>
     */
    private function normalizeIndicator(object $item): array
    {
        /** @var Indicator $item */
        return [
            'id' => $item->id,
            'title' => $item->title,
            'slug' => $item->slug,
            'category' => $item->category,
            'value' => $item->value,
            'unit' => $item->unit,
            'referenceDate' => $item->referenceDate->format('Y-m-d'),
            'source' => $item->source,
            'description' => $item->description,
        ];
    }
}