<?php

namespace App\Service;

// Generated by GitHub Copilot
final class PublicApiSpecificationBuilder
{
    /**
     * Returns the endpoint catalog shown in the human-readable docs page.
     *
     * @return list<array{method: string, path: string, description: string}>
     */
    public function getEndpoints(): array
    {
        return [
            ['method' => 'GET', 'path' => '/public-api/v1/status', 'description' => 'Status operacional da API pública.'],
            ['method' => 'GET', 'path' => '/public-api/v1/openapi.json', 'description' => 'Especificação OpenAPI simplificada da API pública.'],
            ['method' => 'GET', 'path' => '/public-api/v1/tourist-spots', 'description' => 'Lista pontos turísticos ativos com filtros por category, district, source e search.'],
            ['method' => 'GET', 'path' => '/public-api/v1/tourist-spots/{id}', 'description' => 'Detalhe público de um ponto turístico ativo.'],
            ['method' => 'GET', 'path' => '/public-api/v1/events', 'description' => 'Lista eventos públicos com paginação e filtros.'],
            ['method' => 'GET', 'path' => '/public-api/v1/events/{id}', 'description' => 'Detalhe público de um evento.'],
            ['method' => 'GET', 'path' => '/public-api/v1/accommodations', 'description' => 'Lista hospedagens ativas sem contatos privados.'],
            ['method' => 'GET', 'path' => '/public-api/v1/accommodations/{id}', 'description' => 'Detalhe público de uma hospedagem ativa.'],
            ['method' => 'GET', 'path' => '/public-api/v1/guides', 'description' => 'Lista guias ativos sem email e telefone privados.'],
            ['method' => 'GET', 'path' => '/public-api/v1/guides/{id}', 'description' => 'Detalhe público de um guia ativo.'],
            ['method' => 'GET', 'path' => '/public-api/v1/indicators', 'description' => 'Lista indicadores e séries de referência.'],
            ['method' => 'GET', 'path' => '/public-api/v1/indicators/{id}', 'description' => 'Detalhe público de um indicador.'],
            ['method' => 'GET', 'path' => '/public-api/v1/data-sources', 'description' => 'Lista fontes de dados ativas usadas no ecossistema Olinda360.'],
            ['method' => 'GET', 'path' => '/public-api/v1/data-sources/{id}', 'description' => 'Detalhe público de uma fonte de dados ativa.'],
        ];
    }

    /**
     * Returns the example URLs shown in the human-readable docs page.
     *
     * @return list<string>
     */
    public function getExamples(): array
    {
        return [
            '/public-api/v1/tourist-spots?category=Cultural&district=Sitio Historico&page=1&limit=10',
            '/public-api/v1/events?search=carnaval&limit=5',
            '/public-api/v1/indicators?source=Secretaria de Turismo',
            '/public-api/v1/guides?search=olinda',
        ];
    }

    /**
     * Returns the accepted query parameters shown in the docs page.
     *
     * @return list<array{name: string, description: string}>
     */
    public function getParameters(): array
    {
        return [
            ['name' => 'page', 'description' => 'Número da página, começando em 1.'],
            ['name' => 'limit', 'description' => 'Quantidade por página, com máximo de 100 registros.'],
            ['name' => 'search', 'description' => 'Busca textual parcial nos campos públicos relevantes do recurso.'],
            ['name' => 'category', 'description' => 'Filtro exato por categoria quando o recurso possui esse campo.'],
            ['name' => 'district', 'description' => 'Filtro exato por bairro ou distrito quando disponível.'],
            ['name' => 'source', 'description' => 'Filtro exato por fonte de origem quando disponível.'],
        ];
    }

    /**
     * Builds a simplified OpenAPI 3.0 document for the public read-only API.
     *
     * @return array<string, mixed>
     */
    public function buildOpenApiDocument(): array
    {
        $commonParameters = [
            ['$ref' => '#/components/parameters/page'],
            ['$ref' => '#/components/parameters/limit'],
            ['$ref' => '#/components/parameters/search'],
            ['$ref' => '#/components/parameters/category'],
            ['$ref' => '#/components/parameters/district'],
            ['$ref' => '#/components/parameters/source'],
        ];

        return [
            'openapi' => '3.0.3',
            'info' => [
                'title' => 'Olinda360 Public API',
                'version' => 'v1',
                'description' => 'Especificação OpenAPI simplificada da API pública de dados abertos turísticos de Olinda.',
            ],
            'servers' => [
                ['url' => '/public-api/v1', 'description' => 'Base path da API pública versionada'],
            ],
            'tags' => [
                ['name' => 'Status', 'description' => 'Estado operacional da API pública.'],
                ['name' => 'Tourist Spots', 'description' => 'Consulta pública de pontos turísticos ativos.'],
                ['name' => 'Events', 'description' => 'Consulta pública de eventos.'],
                ['name' => 'Accommodations', 'description' => 'Consulta pública de hospedagens ativas.'],
                ['name' => 'Guides', 'description' => 'Consulta pública de guias ativos.'],
                ['name' => 'Indicators', 'description' => 'Consulta pública de indicadores.'],
                ['name' => 'Data Sources', 'description' => 'Consulta pública de fontes de dados.'],
            ],
            'paths' => [
                '/status' => [
                    'get' => [
                        'tags' => ['Status'],
                        'summary' => 'Status da API pública',
                        'responses' => [
                            '200' => [
                                'description' => 'Serviço online.',
                                'content' => [
                                    'application/json' => [
                                        'schema' => [
                                            'type' => 'object',
                                            'properties' => [
                                                'status' => ['type' => 'string', 'example' => 'online'],
                                                'name' => ['type' => 'string', 'example' => 'Olinda360 Public API'],
                                                'version' => ['type' => 'string', 'example' => 'v1'],
                                                'description' => ['type' => 'string'],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
                '/tourist-spots' => [
                    'get' => $this->buildCollectionOperation('Lista pontos turísticos ativos.', 'Tourist Spots', $commonParameters),
                ],
                '/tourist-spots/{id}' => [
                    'get' => $this->buildItemOperation('Retorna o detalhe de um ponto turístico ativo.', 'Tourist Spots'),
                ],
                '/events' => [
                    'get' => $this->buildCollectionOperation('Lista eventos públicos.', 'Events', $commonParameters),
                ],
                '/events/{id}' => [
                    'get' => $this->buildItemOperation('Retorna o detalhe de um evento.', 'Events'),
                ],
                '/accommodations' => [
                    'get' => $this->buildCollectionOperation('Lista hospedagens ativas sem contatos privados.', 'Accommodations', $commonParameters),
                ],
                '/accommodations/{id}' => [
                    'get' => $this->buildItemOperation('Retorna o detalhe de uma hospedagem ativa.', 'Accommodations'),
                ],
                '/guides' => [
                    'get' => $this->buildCollectionOperation('Lista guias ativos sem email e telefone privados.', 'Guides', $commonParameters),
                ],
                '/guides/{id}' => [
                    'get' => $this->buildItemOperation('Retorna o detalhe de um guia ativo.', 'Guides'),
                ],
                '/indicators' => [
                    'get' => $this->buildCollectionOperation('Lista indicadores públicos.', 'Indicators', $commonParameters),
                ],
                '/indicators/{id}' => [
                    'get' => $this->buildItemOperation('Retorna o detalhe de um indicador.', 'Indicators'),
                ],
                '/data-sources' => [
                    'get' => $this->buildCollectionOperation('Lista fontes de dados ativas.', 'Data Sources', $commonParameters),
                ],
                '/data-sources/{id}' => [
                    'get' => $this->buildItemOperation('Retorna o detalhe de uma fonte de dados ativa.', 'Data Sources'),
                ],
            ],
            'components' => [
                'parameters' => [
                    'page' => $this->buildQueryParameter('page', 'integer', 'Número da página, começando em 1.'),
                    'limit' => $this->buildQueryParameter('limit', 'integer', 'Quantidade por página, com máximo de 100 registros.'),
                    'search' => $this->buildQueryParameter('search', 'string', 'Busca textual parcial nos campos públicos relevantes.'),
                    'category' => $this->buildQueryParameter('category', 'string', 'Filtro exato por categoria quando disponível.'),
                    'district' => $this->buildQueryParameter('district', 'string', 'Filtro exato por bairro ou distrito quando disponível.'),
                    'source' => $this->buildQueryParameter('source', 'string', 'Filtro exato por fonte de origem quando disponível.'),
                    'id' => [
                        'name' => 'id',
                        'in' => 'path',
                        'required' => true,
                        'description' => 'Identificador numérico do recurso público.',
                        'schema' => ['type' => 'integer'],
                    ],
                ],
                'schemas' => [
                    'Meta' => [
                        'type' => 'object',
                        'properties' => [
                            'page' => ['type' => 'integer', 'example' => 1],
                            'limit' => ['type' => 'integer', 'example' => 20],
                            'total' => ['type' => 'integer', 'example' => 100],
                            'source' => ['type' => 'string', 'example' => 'Olinda360'],
                            'license' => ['type' => 'string', 'example' => 'Dados abertos para uso publico'],
                            'version' => ['type' => 'string', 'example' => 'v1'],
                        ],
                    ],
                    'CollectionResponse' => [
                        'type' => 'object',
                        'properties' => [
                            'data' => ['type' => 'array', 'items' => ['type' => 'object']],
                            'meta' => ['$ref' => '#/components/schemas/Meta'],
                        ],
                    ],
                    'ItemResponse' => [
                        'type' => 'object',
                        'properties' => [
                            'data' => ['type' => 'object'],
                            'meta' => [
                                'type' => 'object',
                                'properties' => [
                                    'source' => ['type' => 'string', 'example' => 'Olinda360'],
                                    'license' => ['type' => 'string', 'example' => 'Dados abertos para uso publico'],
                                    'version' => ['type' => 'string', 'example' => 'v1'],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }

    /**
     * Builds a simplified GET collection operation block.
     *
     * @param list<array<string, string>> $parameters
     * @return array<string, mixed>
     */
    private function buildCollectionOperation(string $summary, string $tag, array $parameters): array
    {
        return [
            'tags' => [$tag],
            'summary' => $summary,
            'parameters' => $parameters,
            'responses' => [
                '200' => [
                    'description' => 'Consulta realizada com sucesso.',
                    'content' => [
                        'application/json' => [
                            'schema' => ['$ref' => '#/components/schemas/CollectionResponse'],
                        ],
                    ],
                ],
            ],
        ];
    }

    /**
     * Builds a simplified GET item operation block.
     *
     * @return array<string, mixed>
     */
    private function buildItemOperation(string $summary, string $tag): array
    {
        return [
            'tags' => [$tag],
            'summary' => $summary,
            'parameters' => [
                ['$ref' => '#/components/parameters/id'],
            ],
            'responses' => [
                '200' => [
                    'description' => 'Consulta realizada com sucesso.',
                    'content' => [
                        'application/json' => [
                            'schema' => ['$ref' => '#/components/schemas/ItemResponse'],
                        ],
                    ],
                ],
                '404' => [
                    'description' => 'Recurso público não encontrado.',
                ],
            ],
        ];
    }

    /**
     * Builds a reusable query parameter block.
     *
     * @return array<string, mixed>
     */
    private function buildQueryParameter(string $name, string $type, string $description): array
    {
        return [
            'name' => $name,
            'in' => 'query',
            'required' => false,
            'description' => $description,
            'schema' => ['type' => $type],
        ];
    }
}