<?php

namespace App\Service;

use Symfony\Component\HttpFoundation\JsonResponse;

// Generated by GitHub Copilot
final class PublicApiResponseBuilder
{
    /**
     * Builds a paginated collection payload for the public API.
     *
     * @param list<array<string, mixed>> $data
     */
    public function collection(array $data, int $page, int $limit, int $total): JsonResponse
    {
        return new JsonResponse([
            'data' => $data,
            'meta' => [
                'page' => $page,
                'limit' => $limit,
                'total' => $total,
                'source' => 'Olinda360',
                'license' => 'Dados abertos para uso publico',
                'version' => 'v1',
            ],
        ]);
    }

    /**
     * Builds a single-item payload for the public API.
     *
     * @param array<string, mixed> $data
     */
    public function item(array $data): JsonResponse
    {
        return new JsonResponse([
            'data' => $data,
            'meta' => [
                'source' => 'Olinda360',
                'license' => 'Dados abertos para uso publico',
                'version' => 'v1',
            ],
        ]);
    }

    /**
     * Builds a service status payload for the public API.
     *
     * @param array<string, mixed> $payload
     */
    public function status(array $payload): JsonResponse
    {
        return new JsonResponse($payload);
    }
}