<?php

namespace App\Form;

use App\Entity\Accommodation;
use App\Entity\Organization;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

// Generated by GitHub Copilot
final class AccommodationType extends AbstractType
{
    /**
     * Builds the manual maintenance form for accommodations.
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, ['label' => 'Nome'])
            ->add('slug', TextType::class, ['label' => 'Slug', 'required' => false])
            ->add('category', TextType::class, ['label' => 'Categoria'])
            ->add('cadasturCode', TextType::class, ['label' => 'Código Cadastur', 'required' => false])
            ->add('address', TextType::class, ['label' => 'Endereço'])
            ->add('district', TextType::class, ['label' => 'Bairro', 'required' => false])
            ->add('latitude', TextType::class, ['label' => 'Latitude', 'required' => false])
            ->add('longitude', TextType::class, ['label' => 'Longitude', 'required' => false])
            ->add('rooms', IntegerType::class, ['label' => 'Quartos', 'required' => false])
            ->add('beds', IntegerType::class, ['label' => 'Leitos', 'required' => false])
            ->add('website', TextType::class, ['label' => 'Website', 'required' => false])
            ->add('instagram', TextType::class, ['label' => 'Instagram', 'required' => false])
            ->add('phone', TextType::class, ['label' => 'Telefone', 'required' => false])
            ->add('email', TextType::class, ['label' => 'E-mail', 'required' => false])
            ->add('organization', EntityType::class, [
                'class' => Organization::class,
                'choice_label' => 'name',
                'required' => false,
                'placeholder' => 'Selecione uma organização',
                'label' => 'Organização responsável',
            ])
            ->add('description', TextareaType::class, ['label' => 'Descrição', 'required' => false, 'attr' => ['rows' => 5]])
            ->add('wifi', CheckboxType::class, ['label' => 'Possui Wi-Fi', 'required' => false])
            ->add('parking', CheckboxType::class, ['label' => 'Possui estacionamento', 'required' => false])
            ->add('accessibility', CheckboxType::class, ['label' => 'Possui acessibilidade', 'required' => false])
            ->add('active', CheckboxType::class, ['label' => 'Registro ativo', 'required' => false])
        ;
    }

    /**
     * Configures the managed entity class for the form.
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Accommodation::class,
        ]);
    }
}