<?php

namespace App\Form;

use App\Entity\BatchRoutine;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

// Generated by GitHub Copilot
final class BatchRoutineType extends AbstractType
{
    /**
     * Builds the manual maintenance form for batch routines.
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, ['label' => 'Nome'])
            ->add('slug', TextType::class, ['label' => 'Slug', 'required' => false])
            ->add('sourceName', TextType::class, ['label' => 'Fonte'])
            ->add('sourceType', TextType::class, ['label' => 'Tipo da fonte'])
            ->add('apiUrl', TextType::class, ['label' => 'Endpoint', 'required' => false])
            ->add('cronExpression', TextType::class, ['label' => 'Expressão cron', 'required' => false])
            ->add('scheduledTime', TextType::class, ['label' => 'Horário agendado', 'required' => false])
            ->add('status', ChoiceType::class, [
                'label' => 'Status',
                'choices' => [
                    'Pendente' => BatchRoutine::STATUS_PENDING,
                    'Executando' => BatchRoutine::STATUS_RUNNING,
                    'Finalizado' => BatchRoutine::STATUS_SUCCESS,
                    'Alerta' => BatchRoutine::STATUS_WARNING,
                    'Falha' => BatchRoutine::STATUS_FAILED,
                    'Desativado' => BatchRoutine::STATUS_DISABLED,
                ],
            ])
            ->add('lastExecutionAt', DateTimeType::class, ['label' => 'Última execução', 'required' => false, 'widget' => 'single_text'])
            ->add('nextExecutionAt', DateTimeType::class, ['label' => 'Próxima execução', 'required' => false, 'widget' => 'single_text'])
            ->add('recordsProcessed', IntegerType::class, ['label' => 'Processados'])
            ->add('recordsCreated', IntegerType::class, ['label' => 'Criados'])
            ->add('recordsUpdated', IntegerType::class, ['label' => 'Atualizados'])
            ->add('recordsFailed', IntegerType::class, ['label' => 'Falhas'])
            ->add('executionTimeSeconds', NumberType::class, ['label' => 'Tempo de execução (s)', 'required' => false])
            ->add('description', TextareaType::class, ['label' => 'Descrição', 'required' => false, 'attr' => ['rows' => 4]])
            ->add('lastMessage', TextareaType::class, ['label' => 'Última mensagem', 'required' => false, 'attr' => ['rows' => 4]])
            ->add('active', CheckboxType::class, ['label' => 'Rotina ativa', 'required' => false])
        ;
    }

    /**
     * Configures the managed entity class for the form.
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => BatchRoutine::class,
        ]);
    }
}