<?php

namespace App\Form;

use App\Entity\DataSource;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

// Generated by GitHub Copilot
final class DataSourceType extends AbstractType
{
    /**
     * Builds the manual maintenance form for data sources.
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, ['label' => 'Nome'])
            ->add('slug', TextType::class, ['label' => 'Slug', 'required' => false])
            ->add('type', TextType::class, ['label' => 'Tipo'])
            ->add('url', TextType::class, ['label' => 'URL', 'required' => false])
            ->add('updateFrequency', TextType::class, ['label' => 'Frequência de atualização', 'required' => false])
            ->add('description', TextareaType::class, ['label' => 'Descrição', 'required' => false, 'attr' => ['rows' => 5]])
            ->add('active', CheckboxType::class, ['label' => 'Registro ativo', 'required' => false])
        ;
    }

    /**
     * Configures the managed entity class for the form.
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => DataSource::class,
        ]);
    }
}