<?php

namespace App\Form;

use App\Entity\DataProvider;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

// Generated by GitHub Copilot
final class DataProviderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nome do provedor',
            ])
            ->add('type', ChoiceType::class, [
                'label' => 'Tipo',
                'choices' => [
                    'CKAN' => DataProvider::TYPE_CKAN,
                ],
            ])
            ->add('baseUrl', UrlType::class, [
                'label' => 'Base URL',
            ])
            ->add('packageListPath', TextType::class, [
                'label' => 'Rota package_list',
                'help' => 'Ex.: /api/3/action/package_list',
            ])
            ->add('packageShowPath', TextType::class, [
                'label' => 'Rota package_show',
                'help' => 'Ex.: /api/3/action/package_show?id={package_id}',
            ])
            ->add('isActive', CheckboxType::class, [
                'label' => 'Provedor ativo',
                'required' => false,
            ])
            ->add('notes', TextareaType::class, [
                'label' => 'Observações',
                'required' => false,
                'attr' => ['rows' => 5],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => DataProvider::class,
        ]);
    }
}