<?php

namespace App\Form;

use App\Entity\Indicator;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

// Generated by GitHub Copilot
final class IndicatorType extends AbstractType
{
    /**
     * Builds the manual maintenance form for indicators.
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, ['label' => 'Título'])
            ->add('slug', TextType::class, ['label' => 'Slug', 'required' => false])
            ->add('category', TextType::class, ['label' => 'Categoria'])
            ->add('value', NumberType::class, ['label' => 'Valor'])
            ->add('unit', TextType::class, ['label' => 'Unidade', 'required' => false])
            ->add('referenceDate', DateType::class, ['label' => 'Data de referência', 'widget' => 'single_text'])
            ->add('source', TextType::class, ['label' => 'Fonte'])
            ->add('description', TextareaType::class, ['label' => 'Descrição', 'required' => false, 'attr' => ['rows' => 5]])
        ;
    }

    /**
     * Configures the managed entity class for the form.
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Indicator::class,
        ]);
    }
}