<?php

namespace App\Form;

use App\Entity\Organization;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

// Generated by GitHub Copilot
final class OrganizationType extends AbstractType
{
    /**
     * Builds the manual maintenance form for organizations.
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, ['label' => 'Nome'])
            ->add('slug', TextType::class, ['label' => 'Slug', 'required' => false])
            ->add('type', TextType::class, ['label' => 'Tipo'])
            ->add('documentNumber', TextType::class, ['label' => 'Documento', 'required' => false])
            ->add('website', TextType::class, ['label' => 'Website', 'required' => false])
            ->add('instagram', TextType::class, ['label' => 'Instagram', 'required' => false])
            ->add('phone', TextType::class, ['label' => 'Telefone', 'required' => false])
            ->add('email', TextType::class, ['label' => 'E-mail', 'required' => false])
            ->add('address', TextType::class, ['label' => 'Endereço', 'required' => false])
            ->add('district', TextType::class, ['label' => 'Bairro', 'required' => false])
            ->add('city', TextType::class, ['label' => 'Cidade'])
            ->add('state', TextType::class, ['label' => 'UF'])
            ->add('latitude', TextType::class, ['label' => 'Latitude', 'required' => false])
            ->add('longitude', TextType::class, ['label' => 'Longitude', 'required' => false])
            ->add('description', TextareaType::class, ['label' => 'Descrição', 'required' => false, 'attr' => ['rows' => 5]])
            ->add('active', CheckboxType::class, ['label' => 'Registro ativo', 'required' => false])
        ;
    }

    /**
     * Configures the managed entity class for the form.
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Organization::class,
        ]);
    }
}