<?php

namespace App\Form;

use App\Entity\Organization;
use App\Entity\TouristSpot;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

// Generated by GitHub Copilot
final class TouristSpotType extends AbstractType
{
    /**
     * Builds the manual maintenance form for tourist spots.
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, ['label' => 'Nome'])
            ->add('slug', TextType::class, ['label' => 'Slug', 'required' => false])
            ->add('category', TextType::class, ['label' => 'Categoria'])
            ->add('address', TextType::class, ['label' => 'Endereço', 'required' => false])
            ->add('district', TextType::class, ['label' => 'Bairro', 'required' => false])
            ->add('latitude', TextType::class, ['label' => 'Latitude'])
            ->add('longitude', TextType::class, ['label' => 'Longitude'])
            ->add('openingHours', TextType::class, ['label' => 'Horário de funcionamento', 'required' => false])
            ->add('ticketPrice', TextType::class, ['label' => 'Valor do ingresso', 'required' => false])
            ->add('safetyLevel', TextType::class, ['label' => 'Nível de segurança', 'required' => false])
            ->add('source', TextType::class, ['label' => 'Fonte', 'required' => false])
            ->add('organization', EntityType::class, [
                'class' => Organization::class,
                'choice_label' => 'name',
                'required' => false,
                'placeholder' => 'Selecione uma organização',
                'label' => 'Organização responsável',
            ])
            ->add('description', TextareaType::class, ['label' => 'Descrição', 'attr' => ['rows' => 5]])
            ->add('history', TextareaType::class, ['label' => 'Histórico', 'required' => false, 'attr' => ['rows' => 4]])
            ->add('accessibility', CheckboxType::class, ['label' => 'Possui acessibilidade', 'required' => false])
            ->add('hasBathroom', CheckboxType::class, ['label' => 'Possui banheiro', 'required' => false])
            ->add('hasParking', CheckboxType::class, ['label' => 'Possui estacionamento', 'required' => false])
            ->add('active', CheckboxType::class, ['label' => 'Registro ativo', 'required' => false])
        ;
    }

    /**
     * Configures the managed entity class for the form.
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TouristSpot::class,
        ]);
    }
}