<?php

namespace App\Form;

use App\Entity\Organization;
use App\Entity\TouristGuide;
use App\Form\DataTransformer\CommaSeparatedStringToArrayTransformer;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

// Generated by GitHub Copilot
final class TouristGuideType extends AbstractType
{
    /**
     * Receives the transformer used for comma-separated array fields.
     */
    public function __construct(
        private readonly CommaSeparatedStringToArrayTransformer $arrayTransformer,
    ) {
    }

    /**
     * Builds the manual maintenance form for tourist guides.
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, ['label' => 'Nome'])
            ->add('cadasturCode', TextType::class, ['label' => 'Código Cadastur', 'required' => false])
            ->add('languages', TextType::class, ['label' => 'Idiomas', 'required' => false, 'help' => 'Separe os idiomas por vírgula.'])
            ->add('specialties', TextType::class, ['label' => 'Especialidades', 'required' => false, 'help' => 'Separe as especialidades por vírgula.'])
            ->add('phone', TextType::class, ['label' => 'Telefone', 'required' => false])
            ->add('email', TextType::class, ['label' => 'E-mail', 'required' => false])
            ->add('instagram', TextType::class, ['label' => 'Instagram', 'required' => false])
            ->add('serviceRegion', TextType::class, ['label' => 'Região de atuação', 'required' => false])
            ->add('organization', EntityType::class, [
                'class' => Organization::class,
                'choice_label' => 'name',
                'required' => false,
                'placeholder' => 'Selecione uma organização',
                'label' => 'Organização vinculada',
            ])
            ->add('active', CheckboxType::class, ['label' => 'Registro ativo', 'required' => false])
        ;

        $builder->get('languages')->addModelTransformer($this->arrayTransformer);
        $builder->get('specialties')->addModelTransformer($this->arrayTransformer);
    }

    /**
     * Configures the managed entity class for the form.
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TouristGuide::class,
        ]);
    }
}