<?php

namespace App\Form;

use App\Entity\Organization;
use App\Entity\TourismEvent;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

// Generated by GitHub Copilot
final class TourismEventType extends AbstractType
{
    /**
     * Builds the manual maintenance form for tourism events.
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, ['label' => 'Título'])
            ->add('slug', TextType::class, ['label' => 'Slug', 'required' => false])
            ->add('category', TextType::class, ['label' => 'Categoria'])
            ->add('startDate', DateTimeType::class, ['label' => 'Data de início', 'widget' => 'single_text'])
            ->add('endDate', DateTimeType::class, ['label' => 'Data de término', 'required' => false, 'widget' => 'single_text'])
            ->add('location', TextType::class, ['label' => 'Local'])
            ->add('district', TextType::class, ['label' => 'Bairro', 'required' => false])
            ->add('latitude', TextType::class, ['label' => 'Latitude', 'required' => false])
            ->add('longitude', TextType::class, ['label' => 'Longitude', 'required' => false])
            ->add('expectedAudience', IntegerType::class, ['label' => 'Público esperado', 'required' => false])
            ->add('ticketUrl', TextType::class, ['label' => 'URL de ingresso', 'required' => false])
            ->add('website', TextType::class, ['label' => 'Website', 'required' => false])
            ->add('instagram', TextType::class, ['label' => 'Instagram', 'required' => false])
            ->add('source', TextType::class, ['label' => 'Fonte', 'required' => false])
            ->add('organization', EntityType::class, [
                'class' => Organization::class,
                'choice_label' => 'name',
                'required' => false,
                'placeholder' => 'Selecione uma organização',
                'label' => 'Organização responsável',
            ])
            ->add('description', TextareaType::class, ['label' => 'Descrição', 'attr' => ['rows' => 5]])
            ->add('isFree', CheckboxType::class, ['label' => 'Evento gratuito', 'required' => false])
        ;
    }

    /**
     * Configures the managed entity class for the form.
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TourismEvent::class,
        ]);
    }
}