<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

// Generated by GitHub Copilot
final class Version20260522093000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds CKAN data providers, synchronized packages, dataset resources and ingestion runs.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE data_providers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, base_url VARCHAR(255) NOT NULL, package_list_path VARCHAR(255) NOT NULL, package_show_path VARCHAR(255) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE provider_packages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data_provider_id INT NOT NULL, package_id VARCHAR(191) NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, is_monitored BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, last_checked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, raw_metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_DA5EC318152D05A7 ON provider_packages (data_provider_id)");
        $this->addSql("CREATE UNIQUE INDEX uniq_provider_package ON provider_packages (data_provider_id, package_id)");
        $this->addSql("CREATE TABLE dataset_resources (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_package_id INT NOT NULL, resource_id VARCHAR(191) NOT NULL, name VARCHAR(255) DEFAULT NULL, format VARCHAR(50) DEFAULT NULL, url VARCHAR(2048) NOT NULL, size INT DEFAULT NULL, hash VARCHAR(255) DEFAULT NULL, created_at_source TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_modified_source TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, raw_metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_DA6DCC21E736E4A5 ON dataset_resources (provider_package_id)");
        $this->addSql("CREATE UNIQUE INDEX uniq_provider_resource ON dataset_resources (provider_package_id, resource_id)");
        $this->addSql("CREATE TABLE ingestion_runs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data_provider_id INT NOT NULL, provider_package_id INT DEFAULT NULL, dataset_resource_id INT DEFAULT NULL, status VARCHAR(50) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, message TEXT DEFAULT NULL, logs JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_5D9491A7152D05A7 ON ingestion_runs (data_provider_id)");
        $this->addSql("CREATE INDEX IDX_5D9491A7E736E4A5 ON ingestion_runs (provider_package_id)");
        $this->addSql("CREATE INDEX IDX_5D9491A7FD1A4473 ON ingestion_runs (dataset_resource_id)");
        $this->addSql('ALTER TABLE provider_packages ADD CONSTRAINT FK_DA5EC318152D05A7 FOREIGN KEY (data_provider_id) REFERENCES data_providers (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dataset_resources ADD CONSTRAINT FK_DA6DCC21E736E4A5 FOREIGN KEY (provider_package_id) REFERENCES provider_packages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ingestion_runs ADD CONSTRAINT FK_5D9491A7152D05A7 FOREIGN KEY (data_provider_id) REFERENCES data_providers (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ingestion_runs ADD CONSTRAINT FK_5D9491A7E736E4A5 FOREIGN KEY (provider_package_id) REFERENCES provider_packages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ingestion_runs ADD CONSTRAINT FK_5D9491A7FD1A4473 FOREIGN KEY (dataset_resource_id) REFERENCES dataset_resources (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ingestion_runs DROP CONSTRAINT FK_5D9491A7152D05A7');
        $this->addSql('ALTER TABLE ingestion_runs DROP CONSTRAINT FK_5D9491A7E736E4A5');
        $this->addSql('ALTER TABLE ingestion_runs DROP CONSTRAINT FK_5D9491A7FD1A4473');
        $this->addSql('ALTER TABLE dataset_resources DROP CONSTRAINT FK_DA6DCC21E736E4A5');
        $this->addSql('ALTER TABLE provider_packages DROP CONSTRAINT FK_DA5EC318152D05A7');
        $this->addSql('DROP TABLE ingestion_runs');
        $this->addSql('DROP TABLE dataset_resources');
        $this->addSql('DROP TABLE provider_packages');
        $this->addSql('DROP TABLE data_providers');
    }
}