<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

// Generated by GitHub Copilot
final class Version20260517032000 extends AbstractMigration
{
    /**
     * Describes the purpose of this schema change.
     */
    public function getDescription(): string
    {
        return 'Adds the batch_routine table used by the batch monitoring module.';
    }

    /**
     * Creates the schema required by the batch monitoring module.
     */
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE batch_routine (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(191) NOT NULL, source_name VARCHAR(255) NOT NULL, source_type VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, api_url VARCHAR(255) DEFAULT NULL, cron_expression VARCHAR(100) DEFAULT NULL, scheduled_time VARCHAR(20) DEFAULT NULL, status VARCHAR(50) DEFAULT \'pending\' NOT NULL, last_execution_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, next_execution_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, records_processed INT DEFAULT 0 NOT NULL, records_created INT DEFAULT 0 NOT NULL, records_updated INT DEFAULT 0 NOT NULL, records_failed INT DEFAULT 0 NOT NULL, execution_time_seconds DOUBLE PRECISION DEFAULT NULL, last_message TEXT DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_95B3A42E989D9B62 ON batch_routine (slug)');
    }

    /**
     * Removes the batch monitoring schema.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE batch_routine');
    }
}