<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

// Generated by GitHub Copilot
final class Version20260517032000 extends AbstractMigration
{
    /**
     * Describes the purpose of this schema change.
     */
    public function getDescription(): string
    {
        return 'Adds the batch_routine table used by the batch monitoring module.';
    }

    /**
     * Creates the schema required by the batch monitoring module.
     */
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE batch_routine (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(191) NOT NULL, source_name VARCHAR(255) NOT NULL, source_type VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, api_url VARCHAR(255) DEFAULT NULL, cron_expression VARCHAR(100) DEFAULT NULL, scheduled_time VARCHAR(20) DEFAULT NULL, status VARCHAR(50) DEFAULT \'pending\' NOT NULL, last_execution_at DATETIME DEFAULT NULL, next_execution_at DATETIME DEFAULT NULL, records_processed INT DEFAULT 0 NOT NULL, records_created INT DEFAULT 0 NOT NULL, records_updated INT DEFAULT 0 NOT NULL, records_failed INT DEFAULT 0 NOT NULL, execution_time_seconds DOUBLE PRECISION DEFAULT NULL, last_message LONGTEXT DEFAULT NULL, active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_95B3A42E989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
    }

    /**
     * Removes the batch monitoring schema.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE batch_routine');
    }
}