<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260517005252 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE accommodation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(191) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(100) NOT NULL, cadastur_code VARCHAR(100) DEFAULT NULL, address VARCHAR(255) NOT NULL, district VARCHAR(100) DEFAULT NULL, latitude NUMERIC(10, 8) DEFAULT NULL, longitude NUMERIC(11, 8) DEFAULT NULL, rooms INT DEFAULT NULL, beds INT DEFAULT NULL, wifi BOOLEAN DEFAULT false NOT NULL, parking BOOLEAN DEFAULT false NOT NULL, accessibility BOOLEAN DEFAULT false NOT NULL, website VARCHAR(255) DEFAULT NULL, instagram VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, organization_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D385412989D9B62 ON accommodation (slug)');
        $this->addSql('CREATE INDEX IDX_2D38541232C8A3DE ON accommodation (organization_id)');
        $this->addSql('CREATE TABLE data_source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(191) NOT NULL, type VARCHAR(100) NOT NULL, url VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, update_frequency VARCHAR(100) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3F744E6A989D9B62 ON data_source (slug)');
        $this->addSql('CREATE TABLE indicator (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(191) NOT NULL, category VARCHAR(100) NOT NULL, value DOUBLE PRECISION NOT NULL, unit VARCHAR(50) DEFAULT NULL, reference_date DATE NOT NULL, source VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D1349DB3989D9B62 ON indicator (slug)');
        $this->addSql('CREATE TABLE organization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(191) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(100) NOT NULL, document_number VARCHAR(30) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, instagram VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, district VARCHAR(100) DEFAULT NULL, city VARCHAR(100) DEFAULT \'Olinda\' NOT NULL, state VARCHAR(2) DEFAULT \'PE\' NOT NULL, latitude NUMERIC(10, 8) DEFAULT NULL, longitude NUMERIC(11, 8) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C1EE637C989D9B62 ON organization (slug)');
        $this->addSql('CREATE TABLE symfony_demo_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, post_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_53AD8F834B89032C ON symfony_demo_comment (post_id)');
        $this->addSql('CREATE INDEX IDX_53AD8F83F675F31B ON symfony_demo_comment (author_id)');
        $this->addSql('CREATE TABLE symfony_demo_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, summary VARCHAR(255) NOT NULL, content TEXT NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_58A92E65F675F31B ON symfony_demo_post (author_id)');
        $this->addSql('CREATE TABLE symfony_demo_post_tag (post_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (post_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_6ABC1CC44B89032C ON symfony_demo_post_tag (post_id)');
        $this->addSql('CREATE INDEX IDX_6ABC1CC4BAD26311 ON symfony_demo_post_tag (tag_id)');
        $this->addSql('CREATE TABLE symfony_demo_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(191) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D5855405E237E06 ON symfony_demo_tag (name)');
        $this->addSql('CREATE TABLE symfony_demo_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(255) NOT NULL, username VARCHAR(191) NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8FB094A1F85E0677 ON symfony_demo_user (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8FB094A1E7927C74 ON symfony_demo_user (email)');
        $this->addSql('CREATE TABLE tourism_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(191) NOT NULL, description TEXT NOT NULL, category VARCHAR(100) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, location VARCHAR(255) NOT NULL, district VARCHAR(100) DEFAULT NULL, latitude NUMERIC(10, 8) DEFAULT NULL, longitude NUMERIC(11, 8) DEFAULT NULL, expected_audience INT DEFAULT NULL, is_free BOOLEAN DEFAULT true NOT NULL, ticket_url VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, instagram VARCHAR(255) DEFAULT NULL, source VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, organization_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A1CC3CC989D9B62 ON tourism_event (slug)');
        $this->addSql('CREATE INDEX IDX_6A1CC3CC32C8A3DE ON tourism_event (organization_id)');
        $this->addSql('CREATE TABLE tourist_guide (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, cadastur_code VARCHAR(100) DEFAULT NULL, languages JSON DEFAULT NULL, specialties JSON DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, instagram VARCHAR(255) DEFAULT NULL, service_region VARCHAR(255) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, organization_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_696AD74332C8A3DE ON tourist_guide (organization_id)');
        $this->addSql('CREATE TABLE tourist_spot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(191) NOT NULL, description TEXT NOT NULL, history TEXT DEFAULT NULL, category VARCHAR(100) NOT NULL, address VARCHAR(255) DEFAULT NULL, district VARCHAR(100) DEFAULT NULL, latitude NUMERIC(10, 8) NOT NULL, longitude NUMERIC(11, 8) NOT NULL, opening_hours VARCHAR(255) DEFAULT NULL, ticket_price NUMERIC(10, 2) DEFAULT NULL, accessibility BOOLEAN DEFAULT false NOT NULL, has_bathroom BOOLEAN DEFAULT false NOT NULL, has_parking BOOLEAN DEFAULT false NOT NULL, safety_level VARCHAR(50) DEFAULT NULL, source VARCHAR(100) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, organization_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F1227811989D9B62 ON tourist_spot (slug)');
        $this->addSql('CREATE INDEX IDX_F122781132C8A3DE ON tourist_spot (organization_id)');
        $this->addSql('ALTER TABLE accommodation ADD CONSTRAINT FK_2D38541232C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE symfony_demo_comment ADD CONSTRAINT FK_53AD8F834B89032C FOREIGN KEY (post_id) REFERENCES symfony_demo_post (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE symfony_demo_comment ADD CONSTRAINT FK_53AD8F83F675F31B FOREIGN KEY (author_id) REFERENCES symfony_demo_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE symfony_demo_post ADD CONSTRAINT FK_58A92E65F675F31B FOREIGN KEY (author_id) REFERENCES symfony_demo_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE symfony_demo_post_tag ADD CONSTRAINT FK_6ABC1CC44B89032C FOREIGN KEY (post_id) REFERENCES symfony_demo_post (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE symfony_demo_post_tag ADD CONSTRAINT FK_6ABC1CC4BAD26311 FOREIGN KEY (tag_id) REFERENCES symfony_demo_tag (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tourism_event ADD CONSTRAINT FK_6A1CC3CC32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tourist_guide ADD CONSTRAINT FK_696AD74332C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tourist_spot ADD CONSTRAINT FK_F122781132C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE accommodation DROP CONSTRAINT FK_2D38541232C8A3DE');
        $this->addSql('ALTER TABLE symfony_demo_comment DROP CONSTRAINT FK_53AD8F834B89032C');
        $this->addSql('ALTER TABLE symfony_demo_comment DROP CONSTRAINT FK_53AD8F83F675F31B');
        $this->addSql('ALTER TABLE symfony_demo_post DROP CONSTRAINT FK_58A92E65F675F31B');
        $this->addSql('ALTER TABLE symfony_demo_post_tag DROP CONSTRAINT FK_6ABC1CC44B89032C');
        $this->addSql('ALTER TABLE symfony_demo_post_tag DROP CONSTRAINT FK_6ABC1CC4BAD26311');
        $this->addSql('ALTER TABLE tourism_event DROP CONSTRAINT FK_6A1CC3CC32C8A3DE');
        $this->addSql('ALTER TABLE tourist_guide DROP CONSTRAINT FK_696AD74332C8A3DE');
        $this->addSql('ALTER TABLE tourist_spot DROP CONSTRAINT FK_F122781132C8A3DE');
        $this->addSql('DROP TABLE accommodation');
        $this->addSql('DROP TABLE data_source');
        $this->addSql('DROP TABLE indicator');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE symfony_demo_comment');
        $this->addSql('DROP TABLE symfony_demo_post');
        $this->addSql('DROP TABLE symfony_demo_post_tag');
        $this->addSql('DROP TABLE symfony_demo_tag');
        $this->addSql('DROP TABLE symfony_demo_user');
        $this->addSql('DROP TABLE tourism_event');
        $this->addSql('DROP TABLE tourist_guide');
        $this->addSql('DROP TABLE tourist_spot');
    }
}
