<?php

namespace App\Controller\Mcp\V1;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;

// Generated by GitHub Copilot
abstract class AbstractMcpController extends AbstractController
{
    /**
     * Builds a successful MCP JSON response using the standard wrapper.
     *
     * @param array<string, mixed> $payload
     */
    protected function successResponse(string $type, array $payload, ?string $nameKey = null, ?string $name = null): JsonResponse
    {
        $response = [
            'status' => 'success',
            'type' => $type,
            'data' => $payload['data'] ?? $payload,
        ];

        if (null !== $nameKey && null !== $name) {
            $response[$nameKey] = $name;
        }

        if (isset($payload['meta'])) {
            $response['meta'] = $payload['meta'];
        }

        return new JsonResponse($response);
    }

    /**
     * Builds an MCP error payload for invalid or unsupported requests.
     */
    protected function errorResponse(string $type, string $message, int $statusCode = 400): JsonResponse
    {
        return new JsonResponse([
            'status' => 'error',
            'type' => $type,
            'message' => $message,
        ], $statusCode);
    }

    /**
     * Parses a JSON request body or falls back to regular form parameters.
     *
     * @return array<string, mixed>
     */
    protected function parsePayload(Request $request): array
    {
        $content = trim($request->getContent());

        if ('' === $content) {
            return $request->request->all();
        }

        try {
            $payload = json_decode($content, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $exception) {
            throw new BadRequestHttpException('Invalid JSON payload for MCP tool invocation.', $exception);
        }

        return is_array($payload) ? $payload : [];
    }
}