<?php

namespace App\Controller\Mcp\V1;

use App\Service\McpContextService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class McpContextController extends AbstractMcpController
{
    /**
     * Exposes a higher-level context package for AI assistants and agents.
     */
    #[Route('/mcp/v1/context/{context}', name: 'app_mcp_v1_context_show', requirements: ['context' => McpContextService::CONTEXT_REQUIREMENT], methods: ['GET'])]
    public function show(string $context, McpContextService $contextService): JsonResponse
    {
        return $this->successResponse('context', $contextService->getContextPayload($context), 'context', $context);
    }
}