<?php

namespace App\Controller\Mcp\V1;

use App\Service\McpContextService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class McpController extends AbstractMcpController
{
    /**
     * Exposes the MCP gateway home document for future LLM and agent discovery.
     */
    #[Route('/mcp/v1', name: 'app_mcp_v1_home', methods: ['GET'])]
    public function index(McpContextService $contextService): JsonResponse
    {
        return $this->successResponse('home', ['data' => $contextService->getHomePayload()]);
    }

    /**
     * Renders the HTML documentation for the MCP gateway.
     */
    #[Route('/mcp/v1/docs', name: 'app_mcp_v1_docs', methods: ['GET'])]
    public function docs(McpContextService $contextService): Response
    {
        return $this->render('mcp/docs.html.twig', $contextService->getDocumentationPayload());
    }
}