<?php

namespace App\Controller\Mcp\V1;

use App\Service\McpContextService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class McpResourcesController extends AbstractMcpController
{
    /**
     * Lists every MCP resource made available for AI and agent discovery.
     */
    #[Route('/mcp/v1/resources', name: 'app_mcp_v1_resources', methods: ['GET'])]
    public function index(McpContextService $contextService): JsonResponse
    {
        return $this->successResponse('resource', ['data' => $contextService->getResourcesCatalog()], 'resource', 'catalog');
    }

    /**
     * Exposes one MCP resource collection using the standard AI-ready JSON wrapper.
     */
    #[Route('/mcp/v1/resources/{resource}', name: 'app_mcp_v1_resource_show', requirements: ['resource' => McpContextService::RESOURCE_REQUIREMENT], methods: ['GET'])]
    public function show(string $resource, Request $request, McpContextService $contextService): JsonResponse
    {
        return $this->successResponse('resource', $contextService->getResourcePayload($resource, $request->query->all()), 'resource', $resource);
    }
}