<?php

namespace App\Controller\Mcp\V1;

use App\Service\McpContextService;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class McpToolsController extends AbstractMcpController
{
    /**
     * Executes an MCP tool request for AI and agent interactions.
     */
    #[Route('/mcp/v1/tools/{tool}', name: 'app_mcp_v1_tool_execute', requirements: ['tool' => McpContextService::TOOL_REQUIREMENT], methods: ['POST'])]
    public function execute(string $tool, Request $request, McpContextService $contextService): JsonResponse
    {
        try {
            $payload = $this->parsePayload($request);
        } catch (\Throwable $exception) {
            return $this->errorResponse('tool', $exception->getMessage());
        }

        return $this->successResponse('tool', $contextService->executeTool($tool, $payload), 'tool', $tool);
    }
}