<?php

namespace App\Controller;

use App\Entity\BatchRoutine;
use App\Repository\BatchRoutineRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class BatchMonitorController extends AbstractController
{
    /**
     * Renders the batch observability dashboard with summary cards and routine list.
     */
    #[Route('/batch-monitor', name: 'app_batch_monitor', methods: ['GET'])]
    public function index(BatchRoutineRepository $repository): Response
    {
        $routines = $repository->findBy([], ['active' => 'DESC', 'nextExecutionAt' => 'ASC', 'name' => 'ASC']);
        $counts = $repository->countByStatus();

        return $this->render('batch_monitor/index.html.twig', [
            'routines' => $routines,
            'statusPresentation' => $this->getStatusPresentation(),
            'summary' => [
                'total' => count($routines),
                'success' => $counts[BatchRoutine::STATUS_SUCCESS] ?? 0,
                'running' => $counts[BatchRoutine::STATUS_RUNNING] ?? 0,
                'warning' => $counts[BatchRoutine::STATUS_WARNING] ?? 0,
                'failed' => $counts[BatchRoutine::STATUS_FAILED] ?? 0,
                'processed' => $repository->getTotalRecordsProcessed(),
                'averageExecutionTime' => $repository->getAverageExecutionTime(),
            ],
        ]);
    }

    /**
     * Exports batch monitoring data as CSV, optionally scoped to one routine.
     */
    #[Route('/batch-monitor/export.csv', name: 'app_batch_monitor_export_csv', methods: ['GET'])]
    public function exportCsv(Request $request, BatchRoutineRepository $repository): Response
    {
        $routineId = $request->query->getInt('routine');
        $routine = 0 === $routineId ? null : $repository->find($routineId);
        $routines = 0 === $routineId
            ? $repository->findBy([], ['name' => 'ASC'])
            : (null === $routine ? [] : [$routine]);

        $rows = [[
            'rotina',
            'fonte',
            'tipo',
            'status',
            'cron',
            'ultima_execucao',
            'proxima_execucao',
            'processados',
            'criados',
            'atualizados',
            'erros',
            'tempo',
            'mensagem',
        ]];

        foreach ($routines as $routine) {
            $rows[] = [
                $routine->getName(),
                $routine->getSourceName(),
                $routine->getSourceType(),
                $routine->getStatus(),
                (string) ($routine->getCronExpression() ?? ''),
                $this->formatDateTime($routine->getLastExecutionAt()),
                $this->formatDateTime($routine->getNextExecutionAt()),
                (string) $routine->getRecordsProcessed(),
                (string) $routine->getRecordsCreated(),
                (string) $routine->getRecordsUpdated(),
                (string) $routine->getRecordsFailed(),
                null === $routine->getExecutionTimeSeconds() ? '' : number_format($routine->getExecutionTimeSeconds(), 1, '.', ''),
                (string) ($routine->getLastMessage() ?? ''),
            ];
        }

        $filename = 0 === $routineId ? 'batch-monitor.csv' : sprintf('batch-routine-%d.csv', $routineId);

        return $this->csvResponse($filename, $rows);
    }

    /**
     * Shows the operational details for a single batch routine.
     */
    #[Route('/batch-monitor/{id<\d+>}', name: 'app_batch_monitor_show', methods: ['GET'])]
    public function show(BatchRoutine $batchRoutine): Response
    {
        return $this->render('batch_monitor/show.html.twig', [
            'routine' => $batchRoutine,
            'statusPresentation' => $this->getStatusPresentation(),
        ]);
    }

    /**
     * Provides the visual labels used across batch monitoring templates.
     *
     * @return array<string, array{label: string, tone: string}>
     */
    private function getStatusPresentation(): array
    {
        return [
            BatchRoutine::STATUS_SUCCESS => ['label' => 'Finalizado', 'tone' => 'success'],
            BatchRoutine::STATUS_RUNNING => ['label' => 'Executando', 'tone' => 'running'],
            BatchRoutine::STATUS_WARNING => ['label' => 'Alerta', 'tone' => 'warning'],
            BatchRoutine::STATUS_FAILED => ['label' => 'Falha', 'tone' => 'failed'],
            BatchRoutine::STATUS_PENDING => ['label' => 'Pendente', 'tone' => 'pending'],
            BatchRoutine::STATUS_DISABLED => ['label' => 'Desativado', 'tone' => 'disabled'],
        ];
    }

    /**
     * Formats optional timestamps for CSV and table rendering.
     */
    private function formatDateTime(?\DateTimeInterface $dateTime): string
    {
        return null === $dateTime ? '' : $dateTime->format('Y-m-d H:i:s');
    }

    /**
     * Builds a CSV download response for monitoring exports.
     *
     * @param list<array<int, string>> $rows
     */
    private function csvResponse(string $filename, array $rows): Response
    {
        $handle = fopen('php://temp', 'r+');

        if (false === $handle) {
            throw new \RuntimeException('Unable to open temporary stream for CSV export.');
        }

        foreach ($rows as $row) {
            fputcsv($handle, $row, ';');
        }

        rewind($handle);
        $content = stream_get_contents($handle);
        fclose($handle);

        if (false === $content) {
            throw new \RuntimeException('Unable to generate CSV content.');
        }

        return new Response(
            $content,
            Response::HTTP_OK,
            [
                'Content-Type' => 'text/csv; charset=UTF-8',
                'Content-Disposition' => sprintf('attachment; filename="%s"', $filename),
            ]
        );
    }
}