<?php

namespace App\Controller;

use App\Entity\Accommodation;
use App\Entity\BatchRoutine;
use App\Entity\DataSource;
use App\Entity\Indicator;
use App\Entity\Organization;
use App\Entity\TourismEvent;
use App\Entity\TouristGuide;
use App\Entity\TouristSpot;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class DashboardController extends AbstractController
{
    /**
     * Shows aggregate counters for the prototype dashboard.
     */
    #[Route('/dashboard', name: 'dashboard', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $stats = [
            'touristSpots' => $entityManager->getRepository(TouristSpot::class)->count([]),
            'events' => $entityManager->getRepository(TourismEvent::class)->count([]),
            'accommodations' => $entityManager->getRepository(Accommodation::class)->count([]),
            'guides' => $entityManager->getRepository(TouristGuide::class)->count([]),
            'organizations' => $entityManager->getRepository(Organization::class)->count([]),
            'dataSources' => $entityManager->getRepository(DataSource::class)->count([]),
            'indicators' => $entityManager->getRepository(Indicator::class)->count([]),
            'batchRoutines' => $entityManager->getRepository(BatchRoutine::class)->count([]),
            'publicApis' => 8,
        ];

        $totalRecords = array_sum([
            $stats['touristSpots'],
            $stats['events'],
            $stats['accommodations'],
            $stats['guides'],
            $stats['organizations'],
            $stats['dataSources'],
        ]);

        return $this->render('dashboard/index.html.twig', [
            'hero' => [
                'badge' => 'Business Intelligence',
                'title' => 'Dashboard de Inteligencia Turistica',
                'subtitle' => 'Central estratégica de monitoramento, governança e inteligência territorial do Olinda360.',
                'uptime' => '98,7%',
                'uptimeDescription' => 'Disponibilidade operacional da plataforma.',
                'totalRecords' => $totalRecords,
                'sourcesMonitored' => max(14, $stats['dataSources']),
            ],
            'statsCards' => [
                ['title' => 'Pontos Turisticos', 'value' => $stats['touristSpots'], 'subtitle' => 'Mapa territorial ativo', 'description' => 'Ativos monitorados com contexto geoespacial e vocação turística.', 'icon' => 'tabler:map-pin', 'tone' => 'teal'],
                ['title' => 'Eventos', 'value' => $stats['events'], 'subtitle' => 'Agenda territorial', 'description' => 'Programação estratégica com leitura de calendário e fluxo de visitantes.', 'icon' => 'tabler:calendar-event', 'tone' => 'blue'],
                ['title' => 'Hospedagens', 'value' => $stats['accommodations'], 'subtitle' => 'Infraestrutura receptiva', 'description' => 'Capacidade instalada para hospitalidade e permanência turística.', 'icon' => 'tabler:building', 'tone' => 'amber'],
                ['title' => 'Guias Turisticos', 'value' => $stats['guides'], 'subtitle' => 'Capital humano', 'description' => 'Rede operacional de mediação cultural e experiência do visitante.', 'icon' => 'tabler:user', 'tone' => 'cyan'],
                ['title' => 'Organizacoes', 'value' => $stats['organizations'], 'subtitle' => 'Ecossistema institucional', 'description' => 'Atores públicos e privados conectados à governança do turismo.', 'icon' => 'tabler:building-bank', 'tone' => 'emerald'],
                ['title' => 'Fontes de Dados', 'value' => $stats['dataSources'], 'subtitle' => 'Base de integração', 'description' => 'Canais monitorados para observabilidade e inteligência territorial.', 'icon' => 'tabler:database', 'tone' => 'slate'],
                ['title' => 'APIs Publicas', 'value' => $stats['publicApis'], 'subtitle' => 'Transparência digital', 'description' => 'Interfaces abertas para inovação cívica, pesquisa e interoperabilidade.', 'icon' => 'tabler:world-code', 'tone' => 'purple'],
                ['title' => 'Rotinas Batch', 'value' => $stats['batchRoutines'], 'subtitle' => 'Orquestração noturna', 'description' => 'Coletas e sincronizações automatizadas para BI operacional.', 'icon' => 'tabler:robot', 'tone' => 'rose'],
            ],
            'infrastructureCards' => [
                ['title' => 'API Publica', 'description' => 'Camada aberta e versionada para consumo cidadão, acadêmico e govtech.', 'icon' => 'tabler:api', 'actionLabel' => 'Acessar', 'actionPath' => 'app_public_api_v1_docs'],
                ['title' => 'Monitoramento Batch', 'description' => 'Observabilidade das rotinas de coleta e sincronização de madrugada.', 'icon' => 'tabler:clock', 'actionLabel' => 'Acessar', 'actionPath' => 'app_batch_monitor'],
                ['title' => 'Dados Abertos', 'description' => 'Catálogo institucional para transparência, pesquisa e inovação territorial.', 'icon' => 'tabler:folders', 'actionLabel' => 'Acessar', 'actionPath' => 'app_public_api_v1_docs'],
                ['title' => 'Integracoes', 'description' => 'Conexões estratégicas com APIs, formulários e sistemas parceiros.', 'icon' => 'tabler:plug-connected', 'actionLabel' => 'Acessar', 'actionPath' => 'homepage'],
                ['title' => 'Open Data', 'description' => 'Infraestrutura digital preparada para compartilhamento responsável de dados.', 'icon' => 'tabler:world', 'actionLabel' => 'Acessar', 'actionPath' => 'app_public_api_v1_openapi'],
                ['title' => 'Governanca', 'description' => 'Camada de coordenação operacional, integridade e rastreabilidade de datasets.', 'icon' => 'tabler:shield', 'actionLabel' => 'Acessar', 'actionPath' => 'dashboard'],
            ],
            'sourcesCards' => [
                ['name' => 'Cadastur', 'type' => 'Cadastro Oficial', 'status' => 'Online', 'statusTone' => 'success', 'updatedAt' => 'Hoje, 02:00', 'icon' => 'tabler:building-store'],
                ['name' => 'FNRH', 'type' => 'API Restrita', 'status' => 'Planejada', 'statusTone' => 'pending', 'updatedAt' => 'Aguardando credenciais', 'icon' => 'tabler:bed'],
                ['name' => 'OpenStreetMap', 'type' => 'Geoespacial', 'status' => 'Sincronizada', 'statusTone' => 'info', 'updatedAt' => 'Hoje, 01:30', 'icon' => 'tabler:map-2'],
                ['name' => 'IBGE', 'type' => 'Estatistica Oficial', 'status' => 'Online', 'statusTone' => 'success', 'updatedAt' => 'Hoje, 04:00', 'icon' => 'tabler:chart-bar'],
                ['name' => 'Dados Recife', 'type' => 'CSV/JSON', 'status' => 'Alerta', 'statusTone' => 'warning', 'updatedAt' => 'Ontem, 02:45', 'icon' => 'tabler:file-text'],
                ['name' => 'APIs Municipais', 'type' => 'Servicos Locais', 'status' => 'Expansao', 'statusTone' => 'primary', 'updatedAt' => 'Roadmap 2026', 'icon' => 'tabler:building-community'],
            ],
            'operationalIndicators' => [
                ['label' => 'Batch executados hoje', 'value' => '24', 'detail' => 'Janelas noturnas finalizadas com rastreabilidade completa.', 'icon' => 'tabler:clock-check'],
                ['label' => 'Registros sincronizados', 'value' => '18.420', 'detail' => 'Volume consolidado entre integrações, formulários e coletas externas.', 'icon' => 'tabler:database-import'],
                ['label' => 'APIs online', 'value' => '8/8', 'detail' => 'Disponibilidade pública e interna dentro da janela de governança.', 'icon' => 'tabler:cloud-check'],
                ['label' => 'Ultima coleta', 'value' => '05:12', 'detail' => 'Execução mais recente concluída na camada operacional.', 'icon' => 'tabler:timeline'],
                ['label' => 'Tempo medio de sincronizacao', 'value' => '37,4s', 'detail' => 'Média simulada das integrações críticas monitoradas.', 'icon' => 'tabler:gauge'],
                ['label' => 'Datasets publicos', 'value' => '14', 'detail' => 'Conjuntos de dados preparados para transparência e reutilização.', 'icon' => 'tabler:stack-2'],
            ],
            'architectureSteps' => [
                ['title' => 'Formularios', 'description' => 'Entrada estruturada de dados turísticos e operacionais.', 'icon' => 'tabler:forms'],
                ['title' => 'Integracoes/API', 'description' => 'Coletas externas, conectores e serviços institucionais.', 'icon' => 'tabler:plug-connected'],
                ['title' => 'Banco de Dados', 'description' => 'Persistência central com rastreabilidade e histórico.', 'icon' => 'tabler:database'],
                ['title' => 'Processamento Batch', 'description' => 'Orquestração e limpeza para inteligência operacional.', 'icon' => 'tabler:robot'],
                ['title' => 'API Publica', 'description' => 'Distribuição controlada de dados abertos e versionados.', 'icon' => 'tabler:world'],
                ['title' => 'Dashboard e Inteligencia', 'description' => 'Leitura executiva para governança territorial e BI.', 'icon' => 'tabler:chart-donut'],
            ],
            'quickActions' => [
                ['label' => 'Ver API Publica', 'path' => 'app_public_api_v1_docs', 'variant' => 'primary', 'icon' => 'tabler:world-code'],
                ['label' => 'Monitoramento Batch', 'path' => 'app_batch_monitor', 'variant' => 'outline-primary', 'icon' => 'tabler:database'],
                ['label' => 'Swagger API', 'url' => '/api', 'variant' => 'outline-secondary', 'icon' => 'tabler:api'],
                ['label' => 'Exportar CSV', 'path' => 'export_tourist_spots', 'variant' => 'outline-success', 'icon' => 'tabler:file-export'],
                ['label' => 'Ver Dados Abertos', 'path' => 'app_public_api_v1_openapi', 'variant' => 'outline-dark', 'icon' => 'tabler:folders'],
                ['label' => 'Nova Coleta', 'path' => 'app_batch_monitor', 'variant' => 'outline-warning', 'icon' => 'tabler:refresh'],
                ['label' => 'Dashboard Executivo', 'path' => 'dashboard', 'variant' => 'outline-info', 'icon' => 'tabler:chart-bar'],
            ],
            'stats' => $stats,
        ]);
    }
}
