<?php

namespace App\Controller;

use App\Entity\Accommodation;
use App\Entity\Indicator;
use App\Entity\TourismEvent;
use App\Entity\TouristGuide;
use App\Entity\TouristSpot;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class ExportController extends AbstractController
{
    /**
     * Renders the central page for CSV exports.
     */
    #[Route('/exports', name: 'app_exports_index', methods: ['GET'])]
    public function index(): Response
    {
        return $this->render('platform/exports.html.twig', [
            'exports' => [
                [
                    'title' => 'Pontos Turísticos',
                    'description' => 'Exportação dos atrativos com categoria, distrito e geolocalização.',
                    'icon' => 'bi-geo-alt',
                    'route' => 'export_tourist_spots',
                ],
                [
                    'title' => 'Eventos',
                    'description' => 'Agenda turística com datas, categoria e local de realização.',
                    'icon' => 'bi-calendar-event',
                    'route' => 'export_events',
                ],
                [
                    'title' => 'Hospedagens',
                    'description' => 'Capacidade receptiva, tipologia e dados operacionais da hotelaria.',
                    'icon' => 'bi-building',
                    'route' => 'export_accommodations',
                ],
                [
                    'title' => 'Guias Turísticos',
                    'description' => 'Rede de guias, idiomas e especialidades para operação turística.',
                    'icon' => 'bi-person-badge',
                    'route' => 'export_guides',
                ],
                [
                    'title' => 'Indicadores',
                    'description' => 'Séries estratégicas para análise territorial e inteligência governamental.',
                    'icon' => 'bi-graph-up-arrow',
                    'route' => 'export_indicators',
                ],
            ],
        ]);
    }

    /**
     * Exports tourist spots in CSV format.
     */
    #[Route('/export/tourist-spots.csv', name: 'export_tourist_spots', methods: ['GET'])]
    public function touristSpots(EntityManagerInterface $entityManager): Response
    {
        $items = $entityManager->getRepository(TouristSpot::class)->findBy([], ['name' => 'ASC']);
        $rows = [['id', 'name', 'category', 'district', 'latitude', 'longitude', 'active']];

        foreach ($items as $item) {
            $rows[] = [
                (string) $item->id,
                $item->name,
                $item->category,
                (string) ($item->district ?? ''),
                (string) $item->latitude,
                (string) $item->longitude,
                $item->active ? '1' : '0',
            ];
        }

        return $this->csvResponse('tourist-spots.csv', $rows);
    }

    /**
     * Exports events in CSV format.
     */
    #[Route('/export/events.csv', name: 'export_events', methods: ['GET'])]
    public function events(EntityManagerInterface $entityManager): Response
    {
        $items = $entityManager->getRepository(TourismEvent::class)->findBy([], ['startDate' => 'ASC']);
        $rows = [['id', 'title', 'category', 'start_date', 'end_date', 'location', 'is_free']];

        foreach ($items as $item) {
            $rows[] = [
                (string) $item->id,
                $item->title,
                $item->category,
                $item->startDate->format('Y-m-d H:i:s'),
                $item->endDate?->format('Y-m-d H:i:s') ?? '',
                $item->location,
                $item->isFree ? '1' : '0',
            ];
        }

        return $this->csvResponse('events.csv', $rows);
    }

    /**
     * Exports accommodations in CSV format.
     */
    #[Route('/export/accommodations.csv', name: 'export_accommodations', methods: ['GET'])]
    public function accommodations(EntityManagerInterface $entityManager): Response
    {
        $items = $entityManager->getRepository(Accommodation::class)->findBy([], ['name' => 'ASC']);
        $rows = [['id', 'name', 'category', 'district', 'rooms', 'beds', 'active']];

        foreach ($items as $item) {
            $rows[] = [
                (string) $item->id,
                $item->name,
                $item->category,
                (string) ($item->district ?? ''),
                (string) ($item->rooms ?? ''),
                (string) ($item->beds ?? ''),
                $item->active ? '1' : '0',
            ];
        }

        return $this->csvResponse('accommodations.csv', $rows);
    }

    /**
     * Exports tourist guides in CSV format.
     */
    #[Route('/export/guides.csv', name: 'export_guides', methods: ['GET'])]
    public function guides(EntityManagerInterface $entityManager): Response
    {
        $items = $entityManager->getRepository(TouristGuide::class)->findBy([], ['name' => 'ASC']);
        $rows = [['id', 'name', 'cadastur_code', 'languages', 'specialties', 'active']];

        foreach ($items as $item) {
            $rows[] = [
                (string) $item->id,
                $item->name,
                (string) ($item->cadasturCode ?? ''),
                $item->languages ? implode('|', $item->languages) : '',
                $item->specialties ? implode('|', $item->specialties) : '',
                $item->active ? '1' : '0',
            ];
        }

        return $this->csvResponse('guides.csv', $rows);
    }

    /**
     * Exports indicators in CSV format.
     */
    #[Route('/export/indicators.csv', name: 'export_indicators', methods: ['GET'])]
    public function indicators(EntityManagerInterface $entityManager): Response
    {
        $items = $entityManager->getRepository(Indicator::class)->findBy([], ['referenceDate' => 'DESC']);
        $rows = [['id', 'title', 'category', 'value', 'unit', 'reference_date', 'source']];

        foreach ($items as $item) {
            $rows[] = [
                (string) $item->id,
                $item->title,
                $item->category,
                (string) $item->value,
                (string) ($item->unit ?? ''),
                $item->referenceDate->format('Y-m-d'),
                $item->source,
            ];
        }

        return $this->csvResponse('indicators.csv', $rows);
    }

    /**
     * Builds a CSV HTTP response with proper download headers.
     */
    private function csvResponse(string $filename, array $rows): Response
    {
        $handle = fopen('php://temp', 'r+');

        if (false === $handle) {
            throw new \RuntimeException('Unable to open temporary stream for CSV export.');
        }

        foreach ($rows as $row) {
            fputcsv($handle, $row, ';');
        }

        rewind($handle);
        $content = stream_get_contents($handle);
        fclose($handle);

        if (false === $content) {
            throw new \RuntimeException('Unable to generate CSV content.');
        }

        return new Response(
            $content,
            Response::HTTP_OK,
            [
                'Content-Type' => 'text/csv; charset=UTF-8',
                'Content-Disposition' => sprintf('attachment; filename="%s"', $filename),
            ]
        );
    }
}
