<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class PlatformConsoleController extends AbstractController
{
    /**
     * Renders the executive analytics center for territorial intelligence and smart tourism.
     */
    #[Route('/analytics', name: 'app_platform_analytics', methods: ['GET'])]
    public function analytics(): Response
    {
        return $this->render('platform/analytics.html.twig', $this->buildAnalyticsDashboardContext());
    }

    /**
     * Renders the executive indicators dashboard for territorial intelligence.
     */
    #[Route('/indicators', name: 'app_platform_indicators', methods: ['GET'])]
    public function indicators(): Response
    {
        $analyticsCharts = [
            'monthlyVisitors' => [
                'labels' => ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun'],
                'values' => [12400, 13280, 14560, 15240, 17080, 18540],
            ],
            'eventGrowth' => [
                'labels' => ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun'],
                'values' => [52, 61, 74, 88, 103, 126],
            ],
            'tourismOccupancy' => [
                'labels' => ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
                'values' => [62, 64, 66, 70, 81, 88, 79],
            ],
            'seasonality' => [
                'labels' => ['Alta', 'Média', 'Baixa'],
                'values' => [48, 34, 18],
            ],
            'districtComparison' => [
                'labels' => ['Sítio Histórico', 'Carmo', 'Varadouro', 'Alto da Sé', 'Recife Antigo'],
                'values' => [96, 74, 62, 88, 81],
            ],
        ];

        $analyticsCharts['monthlyVisitors']['max'] = self::getMaxValue($analyticsCharts['monthlyVisitors']['values']);
        $analyticsCharts['monthlyVisitors']['points'] = self::buildChartPoints(
            $analyticsCharts['monthlyVisitors']['values'],
            $analyticsCharts['monthlyVisitors']['max'],
            40,
            76,
            185,
            125,
        );

        $analyticsCharts['eventGrowth']['max'] = self::getMaxValue($analyticsCharts['eventGrowth']['values']);
        $analyticsCharts['tourismOccupancy']['max'] = self::getMaxValue($analyticsCharts['tourismOccupancy']['values']);
        $analyticsCharts['tourismOccupancy']['points'] = self::buildChartPoints(
            $analyticsCharts['tourismOccupancy']['values'],
            $analyticsCharts['tourismOccupancy']['max'],
            35,
            58,
            185,
            125,
        );
        $analyticsCharts['districtComparison']['max'] = self::getMaxValue($analyticsCharts['districtComparison']['values']);

        return $this->render('platform/indicators.html.twig', [
            'hero' => [
                'badge' => 'Business Intelligence',
                'title' => 'Indicadores Estratégicos',
                'subtitle' => 'Camada analítica dedicada à inteligência territorial, turismo inteligente e apoio à tomada de decisão do ecossistema Olinda360.',
                'availability' => '98,7%',
                'availabilityDescription' => 'Infraestrutura operacional de dados estratégicos em funcionamento.',
            ],
            'executiveIndicators' => [
                ['title' => 'Total de visitantes estimados', 'value' => '18.540/mês', 'variation' => '+12,4%', 'trend' => 'up', 'icon' => 'people-fill', 'description' => 'Movimento turístico consolidado no ciclo mensal com tração cultural.', 'tone' => 'teal', 'sparkBars' => [52, 61, 68, 73, 86]],
                ['title' => 'Taxa de ocupação hoteleira', 'value' => '78%', 'variation' => '+6,1%', 'trend' => 'up', 'icon' => 'building-check', 'description' => 'Capacidade receptiva aquecida em zonas de maior permanência.', 'tone' => 'blue', 'sparkBars' => [46, 54, 58, 67, 78]],
                ['title' => 'Eventos ativos no período', 'value' => '126', 'variation' => '+18,0%', 'trend' => 'up', 'icon' => 'calendar2-event-fill', 'description' => 'Agenda urbana densa sustentando fluxo contínuo de visitantes.', 'tone' => 'amber', 'sparkBars' => [33, 48, 59, 77, 92]],
                ['title' => 'Fluxo turístico diário', 'value' => '3.280', 'variation' => '+9,7%', 'trend' => 'up', 'icon' => 'signpost-split-fill', 'description' => 'Média diária de circulação em zonas turísticas e eixos culturais.', 'tone' => 'cyan', 'sparkBars' => [40, 51, 63, 70, 84]],
                ['title' => 'Crescimento do turismo', 'value' => '14,2%', 'variation' => '+2,9 p.p.', 'trend' => 'up', 'icon' => 'graph-up-arrow', 'description' => 'Indicador sintético de expansão do ecossistema turístico local.', 'tone' => 'emerald', 'sparkBars' => [38, 44, 53, 62, 80]],
                ['title' => 'Ticket médio estimado', 'value' => 'R$ 184', 'variation' => '+4,8%', 'trend' => 'up', 'icon' => 'cash-stack', 'description' => 'Potencial econômico médio por visitante nas jornadas monitoradas.', 'tone' => 'slate', 'sparkBars' => [48, 56, 62, 70, 74]],
                ['title' => 'Índice de atividade cultural', 'value' => '91/100', 'variation' => '+7,3%', 'trend' => 'up', 'icon' => 'music-note-beamed', 'description' => 'Vitalidade cultural observada em agenda, ocupação e circulação.', 'tone' => 'purple', 'sparkBars' => [44, 52, 63, 76, 91]],
                ['title' => 'Regiões mais visitadas', 'value' => 'Sítio Histórico', 'variation' => 'Liderança contínua', 'trend' => 'steady', 'icon' => 'geo-alt-fill', 'description' => 'Área com maior densidade de visitação, permanência e oferta cultural.', 'tone' => 'rose', 'sparkBars' => [70, 74, 79, 84, 89]],
            ],
            'territorialZones' => [
                ['name' => 'Alto da Sé', 'flow' => '4.820', 'events' => 18, 'economicActivity' => 'Alta', 'occupancy' => '82%', 'intensity' => 92, 'top' => '18%', 'left' => '30%'],
                ['name' => 'Recife Antigo', 'flow' => '3.940', 'events' => 22, 'economicActivity' => 'Alta', 'occupancy' => '76%', 'intensity' => 86, 'top' => '54%', 'left' => '68%'],
                ['name' => 'Sítio Histórico', 'flow' => '5.260', 'events' => 31, 'economicActivity' => 'Muito alta', 'occupancy' => '88%', 'intensity' => 98, 'top' => '34%', 'left' => '48%'],
                ['name' => 'Carmo', 'flow' => '2.780', 'events' => 14, 'economicActivity' => 'Moderada', 'occupancy' => '71%', 'intensity' => 72, 'top' => '64%', 'left' => '38%'],
                ['name' => 'Varadouro', 'flow' => '2.140', 'events' => 9, 'economicActivity' => 'Em expansão', 'occupancy' => '65%', 'intensity' => 58, 'top' => '72%', 'left' => '56%'],
            ],
            'operationalIndicators' => [
                ['source' => 'Cadastur', 'updatedAt' => 'Hoje, 02:10', 'status' => 'Online', 'statusTone' => 'success', 'processed' => '6.420', 'coverage' => 'Rede hoteleira e serviços', 'quality' => '96%'],
                ['source' => 'FNRH', 'updatedAt' => 'Hoje, 03:00', 'status' => 'Em sincronização', 'statusTone' => 'primary', 'processed' => '4.180', 'coverage' => 'Hospedagem formal', 'quality' => '89%'],
                ['source' => 'OpenStreetMap', 'updatedAt' => 'Hoje, 01:25', 'status' => 'Online', 'statusTone' => 'success', 'processed' => '8.960', 'coverage' => 'Território e POIs', 'quality' => '93%'],
                ['source' => 'IBGE', 'updatedAt' => 'Hoje, 04:15', 'status' => 'Online', 'statusTone' => 'success', 'processed' => '2.310', 'coverage' => 'Macroindicadores urbanos', 'quality' => '98%'],
                ['source' => 'Dados Recife', 'updatedAt' => 'Ontem, 22:40', 'status' => 'Alerta', 'statusTone' => 'warning', 'processed' => '1.480', 'coverage' => 'Mobilidade e apoio regional', 'quality' => '78%'],
                ['source' => 'Cadastro Manual', 'updatedAt' => 'Hoje, 08:20', 'status' => 'Desatualizado', 'statusTone' => 'secondary', 'processed' => '950', 'coverage' => 'Curadoria institucional', 'quality' => '84%'],
            ],
            'governanceCards' => [
                ['title' => 'APIs públicas ativas', 'value' => '8', 'detail' => 'Interfaces disponíveis para dados abertos e interoperabilidade.', 'icon' => 'globe2', 'tone' => 'teal'],
                ['title' => 'Rotinas batch executadas', 'value' => '6', 'detail' => 'Pipelines críticos operando com monitoramento contínuo.', 'icon' => 'arrow-repeat', 'tone' => 'blue'],
                ['title' => 'Integridade dos dados', 'value' => '94%', 'detail' => 'Consistência estrutural consolidada na camada analítica.', 'icon' => 'shield-check', 'tone' => 'amber'],
                ['title' => 'Cobertura geográfica', 'value' => '87%', 'detail' => 'Distribuição territorial mapeada nas principais zonas turísticas.', 'icon' => 'map', 'tone' => 'cyan'],
                ['title' => 'Qualidade cadastral', 'value' => '91%', 'detail' => 'Nível de completude cadastral das bases estratégicas.', 'icon' => 'patch-check', 'tone' => 'emerald'],
                ['title' => 'Dados georreferenciados', 'value' => '1.280', 'detail' => 'Registros já posicionados para leitura espacial.', 'icon' => 'geo-alt', 'tone' => 'slate'],
                ['title' => 'Índice de atualização', 'value' => '96h', 'detail' => 'Janela média recente de atualização analítica monitorada.', 'icon' => 'clock-history', 'tone' => 'purple'],
                ['title' => 'Disponibilidade da plataforma', 'value' => '98,7%', 'detail' => 'SLA operacional sustentando análise e decisões públicas.', 'icon' => 'cloud-check', 'tone' => 'rose'],
            ],
            'strategicInsights' => [
                ['title' => 'Alta concentração de eventos detectada no Sítio Histórico.', 'description' => 'O eixo patrimonial consolidou a maior densidade de agenda cultural e maior permanência de visitantes neste ciclo.', 'badge' => 'Evento', 'badgeTone' => 'primary', 'icon' => 'stars'],
                ['title' => 'Taxa de ocupação elevada em períodos culturais.', 'description' => 'Picos de programação artística e festividades ampliaram a permanência média e a pressão sobre a capacidade receptiva.', 'badge' => 'Hospedagem', 'badgeTone' => 'success', 'icon' => 'moon-stars'],
                ['title' => 'Região do Carmo apresenta potencial para expansão turística.', 'description' => 'A zona combina fluxo intermediário com atividade econômica crescente, indicando oportunidade para indução programática.', 'badge' => 'Território', 'badgeTone' => 'warning', 'icon' => 'geo'],
                ['title' => 'Dados de hospedagem apresentam crescimento de 18%.', 'description' => 'A expansão do cadastro e da ocupação sugere aquecimento contínuo do ecossistema turístico receptivo.', 'badge' => 'Crescimento', 'badgeTone' => 'info', 'icon' => 'bar-chart-line'],
            ],
            'analyticalLayers' => [
                ['title' => 'Dados Públicos', 'description' => 'Bases abertas, estatísticas oficiais e sinais territoriais primários.', 'icon' => 'database'],
                ['title' => 'Integrações', 'description' => 'Conectores com serviços externos, cadastros e fontes institucionais.', 'icon' => 'plug'],
                ['title' => 'Processamento Batch', 'description' => 'Normalização, enriquecimento, limpeza e sincronização contínua.', 'icon' => 'gear-wide-connected'],
                ['title' => 'Banco Analítico', 'description' => 'Camada consolidada para exploração executiva e inteligência territorial.', 'icon' => 'server'],
                ['title' => 'Indicadores', 'description' => 'KPIs estratégicos, leituras comparativas e sinais de governança.', 'icon' => 'speedometer2'],
                ['title' => 'Tomada de Decisão', 'description' => 'Apoio direto à gestão pública, turismo inteligente e interoperabilidade.', 'icon' => 'clipboard2-data'],
            ],
            'strategicActions' => [
                ['label' => 'Exportar Indicadores', 'path' => 'export_indicators', 'variant' => 'primary', 'icon' => 'download'],
                ['label' => 'Abrir Dashboard', 'path' => 'dashboard', 'variant' => 'outline-primary', 'icon' => 'grid-1x2'],
                ['label' => 'Ver API Pública', 'path' => 'app_public_api_v1_docs', 'variant' => 'outline-success', 'icon' => 'globe2'],
                ['label' => 'Monitoramento Batch', 'path' => 'app_batch_monitor', 'variant' => 'outline-secondary', 'icon' => 'activity'],
                ['label' => 'Abrir MCP / IA', 'path' => 'app_mcp_v1_docs', 'variant' => 'outline-dark', 'icon' => 'cpu'],
                ['label' => 'Relatório Executivo', 'path' => 'app_platform_indicators', 'variant' => 'outline-warning', 'icon' => 'file-earmark-text'],
                ['label' => 'Painel Territorial', 'path' => 'app_platform_indicators', 'variant' => 'outline-info', 'icon' => 'map'],
            ],
            'analyticsCharts' => $analyticsCharts,
        ]);
    }

    /**
     * Calculates the highest value in a numeric chart series.
     */
    private static function getMaxValue(array $values): int
    {
        return (int) max($values);
    }

    /**
     * Builds SVG point coordinates for simplified line and area charts.
     * Security: receives only server-side numeric series, avoiding client-side script generation.
     */
    private static function buildChartPoints(
        array $values,
        int $maxValue,
        int $startX,
        int $stepX,
        int $baselineY,
        int $height
    ): array {
        $points = [];

        foreach ($values as $index => $value) {
            $x = $startX + ($index * $stepX);
            $y = $baselineY - (($value / $maxValue) * $height);
            $points[] = sprintf('%d,%s', $x, rtrim(rtrim(sprintf('%.2F', $y), '0'), '.'));
        }

        return $points;
    }

    /**
     * Provides the mock executive analytics data used by the analytics command center.
     */
    private function buildAnalyticsDashboardContext(): array
    {
        return [
            'hero' => [
                'badge' => 'Analytics Intelligence',
                'title' => 'Analytics Territorial e Turistico',
                'subtitle' => 'Central avancada de analise territorial, inteligencia operacional e apoio estrategico para decisoes publicas e turismo inteligente.',
                'accuracy' => '97,9%',
                'accuracyDescription' => 'Precisao analitica dos dados processados.',
            ],
            'comparativePanels' => [
                ['title' => 'Fluxo turistico mensal', 'description' => 'Evolucao semestral do volume de visitantes acompanhados.', 'chartId' => 'analyticsTourismFlowChart', 'chartType' => 'Line', 'status' => 'Crescimento consistente', 'statusTone' => 'success', 'insight' => 'O fluxo turistico apresenta tendencia consistente de crescimento no semestre.'],
                ['title' => 'Eventos por regiao', 'description' => 'Distribuicao territorial das ativacoes culturais e turisticas.', 'chartId' => 'analyticsEventsRegionChart', 'chartType' => 'Bars', 'status' => 'Concentracao territorial', 'statusTone' => 'primary', 'insight' => 'Alto da Se e Sitio Historico concentram maior atividade cultural e economica.'],
                ['title' => 'Perfil de motivacao dos visitantes', 'description' => 'Composicao da demanda por experiencia, cultura e deslocamentos.', 'chartId' => 'analyticsVisitorMotivationChart', 'chartType' => 'Donut', 'status' => 'Predominio cultural', 'statusTone' => 'info', 'insight' => 'A motivacao cultural lidera a demanda e reforca a vocacao patrimonial do destino.'],
                ['title' => 'Ocupacao hoteleira por periodo', 'description' => 'Capacidade receptiva acompanhando picos de demanda e eventos.', 'chartId' => 'analyticsHotelOccupancyChart', 'chartType' => 'Area', 'status' => 'Pressao de alta', 'statusTone' => 'success', 'insight' => 'A ocupacao hoteleira acompanha o crescimento dos eventos.'],
                ['title' => 'Regioes com maior atividade economica', 'description' => 'Comparativo entre polos com maior inducao de receita e circulacao.', 'chartId' => 'analyticsEconomicActivityChart', 'chartType' => 'Horizontal Bars', 'status' => 'Eixos lideres definidos', 'statusTone' => 'warning', 'insight' => 'Alto da Se e Sitio Historico lideram a dinamica economica do territorio turistico.'],
                ['title' => 'Maturidade turistica por dimensao', 'description' => 'Leitura comparativa de governanca, dados, mobilidade, cultura e economia.', 'chartId' => 'analyticsMaturityRadarChart', 'chartType' => 'Radar', 'status' => 'Maturidade desigual', 'statusTone' => 'secondary', 'insight' => 'Governanca e dados apresentam boa maturidade, mas mobilidade ainda exige atencao.'],
            ],
            'chartPayloads' => [
                'tourismFlow' => [
                    'labels' => ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun'],
                    'values' => [8200, 9400, 11000, 13800, 16400, 18540],
                ],
                'eventsByRegion' => [
                    'labels' => ['Alto da Se', 'Carmo', 'Varadouro', 'Sitio Historico', 'Bairro Novo'],
                    'values' => [42, 28, 21, 35, 16],
                ],
                'visitorMotivation' => [
                    'labels' => ['Cultural', 'Religioso', 'Gastronomia', 'Eventos', 'Negocios'],
                    'values' => [42, 18, 16, 15, 9],
                ],
                'hotelOccupancy' => [
                    'labels' => ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun'],
                    'values' => [58, 61, 64, 70, 74, 78],
                ],
                'economicActivity' => [
                    'labels' => ['Alto da Se', 'Sitio Historico', 'Carmo', 'Varadouro', 'Bairro Novo'],
                    'values' => [91, 88, 76, 63, 52],
                ],
                'tourismMaturity' => [
                    'labels' => ['Governanca', 'Dados', 'Mobilidade', 'Cultura', 'Hospedagem', 'Economia'],
                    'values' => [78, 82, 61, 91, 74, 69],
                ],
            ],
            'comparativeInsights' => [
                'O fluxo turistico apresenta tendencia consistente de crescimento no semestre.',
                'Alto da Se e Sitio Historico concentram maior atividade cultural e economica.',
                'A ocupacao hoteleira acompanha o crescimento dos eventos.',
                'Governanca e dados apresentam boa maturidade, mas mobilidade ainda exige atencao.',
            ],
            'territorialHotspots' => [
                ['name' => 'Alto da Se', 'flow' => '4.820', 'events' => 28, 'status' => 'Hotspot critico', 'intensity' => 96, 'top' => '18%', 'left' => '34%', 'description' => 'Maior concentracao de fluxo turistico nos finais de semana.'],
                ['name' => 'Carmo', 'flow' => '3.980', 'events' => 22, 'status' => 'Alta densidade', 'intensity' => 84, 'top' => '46%', 'left' => '44%', 'description' => 'Zona com permanencia ampliada e alta densidade de visitantes.'],
                ['name' => 'Varadouro', 'flow' => '2.640', 'events' => 16, 'status' => 'Expansao', 'intensity' => 68, 'top' => '66%', 'left' => '57%', 'description' => 'Area com crescimento de operacoes e inducoes economicas.'],
                ['name' => 'Sitio Historico', 'flow' => '5.120', 'events' => 39, 'status' => 'Nucleo estrategico', 'intensity' => 98, 'top' => '30%', 'left' => '58%', 'description' => 'Polo com maior pressao de eventos e experiencias historicas.'],
                ['name' => 'Bairro Novo', 'flow' => '1.860', 'events' => 11, 'status' => 'Observacao', 'intensity' => 52, 'top' => '76%', 'left' => '31%', 'description' => 'Territorio com potencial de novas rotas e conexoes.'],
            ],
            'executiveInsights' => [
                ['title' => 'Alto da Se apresenta maior fluxo turistico nos finais de semana.', 'description' => 'A concentracao de visitantes aumenta nos periodos de pico cultural e amplia a pressao territorial sobre o polo historico.', 'badge' => 'Fluxo', 'badgeTone' => 'primary', 'icon' => 'stars'],
                ['title' => 'Eventos culturais aumentaram 23% no ultimo periodo.', 'description' => 'A programacao artistica intensificou a permanencia media e o volume de deslocamentos entre polos culturais.', 'badge' => 'Eventos', 'badgeTone' => 'success', 'icon' => 'calendar2-week'],
                ['title' => 'Regiao do Carmo possui alta densidade de visitantes.', 'description' => 'O territorio combina boa distribuicao economica com forte atratividade historica e gastronomica.', 'badge' => 'Territorio', 'badgeTone' => 'warning', 'icon' => 'geo-alt-fill'],
                ['title' => 'Dados apontam crescimento no turismo gastronomico.', 'description' => 'Experiencias ligadas a culinaria local aumentaram o ticket medio e elevaram a permanencia em eixos especificos.', 'badge' => 'Economia', 'badgeTone' => 'info', 'icon' => 'cup-hot-fill'],
                ['title' => 'Taxa de permanencia aumentou durante eventos historicos.', 'description' => 'A ocupacao hoteleira e a permanencia diaria cresceram em ciclos com forte narrativa patrimonial.', 'badge' => 'Permanencia', 'badgeTone' => 'dark', 'icon' => 'clock-history'],
            ],
            'operationalIndicators' => [
                ['source' => 'Cadastur', 'updatedAt' => 'Hoje, 02:10', 'coverage' => 'Rede turistica formal', 'integrity' => '97%', 'quality' => '96%', 'processed' => '6.420', 'status' => 'Online', 'tone' => 'success'],
                ['source' => 'FNRH', 'updatedAt' => 'Hoje, 03:00', 'coverage' => 'Hospedagem e permanencia', 'integrity' => '92%', 'quality' => '89%', 'processed' => '4.180', 'status' => 'Sincronizando', 'tone' => 'primary'],
                ['source' => 'OpenStreetMap', 'updatedAt' => 'Hoje, 01:25', 'coverage' => 'Territorio e POIs', 'integrity' => '95%', 'quality' => '93%', 'processed' => '8.960', 'status' => 'Atualizado', 'tone' => 'success'],
                ['source' => 'IBGE', 'updatedAt' => 'Hoje, 04:15', 'coverage' => 'Macroindicadores urbanos', 'integrity' => '99%', 'quality' => '98%', 'processed' => '2.310', 'status' => 'Online', 'tone' => 'success'],
                ['source' => 'Dados Recife', 'updatedAt' => 'Ontem, 22:40', 'coverage' => 'Mobilidade regional', 'integrity' => '83%', 'quality' => '78%', 'processed' => '1.480', 'status' => 'Alerta', 'tone' => 'warning'],
                ['source' => 'APIs Municipais', 'updatedAt' => 'Hoje, 05:05', 'coverage' => 'Operacao territorial', 'integrity' => '94%', 'quality' => '91%', 'processed' => '3.740', 'status' => 'Online', 'tone' => 'success'],
            ],
            'analyticalLayers' => [
                ['title' => 'Coleta de Dados', 'description' => 'Captura de sinais territoriais, turisticos e operacionais.', 'icon' => 'database-fill-down'],
                ['title' => 'Integracoes / API', 'description' => 'Conectores com plataformas externas, APIs publicas e fontes institucionais.', 'icon' => 'plugin'],
                ['title' => 'Batch Processing', 'description' => 'Tratamento, enrichimento e sincronizacao automatica.', 'icon' => 'gear-wide-connected'],
                ['title' => 'Banco Analitico', 'description' => 'Persistencia estruturada para exploracao e leitura executiva.', 'icon' => 'server'],
                ['title' => 'Analytics', 'description' => 'Visualizacoes avancadas, comparativos e sinais preditivos.', 'icon' => 'bar-chart-line-fill'],
                ['title' => 'Tomada de Decisao', 'description' => 'Apoio direto a governanca publica e turismo inteligente.', 'icon' => 'clipboard2-data-fill'],
            ],
            'executiveWidgets' => [
                ['title' => 'APIs ativas', 'value' => '14', 'icon' => 'globe2', 'tone' => 'teal'],
                ['title' => 'Rotinas batch executadas', 'value' => '32', 'icon' => 'arrow-repeat', 'tone' => 'blue'],
                ['title' => 'Dados processados', 'value' => '84,2k', 'icon' => 'database-fill-check', 'tone' => 'amber'],
                ['title' => 'Registros georreferenciados', 'value' => '1.280', 'icon' => 'geo-alt-fill', 'tone' => 'cyan'],
                ['title' => 'Cobertura territorial', 'value' => '87%', 'icon' => 'map-fill', 'tone' => 'emerald'],
                ['title' => 'Disponibilidade operacional', 'value' => '99,1%', 'icon' => 'shield-check', 'tone' => 'purple'],
                ['title' => 'Fontes conectadas', 'value' => '14', 'icon' => 'diagram-3-fill', 'tone' => 'rose'],
            ],
            'predictiveCards' => [
                ['title' => 'Previsao de crescimento turistico', 'projection' => '+16,8%', 'horizon' => 'Proximos 90 dias', 'confidence' => 'Alta confianca', 'icon' => 'graph-up-arrow', 'tone' => 'teal', 'description' => 'Modelo aponta crescimento sustentado em periodos de agenda cultural ampliada.'],
                ['title' => 'Tendencia de ocupacao', 'projection' => '82%', 'horizon' => 'Alta temporada', 'confidence' => 'Confianca moderada', 'icon' => 'building-fill-up', 'tone' => 'blue', 'description' => 'A capacidade hoteleira deve operar proxima do limite em ciclos festivos.'],
                ['title' => 'Sazonalidade futura', 'projection' => 'Pico em julho', 'horizon' => '120 dias', 'confidence' => 'Alta confianca', 'icon' => 'calendar3', 'tone' => 'amber', 'description' => 'Sinais sugerem maior concentracao de demanda nos periodos historico-culturais.'],
                ['title' => 'Projecao de eventos', 'projection' => '148 eventos', 'horizon' => 'Proximo trimestre', 'confidence' => 'Confianca moderada', 'icon' => 'broadcast', 'tone' => 'purple', 'description' => 'Agenda cultural e institucional tende a aumentar a densidade de ativacoes.'],
                ['title' => 'Projecao economica', 'projection' => 'R$ 3,9 mi', 'horizon' => 'Ciclo trimestral', 'confidence' => 'Alta confianca', 'icon' => 'cash-coin', 'tone' => 'rose', 'description' => 'Receita estimada impulsionada por permanencia, gastronomia e turismo de experiencia.'],
            ],
            'strategicActions' => [
                ['label' => 'Exportar Analytics', 'route' => 'export_indicators', 'variant' => 'primary', 'icon' => 'download'],
                ['label' => 'Gerar Relatorio Executivo', 'route' => 'app_exports_index', 'variant' => 'outline-primary', 'icon' => 'file-earmark-text'],
                ['label' => 'Abrir Indicadores', 'route' => 'app_platform_indicators', 'variant' => 'outline-success', 'icon' => 'speedometer2'],
                ['label' => 'Ver Dashboard', 'route' => 'dashboard', 'variant' => 'outline-secondary', 'icon' => 'grid-1x2-fill'],
                ['label' => 'API Publica', 'route' => 'app_public_api_v1_docs', 'variant' => 'outline-info', 'icon' => 'globe-americas'],
                ['label' => 'Monitoramento Batch', 'route' => 'app_batch_monitor', 'variant' => 'outline-dark', 'icon' => 'activity'],
                ['label' => 'Abrir MCP / IA', 'route' => 'app_mcp_v1_docs', 'variant' => 'outline-warning', 'icon' => 'cpu'],
                ['label' => 'Relatorio PDF', 'route' => 'app_exports_index', 'variant' => 'outline-danger', 'icon' => 'filetype-pdf'],
            ],
        ];
    }

    /**
     * Renders roadmap pages for platform capabilities that are planned but not yet implemented.
     */
    #[Route('/observability', name: 'app_platform_observability', defaults: ['title' => 'Observabilidade', 'description' => 'Console de observabilidade para métricas, disponibilidade, tracing e sinais críticos do ecossistema.', 'badge' => 'Em breve', 'badgeTone' => 'warning', 'icon' => 'broadcast-pin', 'section' => 'Inteligência'])]
    #[Route('/logs', name: 'app_platform_logs', defaults: ['title' => 'Logs Operacionais', 'description' => 'Trilha operacional para auditoria, investigação e confiabilidade dos serviços do Olinda360.', 'badge' => 'Em breve', 'badgeTone' => 'warning', 'icon' => 'journal-text', 'section' => 'Inteligência'])]
    #[Route('/webhooks', name: 'app_platform_webhooks', defaults: ['title' => 'Webhooks', 'description' => 'Eventos de integração e gatilhos externos para orquestração futura com parceiros e automações.', 'badge' => 'Em breve', 'badgeTone' => 'warning', 'icon' => 'send-check', 'section' => 'Integrações'])]
    #[Route('/integrations', name: 'app_platform_integrations', defaults: ['title' => 'Integrações Externas', 'description' => 'Catálogo de conectores, APIs parceiras e integrações estratégicas do ecossistema governamental.', 'badge' => 'Em breve', 'badgeTone' => 'warning', 'icon' => 'plugin', 'section' => 'Integrações'])]
    #[Route('/architecture', name: 'app_platform_architecture', defaults: ['title' => 'Arquitetura', 'description' => 'Visão institucional das camadas, fluxos e capacidades que sustentam a plataforma.', 'badge' => 'Roadmap', 'badgeTone' => 'secondary', 'icon' => 'diagram-3', 'section' => 'Plataforma'])]
    #[Route('/infrastructure', name: 'app_platform_infrastructure', defaults: ['title' => 'Infraestrutura', 'description' => 'Mapa da infraestrutura de serviços, persistência e sustentação do console govtech.', 'badge' => 'Roadmap', 'badgeTone' => 'secondary', 'icon' => 'hdd-network', 'section' => 'Plataforma'])]
    #[Route('/settings', name: 'app_platform_settings', defaults: ['title' => 'Configurações', 'description' => 'Centro de parâmetros operacionais, políticas e ajustes institucionais futuros.', 'badge' => 'Roadmap', 'badgeTone' => 'secondary', 'icon' => 'sliders', 'section' => 'Plataforma'])]
    #[Route('/users', name: 'app_platform_users', defaults: ['title' => 'Usuários', 'description' => 'Gestão futura de perfis, permissões e responsabilidades administrativas da plataforma.', 'badge' => 'Roadmap', 'badgeTone' => 'secondary', 'icon' => 'people', 'section' => 'Plataforma'])]
    #[Route('/security', name: 'app_platform_security', defaults: ['title' => 'Segurança', 'description' => 'Módulo planejado para postura de segurança, controles institucionais e governança de acesso.', 'badge' => 'Roadmap', 'badgeTone' => 'secondary', 'icon' => 'shield-lock', 'section' => 'Plataforma'])]
    #[Route('/about', name: 'app_platform_about', defaults: ['title' => 'Sobre o Projeto', 'description' => 'Contexto institucional, missão e evolução do Olinda360 como plataforma de inteligência territorial.', 'badge' => 'Roadmap', 'badgeTone' => 'secondary', 'icon' => 'info-circle', 'section' => 'Plataforma'])]
    public function placeholder(string $title, string $description, string $badge, string $badgeTone, string $icon, string $section): Response
    {
        return $this->render('platform/placeholder.html.twig', [
            'title' => $title,
            'description' => $description,
            'badge' => $badge,
            'badgeTone' => $badgeTone,
            'icon' => $icon,
            'section' => $section,
        ]);
    }

    /**
     * Redirects the internal API documentation shortcut to the current API console.
     */
    #[Route('/api/docs', name: 'app_platform_api_docs', methods: ['GET'])]
    public function apiDocs(): Response
    {
        return $this->redirect('/api');
    }
}