<?php

namespace App\Controller\PublicApi\V1;

use App\Service\PublicApiResponseBuilder;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

// Generated by GitHub Copilot
abstract class AbstractPublicApiController extends AbstractController
{
    private const DEFAULT_LIMIT = 20;
    private const MAX_LIMIT = 100;

    /**
     * Builds a public collection response with filtering and pagination.
     *
     * @param class-string $entityClass
     * @param list<string> $searchFields
     * @param array<string, string> $filterMap
     * @param array<string, string> $orderBy
     * @param callable(object): array<string, mixed> $mapper
     */
    protected function collectionResponse(
        Request $request,
        EntityManagerInterface $entityManager,
        PublicApiResponseBuilder $responseBuilder,
        string $entityClass,
        array $searchFields,
        array $filterMap,
        array $orderBy,
        callable $mapper,
    ): Response {
        [$page, $limit] = $this->resolvePagination($request);
        $queryBuilder = $this->createFilteredQueryBuilder($request, $entityManager, $entityClass, $searchFields, $filterMap, $orderBy);

        $countQueryBuilder = clone $queryBuilder;
        $countQueryBuilder->select('COUNT(item.id)');
        $countQueryBuilder->resetDQLPart('orderBy');

        $total = (int) $countQueryBuilder->getQuery()->getSingleScalarResult();
        $items = $queryBuilder
            ->setFirstResult(($page - 1) * $limit)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();

        return $responseBuilder->collection(
            array_map(static fn (object $item): array => $mapper($item), $items),
            $page,
            $limit,
            $total,
        );
    }

    /**
     * Builds a single-item response while enforcing the public visibility rules.
     *
     * @param class-string $entityClass
     * @param callable(object): array<string, mixed> $mapper
     */
    protected function itemResponse(
        int $id,
        EntityManagerInterface $entityManager,
        PublicApiResponseBuilder $responseBuilder,
        string $entityClass,
        callable $mapper,
    ): Response {
        $queryBuilder = $entityManager->getRepository($entityClass)->createQueryBuilder('item');
        $metadata = $entityManager->getClassMetadata($entityClass);

        $queryBuilder
            ->andWhere('item.id = :id')
            ->setParameter('id', $id);

        if ($metadata->hasField('active')) {
            $queryBuilder
                ->andWhere('item.active = :active')
                ->setParameter('active', true);
        }

        $item = $queryBuilder->getQuery()->getOneOrNullResult();

        if (null === $item) {
            throw new NotFoundHttpException('Public resource not found.');
        }

        return $responseBuilder->item($mapper($item));
    }

    /**
     * Normalizes optional datetimes for public JSON responses.
     */
    protected function formatDateTime(?\DateTimeInterface $dateTime): ?string
    {
        return null === $dateTime ? null : $dateTime->format(\DateTimeInterface::ATOM);
    }

    /**
     * Normalizes optional dates for public JSON responses.
     */
    protected function formatDate(?\DateTimeInterface $dateTime): ?string
    {
        return null === $dateTime ? null : $dateTime->format('Y-m-d');
    }

    /**
     * Resolves page and limit with sane public API bounds.
     *
     * @return array{0: int, 1: int}
     */
    private function resolvePagination(Request $request): array
    {
        $page = max(1, $request->query->getInt('page', 1));
        $limit = min(self::MAX_LIMIT, max(1, $request->query->getInt('limit', self::DEFAULT_LIMIT)));

        return [$page, $limit];
    }

    /**
     * Creates the filtered query builder for public resource listings.
     *
     * @param class-string $entityClass
     * @param list<string> $searchFields
     * @param array<string, string> $filterMap
     * @param array<string, string> $orderBy
     */
    private function createFilteredQueryBuilder(
        Request $request,
        EntityManagerInterface $entityManager,
        string $entityClass,
        array $searchFields,
        array $filterMap,
        array $orderBy,
    ): QueryBuilder {
        $queryBuilder = $entityManager->getRepository($entityClass)->createQueryBuilder('item');
        $metadata = $entityManager->getClassMetadata($entityClass);

        if ($metadata->hasField('active')) {
            $queryBuilder
                ->andWhere('item.active = :active')
                ->setParameter('active', true);
        }

        foreach ($filterMap as $queryParameter => $field) {
            $value = trim((string) $request->query->get($queryParameter, ''));

            if ('' === $value || !$metadata->hasField($field)) {
                continue;
            }

            $queryBuilder
                ->andWhere(sprintf('item.%s = :%s', $field, $queryParameter))
                ->setParameter($queryParameter, $value);
        }

        $search = trim((string) $request->query->get('search', ''));
        if ('' !== $search) {
            $searchExpression = $queryBuilder->expr()->orX();

            foreach ($searchFields as $index => $field) {
                if (!$metadata->hasField($field)) {
                    continue;
                }

                $parameter = sprintf('search_%d', $index);
                $searchExpression->add(sprintf('LOWER(item.%s) LIKE :%s', $field, $parameter));
                $queryBuilder->setParameter($parameter, '%'.mb_strtolower($search).'%');
            }

            if ([] !== $searchExpression->getParts()) {
                $queryBuilder->andWhere($searchExpression);
            }
        }

        foreach ($orderBy as $field => $direction) {
            if ($metadata->hasField($field)) {
                $queryBuilder->addOrderBy(sprintf('item.%s', $field), $direction);
            }
        }

        return $queryBuilder;
    }
}