<?php

namespace App\Controller\PublicApi\V1;

use App\Entity\TouristGuide;
use App\Service\PublicApiResponseBuilder;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class PublicTouristGuideController extends AbstractPublicApiController
{
    /**
     * Lists active tourist guides in the public API.
     */
    #[Route('/public-api/v1/guides', name: 'app_public_api_v1_guide_index', methods: ['GET'])]
    public function index(Request $request, EntityManagerInterface $entityManager, PublicApiResponseBuilder $responseBuilder): Response
    {
        return $this->collectionResponse(
            $request,
            $entityManager,
            $responseBuilder,
            TouristGuide::class,
            ['name', 'serviceRegion'],
            [],
            ['name' => 'ASC'],
            fn (object $item): array => $this->normalizeGuide($item),
        );
    }

    /**
     * Shows one active tourist guide in the public API.
     */
    #[Route('/public-api/v1/guides/{id<\d+>}', name: 'app_public_api_v1_guide_show', methods: ['GET'])]
    public function show(int $id, EntityManagerInterface $entityManager, PublicApiResponseBuilder $responseBuilder): Response
    {
        return $this->itemResponse($id, $entityManager, $responseBuilder, TouristGuide::class, fn (object $item): array => $this->normalizeGuide($item));
    }

    /**
     * Maps a tourist guide entity to public-safe JSON.
     *
     * @return array<string, mixed>
     */
    private function normalizeGuide(object $item): array
    {
        /** @var TouristGuide $item */
        return [
            'id' => $item->id,
            'name' => $item->name,
            'languages' => $item->languages ?? [],
            'specialties' => $item->specialties ?? [],
            'instagram' => $item->instagram,
            'serviceRegion' => $item->serviceRegion,
        ];
    }
}