<?php

namespace App\Controller\PublicApi\V1;

use App\Entity\Indicator;
use App\Service\PublicApiResponseBuilder;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class PublicIndicatorController extends AbstractPublicApiController
{
    /**
     * Lists indicators in the public API.
     */
    #[Route('/public-api/v1/indicators', name: 'app_public_api_v1_indicator_index', methods: ['GET'])]
    public function index(Request $request, EntityManagerInterface $entityManager, PublicApiResponseBuilder $responseBuilder): Response
    {
        return $this->collectionResponse(
            $request,
            $entityManager,
            $responseBuilder,
            Indicator::class,
            ['title', 'description'],
            ['category' => 'category', 'source' => 'source'],
            ['referenceDate' => 'DESC', 'title' => 'ASC'],
            fn (object $item): array => $this->normalizeIndicator($item),
        );
    }

    /**
     * Shows one indicator in the public API.
     */
    #[Route('/public-api/v1/indicators/{id<\d+>}', name: 'app_public_api_v1_indicator_show', methods: ['GET'])]
    public function show(int $id, EntityManagerInterface $entityManager, PublicApiResponseBuilder $responseBuilder): Response
    {
        return $this->itemResponse($id, $entityManager, $responseBuilder, Indicator::class, fn (object $item): array => $this->normalizeIndicator($item));
    }

    /**
     * Maps an indicator entity to public-safe JSON.
     *
     * @return array<string, mixed>
     */
    private function normalizeIndicator(object $item): array
    {
        /** @var Indicator $item */
        return [
            'id' => $item->id,
            'title' => $item->title,
            'slug' => $item->slug,
            'category' => $item->category,
            'value' => $item->value,
            'unit' => $item->unit,
            'referenceDate' => $this->formatDate($item->referenceDate),
            'source' => $item->source,
            'description' => $item->description,
        ];
    }
}