<?php

namespace App\Controller\PublicApi\V1;

use App\Service\PublicApiSpecificationBuilder;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class PublicApiDocsController extends AbstractController
{
    /**
     * Renders a simple documentation page for the public read-only API.
     */
    #[Route('/public-api/v1/docs', name: 'app_public_api_v1_docs', methods: ['GET'])]
    public function __invoke(PublicApiSpecificationBuilder $specificationBuilder): Response
    {
        return $this->render('public_api/docs.html.twig', [
            'endpoints' => $specificationBuilder->getEndpoints(),
            'examples' => $specificationBuilder->getExamples(),
            'parameters' => $specificationBuilder->getParameters(),
        ]);
    }
}