<?php

namespace App\Controller\PublicApi\V1;

use App\Entity\TourismEvent;
use App\Service\PublicApiResponseBuilder;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class PublicTourismEventController extends AbstractPublicApiController
{
    /**
     * Lists tourism events in the public API.
     */
    #[Route('/public-api/v1/events', name: 'app_public_api_v1_event_index', methods: ['GET'])]
    public function index(Request $request, EntityManagerInterface $entityManager, PublicApiResponseBuilder $responseBuilder): Response
    {
        return $this->collectionResponse(
            $request,
            $entityManager,
            $responseBuilder,
            TourismEvent::class,
            ['title', 'description', 'location'],
            ['category' => 'category', 'district' => 'district', 'source' => 'source'],
            ['startDate' => 'ASC', 'title' => 'ASC'],
            fn (object $item): array => $this->normalizeTourismEvent($item),
        );
    }

    /**
     * Shows one tourism event in the public API.
     */
    #[Route('/public-api/v1/events/{id<\d+>}', name: 'app_public_api_v1_event_show', methods: ['GET'])]
    public function show(int $id, EntityManagerInterface $entityManager, PublicApiResponseBuilder $responseBuilder): Response
    {
        return $this->itemResponse($id, $entityManager, $responseBuilder, TourismEvent::class, fn (object $item): array => $this->normalizeTourismEvent($item));
    }

    /**
     * Maps a tourism event entity to public-safe JSON.
     *
     * @return array<string, mixed>
     */
    private function normalizeTourismEvent(object $item): array
    {
        /** @var TourismEvent $item */
        return [
            'id' => $item->id,
            'title' => $item->title,
            'slug' => $item->slug,
            'description' => $item->description,
            'category' => $item->category,
            'startDate' => $this->formatDateTime($item->startDate),
            'endDate' => $this->formatDateTime($item->endDate),
            'location' => $item->location,
            'district' => $item->district,
            'latitude' => $item->latitude,
            'longitude' => $item->longitude,
            'expectedAudience' => $item->expectedAudience,
            'isFree' => $item->isFree,
            'ticketUrl' => $item->ticketUrl,
            'website' => $item->website,
            'instagram' => $item->instagram,
            'source' => $item->source,
        ];
    }
}