<?php

namespace App\Controller\PublicApi\V1;

use App\Service\PublicApiSpecificationBuilder;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class PublicApiOpenApiController extends AbstractController
{
    /**
     * Publishes a simplified OpenAPI document dedicated to the public API.
     */
    #[Route('/public-api/v1/openapi.json', name: 'app_public_api_v1_openapi', methods: ['GET'])]
    public function __invoke(PublicApiSpecificationBuilder $specificationBuilder): JsonResponse
    {
        return new JsonResponse($specificationBuilder->buildOpenApiDocument());
    }
}