<?php

namespace App\Controller\PublicApi\V1;

use App\Entity\Accommodation;
use App\Service\PublicApiResponseBuilder;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class PublicAccommodationController extends AbstractPublicApiController
{
    /**
     * Lists active accommodations in the public API.
     */
    #[Route('/public-api/v1/accommodations', name: 'app_public_api_v1_accommodation_index', methods: ['GET'])]
    public function index(Request $request, EntityManagerInterface $entityManager, PublicApiResponseBuilder $responseBuilder): Response
    {
        return $this->collectionResponse(
            $request,
            $entityManager,
            $responseBuilder,
            Accommodation::class,
            ['name', 'description', 'address'],
            ['category' => 'category', 'district' => 'district'],
            ['name' => 'ASC'],
            fn (object $item): array => $this->normalizeAccommodation($item),
        );
    }

    /**
     * Shows one active accommodation in the public API.
     */
    #[Route('/public-api/v1/accommodations/{id<\d+>}', name: 'app_public_api_v1_accommodation_show', methods: ['GET'])]
    public function show(int $id, EntityManagerInterface $entityManager, PublicApiResponseBuilder $responseBuilder): Response
    {
        return $this->itemResponse($id, $entityManager, $responseBuilder, Accommodation::class, fn (object $item): array => $this->normalizeAccommodation($item));
    }

    /**
     * Maps an accommodation entity to public-safe JSON.
     *
     * @return array<string, mixed>
     */
    private function normalizeAccommodation(object $item): array
    {
        /** @var Accommodation $item */
        return [
            'id' => $item->id,
            'name' => $item->name,
            'slug' => $item->slug,
            'description' => $item->description,
            'category' => $item->category,
            'address' => $item->address,
            'district' => $item->district,
            'latitude' => $item->latitude,
            'longitude' => $item->longitude,
            'rooms' => $item->rooms,
            'beds' => $item->beds,
            'wifi' => $item->wifi,
            'parking' => $item->parking,
            'accessibility' => $item->accessibility,
            'website' => $item->website,
            'instagram' => $item->instagram,
        ];
    }
}