<?php

namespace App\Controller\PublicApi\V1;

use App\Entity\TouristSpot;
use App\Service\PublicApiResponseBuilder;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class PublicTouristSpotController extends AbstractPublicApiController
{
    /**
     * Lists active tourist spots in the public API.
     */
    #[Route('/public-api/v1/tourist-spots', name: 'app_public_api_v1_tourist_spot_index', methods: ['GET'])]
    public function index(Request $request, EntityManagerInterface $entityManager, PublicApiResponseBuilder $responseBuilder): Response
    {
        return $this->collectionResponse(
            $request,
            $entityManager,
            $responseBuilder,
            TouristSpot::class,
            ['name', 'description', 'history', 'address'],
            ['category' => 'category', 'district' => 'district', 'source' => 'source'],
            ['name' => 'ASC'],
            fn (object $item): array => $this->normalizeTouristSpot($item),
        );
    }

    /**
     * Shows one active tourist spot in the public API.
     */
    #[Route('/public-api/v1/tourist-spots/{id<\d+>}', name: 'app_public_api_v1_tourist_spot_show', methods: ['GET'])]
    public function show(int $id, EntityManagerInterface $entityManager, PublicApiResponseBuilder $responseBuilder): Response
    {
        return $this->itemResponse($id, $entityManager, $responseBuilder, TouristSpot::class, fn (object $item): array => $this->normalizeTouristSpot($item));
    }

    /**
     * Maps a tourist spot entity to public-safe JSON.
     *
     * @return array<string, mixed>
     */
    private function normalizeTouristSpot(object $item): array
    {
        /** @var TouristSpot $item */
        return [
            'id' => $item->id,
            'name' => $item->name,
            'slug' => $item->slug,
            'description' => $item->description,
            'history' => $item->history,
            'category' => $item->category,
            'address' => $item->address,
            'district' => $item->district,
            'latitude' => $item->latitude,
            'longitude' => $item->longitude,
            'openingHours' => $item->openingHours,
            'ticketPrice' => $item->ticketPrice,
            'accessibility' => $item->accessibility,
            'hasBathroom' => $item->hasBathroom,
            'hasParking' => $item->hasParking,
            'safetyLevel' => $item->safetyLevel,
            'source' => $item->source,
        ];
    }
}