<?php

namespace App\Controller\PublicApi\V1;

use App\Entity\DataSource;
use App\Service\PublicApiResponseBuilder;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class PublicDataSourceController extends AbstractPublicApiController
{
    /**
     * Lists active data sources in the public API.
     */
    #[Route('/public-api/v1/data-sources', name: 'app_public_api_v1_data_source_index', methods: ['GET'])]
    public function index(Request $request, EntityManagerInterface $entityManager, PublicApiResponseBuilder $responseBuilder): Response
    {
        return $this->collectionResponse(
            $request,
            $entityManager,
            $responseBuilder,
            DataSource::class,
            ['name', 'description', 'type'],
            [],
            ['name' => 'ASC'],
            fn (object $item): array => $this->normalizeDataSource($item),
        );
    }

    /**
     * Shows one active data source in the public API.
     */
    #[Route('/public-api/v1/data-sources/{id<\d+>}', name: 'app_public_api_v1_data_source_show', methods: ['GET'])]
    public function show(int $id, EntityManagerInterface $entityManager, PublicApiResponseBuilder $responseBuilder): Response
    {
        return $this->itemResponse($id, $entityManager, $responseBuilder, DataSource::class, fn (object $item): array => $this->normalizeDataSource($item));
    }

    /**
     * Maps a data source entity to public-safe JSON.
     *
     * @return array<string, mixed>
     */
    private function normalizeDataSource(object $item): array
    {
        /** @var DataSource $item */
        return [
            'id' => $item->id,
            'name' => $item->name,
            'slug' => $item->slug,
            'type' => $item->type,
            'url' => $item->url,
            'description' => $item->description,
            'updateFrequency' => $item->updateFrequency,
        ];
    }
}