<?php

namespace App\Controller\PublicApi\V1;

use App\Service\PublicApiResponseBuilder;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class PublicApiStatusController extends AbstractController
{
    /**
     * Exposes a simple health document for the public read-only API.
     */
    #[Route('/public-api/v1/status', name: 'app_public_api_v1_status', methods: ['GET'])]
    public function __invoke(PublicApiResponseBuilder $responseBuilder): Response
    {
        return $responseBuilder->status([
            'status' => 'online',
            'name' => 'Olinda360 Public API',
            'version' => 'v1',
            'description' => 'API publica de dados abertos turisticos de Olinda',
        ]);
    }
}