<?php

namespace App\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;

// Generated by GitHub Copilot
final class CommaSeparatedStringToArrayTransformer implements DataTransformerInterface
{
    /**
     * Transforms an array into a comma separated string for text inputs.
     */
    public function transform($value): string
    {
        if (!is_array($value) || [] === $value) {
            return '';
        }

        return implode(', ', $value);
    }

    /**
     * Transforms a comma separated string back into a normalized string array.
     *
     * @return list<string>
     */
    public function reverseTransform($value): array
    {
        if (!is_string($value) || '' === trim($value)) {
            return [];
        }

        $items = array_map('trim', explode(',', $value));
        $items = array_values(array_filter($items, static fn (string $item): bool => '' !== $item));

        return array_values(array_unique($items));
    }
}