<?php

namespace App\Controller\Admin;

use App\Entity\Data\RawFile;
use App\Entity\DataProvider;
use App\Entity\DatasetResource;
use App\Entity\IngestionRun;
use App\Entity\ProviderPackage;
use App\Entity\User;
use App\Form\DataProviderType;
use App\Repository\Data\RawFileRepository;
use App\Repository\DataProviderRepository;
use App\Repository\IngestionRunRepository;
use App\Repository\ProviderPackageRepository;
use App\Service\CkanProviderService;
use App\Service\DataPipeline\PipelineJobService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

// Generated by GitHub Copilot
#[Route('/admin/data-providers')]
#[IsGranted(User::ROLE_ADMIN)]
final class DataProviderController extends AbstractController
{
    #[Route('/overview', name: 'app_admin_ingestion_overview', methods: ['GET'])]
    public function overview(
        DataProviderRepository $providerRepository,
        ProviderPackageRepository $packageRepository,
        IngestionRunRepository $runRepository,
        RawFileRepository $rawFileRepository,
    ): Response {
        $recentRuns = $runRepository->findRecentRuns(10);

        $statusCounts = array_fill_keys(IngestionRun::getAvailableStatuses(), 0);
        foreach ($runRepository->findRecentRuns(100) as $run) {
            $statusCounts[$run->getStatus()] = ($statusCounts[$run->getStatus()] ?? 0) + 1;
        }

        return $this->render('admin/data_providers/overview.html.twig', [
            'summary' => [
                'totalProviders' => $providerRepository->count([]),
                'activeProviders' => $providerRepository->countActiveProviders(),
                'totalPackages' => $packageRepository->countAllPackages(),
                'monitoredPackages' => $packageRepository->countMonitored(),
                'totalRawFiles' => $rawFileRepository->count([]),
                'previewableFiles' => $rawFileRepository->countPreviewable(),
            ],
            'recentRuns' => $recentRuns,
            'statusCounts' => $statusCounts,
            'statusPresentation' => $this->getRunStatusPresentation(),
        ]);
    }

    #[Route('', name: 'app_admin_data_providers', methods: ['GET'])]
    public function index(
        DataProviderRepository $providerRepository,
        ProviderPackageRepository $packageRepository,
        IngestionRunRepository $runRepository,
    ): Response {
        $providers = $providerRepository->findOrderedForDashboard();

        return $this->render('admin/data_providers/index.html.twig', [
            'providers' => $providers,
            'summary' => [
                'totalProviders' => count($providers),
                'activeProviders' => $providerRepository->countActiveProviders(),
                'syncedPackages' => $packageRepository->countAllPackages(),
                'monitoredPackages' => $packageRepository->countMonitored(),
                'totalRuns' => count($runRepository->findRecentRuns(100)),
            ],
            'statusPresentation' => $this->getRunStatusPresentation(),
        ]);
    }

    #[Route('/new', name: 'app_admin_data_providers_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $provider = (new DataProvider())
            ->setType(DataProvider::TYPE_CKAN)
            ->setBaseUrl('https://dados.turismo.gov.br')
            ->setPackageListPath('/api/3/action/package_list')
            ->setPackageShowPath('/api/3/action/package_show?id={package_id}')
            ->setIsActive(true)
        ;

        $form = $this->createForm(DataProviderType::class, $provider);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($provider);
            $entityManager->flush();

            $this->addFlash('success', 'Provedor de dados salvo com sucesso.');

            return $this->redirectToRoute('app_admin_data_providers', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/data_providers/form.html.twig', [
            'provider' => $provider,
            'form' => $form,
            'isEdit' => false,
        ]);
    }

    #[Route('/{id<\d+>}/edit', name: 'app_admin_data_providers_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, DataProvider $provider, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DataProviderType::class, $provider);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            $this->addFlash('success', 'Provedor atualizado com sucesso.');

            return $this->redirectToRoute('app_admin_data_providers_edit', ['id' => $provider->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/data_providers/form.html.twig', [
            'provider' => $provider,
            'form' => $form,
            'isEdit' => true,
        ]);
    }

    #[Route('/packages', name: 'app_admin_provider_packages', methods: ['GET'])]
    public function packages(ProviderPackageRepository $packageRepository): Response
    {
        $packages = $packageRepository->findBy([], ['isMonitored' => 'DESC', 'updatedAt' => 'DESC', 'packageId' => 'ASC']);

        return $this->render('admin/data_providers/packages.html.twig', [
            'packages' => $packages,
            'provider' => null,
            'latestRawFiles' => $this->indexLatestRawFiles($packages),
        ]);
    }

    #[Route('/ingestion', name: 'app_admin_ingestion_runs', methods: ['GET'])]
    public function ingestion(IngestionRunRepository $runRepository, DataProviderRepository $providerRepository): Response
    {
        $runs = $runRepository->findRecentRuns(30);
        $providers = $providerRepository->findOrderedForDashboard();

        $statusCounts = array_fill_keys(IngestionRun::getAvailableStatuses(), 0);
        foreach ($runs as $run) {
            $statusCounts[$run->getStatus()] = ($statusCounts[$run->getStatus()] ?? 0) + 1;
        }

        return $this->render('admin/data_providers/ingestion.html.twig', [
            'runs' => $runs,
            'providers' => $providers,
            'statusPresentation' => $this->getRunStatusPresentation(),
            'summary' => [
                'totalRuns' => count($runs),
                'running' => $statusCounts[IngestionRun::STATUS_RUNNING] ?? 0,
                'success' => $statusCounts[IngestionRun::STATUS_SUCCESS] ?? 0,
                'failed' => $statusCounts[IngestionRun::STATUS_FAILED] ?? 0,
            ],
        ]);
    }

    #[Route('/history', name: 'app_admin_ingestion_history', methods: ['GET'])]
    public function history(IngestionRunRepository $runRepository): Response
    {
        return $this->render('admin/data_providers/history.html.twig', [
            'runs' => $runRepository->findRecentRuns(50),
            'statusPresentation' => $this->getRunStatusPresentation(),
        ]);
    }

    #[Route('/{id<\d+>}/sync', name: 'app_admin_data_providers_sync', methods: ['POST'])]
    public function syncPackages(DataProvider $provider, CkanProviderService $ckanProviderService): Response
    {
        try {
            $result = $ckanProviderService->syncPackageList($provider);
            $this->addFlash('success', $result['message']);
        } catch (\Throwable $exception) {
            $this->addFlash('danger', $exception->getMessage());
        }

        return $this->redirectToRoute('app_admin_data_providers', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id<\d+>}/packages', name: 'app_admin_data_providers_packages', methods: ['GET'])]
    public function providerPackages(DataProvider $provider, ProviderPackageRepository $packageRepository): Response
    {
        $packages = $packageRepository->findByProviderOrdered($provider);

        return $this->render('admin/data_providers/packages.html.twig', [
            'packages' => $packages,
            'provider' => $provider,
            'latestRawFiles' => $this->indexLatestRawFiles($packages),
        ]);
    }

    #[Route('/packages/{id<\d+>}', name: 'app_admin_provider_package_show', methods: ['GET'])]
    public function showPackage(ProviderPackage $package, CkanProviderService $ckanProviderService): Response
    {
        $metadata = $package->getRawMetadata();

        try {
            $result = $ckanProviderService->syncPackageResources($package);
            $metadata = $result['metadata'];
            $this->addFlash('success', $result['message']);
        } catch (\Throwable $exception) {
            $this->addFlash('warning', sprintf('Não foi possível atualizar os detalhes em tempo real. Exibindo os dados salvos. %s', $exception->getMessage()));
        }

        return $this->render('admin/data_providers/package_show.html.twig', [
            'package' => $package,
            'metadata' => $metadata,
            'resources' => $package->getResources(),
        ]);
    }

    #[Route('/packages/{id<\d+>}/download', name: 'app_admin_provider_package_download', methods: ['POST'])]
    public function downloadPackageResource(ProviderPackage $package, CkanProviderService $ckanProviderService, PipelineJobService $pipelineJobService): Response
    {
        try {
            $ckanProviderService->syncPackageResources($package);
            $resource = $this->resolvePrimaryResource($package);

            if (null === $resource) {
                throw new \RuntimeException('Nenhum resource elegível foi encontrado neste pacote.');
            }

            $result = $pipelineJobService->dispatchDownload($resource);
            $this->addFlash('success', $result['message']);
        } catch (\Throwable $exception) {
            $this->addFlash('danger', $exception->getMessage());
        }

        return $this->redirectToRoute('app_admin_provider_package_show', ['id' => $package->getId()], Response::HTTP_SEE_OTHER);
    }

    #[Route('/packages/{id<\d+>}/pipeline', name: 'app_admin_provider_package_pipeline', methods: ['POST'])]
    public function executePackagePipeline(ProviderPackage $package, CkanProviderService $ckanProviderService, PipelineJobService $pipelineJobService): Response
    {
        try {
            $ckanProviderService->syncPackageResources($package);
            $resource = $this->resolvePrimaryResource($package);

            if (null === $resource) {
                throw new \RuntimeException('Nenhum resource elegível foi encontrado neste pacote.');
            }

            $result = $pipelineJobService->executePipeline($resource);
            $this->addFlash('success', $result['message']);
        } catch (\Throwable $exception) {
            $this->addFlash('danger', $exception->getMessage());
        }

        return $this->redirectToRoute('app_admin_provider_package_show', ['id' => $package->getId()], Response::HTTP_SEE_OTHER);
    }

    #[Route('/resources/{id<\d+>}/download', name: 'app_admin_dataset_resource_download', methods: ['POST'])]
    public function downloadResource(DatasetResource $resource, PipelineJobService $pipelineJobService): Response
    {
        try {
            $result = $pipelineJobService->dispatchDownload($resource);
            $this->addFlash('success', $result['message']);
        } catch (\Throwable $exception) {
            $this->addFlash('danger', $exception->getMessage());
        }

        return $this->redirect($this->generateUrl('app_admin_provider_package_show', [
            'id' => $resource->getProviderPackage()->getId(),
        ]).'#resources', Response::HTTP_SEE_OTHER);
    }

    #[Route('/resources/{id<\d+>}/pipeline', name: 'app_admin_dataset_resource_pipeline', methods: ['POST'])]
    public function executeResourcePipeline(DatasetResource $resource, PipelineJobService $pipelineJobService): Response
    {
        try {
            $result = $pipelineJobService->executePipeline($resource);
            $this->addFlash('success', $result['message']);
        } catch (\Throwable $exception) {
            $this->addFlash('danger', $exception->getMessage());
        }

        return $this->redirect($this->generateUrl('app_admin_provider_package_show', [
            'id' => $resource->getProviderPackage()->getId(),
        ]).'#resources', Response::HTTP_SEE_OTHER);
    }

    #[Route('/packages/{id<\d+>}/monitor/on', name: 'app_admin_provider_package_monitor_on', methods: ['POST'])]
    public function enableMonitoring(ProviderPackage $package, EntityManagerInterface $entityManager): Response
    {
        $package->setIsMonitored(true);
        $entityManager->flush();

        $this->addFlash('success', sprintf('Monitoramento ativado para o pacote %s.', $package->getPackageId()));

        return $this->redirectToRoute('app_admin_data_providers_packages', ['id' => $package->getDataProvider()->getId()], Response::HTTP_SEE_OTHER);
    }

    #[Route('/packages/{id<\d+>}/monitor/off', name: 'app_admin_provider_package_monitor_off', methods: ['POST'])]
    public function disableMonitoring(ProviderPackage $package, EntityManagerInterface $entityManager): Response
    {
        $package->setIsMonitored(false);
        $entityManager->flush();

        $this->addFlash('success', sprintf('Monitoramento desativado para o pacote %s.', $package->getPackageId()));

        return $this->redirectToRoute('app_admin_data_providers_packages', ['id' => $package->getDataProvider()->getId()], Response::HTTP_SEE_OTHER);
    }

    /**
     * @return array<string, array{label: string, tone: string}>
     */
    private function getRunStatusPresentation(): array
    {
        return [
            IngestionRun::STATUS_PENDING => ['label' => 'Pendente', 'tone' => 'secondary'],
            IngestionRun::STATUS_RUNNING => ['label' => 'Executando', 'tone' => 'info'],
            IngestionRun::STATUS_SUCCESS => ['label' => 'Concluído', 'tone' => 'success'],
            IngestionRun::STATUS_WARNING => ['label' => 'Atenção', 'tone' => 'warning'],
            IngestionRun::STATUS_FAILED => ['label' => 'Falha', 'tone' => 'danger'],
        ];
    }

    /**
     * @param list<ProviderPackage> $packages
     *
     * @return array<int, RawFile>
     */
    private function indexLatestRawFiles(array $packages): array
    {
        $latestRawFiles = [];

        foreach ($packages as $package) {
            foreach ($package->getResources() as $resource) {
                $rawFile = $resource->getLatestRawFile();

                if (null !== $rawFile) {
                    $latestRawFiles[$package->getId()] = $rawFile;
                    break;
                }
            }
        }

        return $latestRawFiles;
    }

    private function resolvePrimaryResource(ProviderPackage $package): ?DatasetResource
    {
        $resources = $package->getResources()->toArray();
        usort($resources, static function (DatasetResource $left, DatasetResource $right): int {
            $priority = ['CSV' => 0, 'XLSX' => 1, 'JSON' => 2, 'ZIP' => 3];
            $leftPriority = $priority[$left->getFormat() ?? ''] ?? 99;
            $rightPriority = $priority[$right->getFormat() ?? ''] ?? 99;

            return [$leftPriority, $left->getName() ?? $left->getResourceId()] <=> [$rightPriority, $right->getName() ?? $right->getResourceId()];
        });

        foreach ($resources as $resource) {
            if ('' !== trim($resource->getUrl())) {
                return $resource;
            }
        }

        return null;
    }
}