<?php

namespace App\Controller\Admin;

use App\Admin\DataManagementRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class DataManagementController extends AbstractController
{
    /**
     * Renders the administrative data governance entrypoint.
     * Esta area devera receber autenticacao administrativa em etapa futura.
     */
    #[Route('/admin/data-management', name: 'app_admin_data_management', methods: ['GET'])]
    public function index(DataManagementRegistry $registry): Response
    {
        return $this->render('admin/data_management/index.html.twig', [
            'resources' => $registry->getDashboardCards(),
            'quickActions' => $registry->getQuickActions(),
        ]);
    }
}