<?php

namespace App\Controller\Admin;

use App\Admin\DataManagementRegistry;
use App\Pagination\Paginator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Generated by GitHub Copilot
final class DataCrudController extends AbstractController
{
    /**
     * Lists records with simple search, hygiene filters and pagination.
     * Esta area devera receber autenticacao administrativa em etapa futura.
     */
    #[Route('/admin/{resource}', name: 'app_admin_resource_index', requirements: ['resource' => DataManagementRegistry::ROUTE_REQUIREMENT], methods: ['GET'])]
    public function index(string $resource, Request $request, DataManagementRegistry $registry): Response
    {
        $metadata = $registry->get($resource);
        $search = trim((string) $request->query->get('q', ''));
        $status = (string) $request->query->get('status', '');
        $quality = (string) $request->query->get('quality', '');
        $page = max(1, $request->query->getInt('page', 1));

        $paginator = new Paginator($registry->createIndexQueryBuilder($metadata, $search, $status ?: null, $quality ?: null));
        $paginator->paginate($page);

        return $this->render('admin/data_management/resource_index.html.twig', [
            'resource' => $resource,
            'metadata' => $metadata,
            'registry' => $registry,
            'paginator' => $paginator,
            'search' => $search,
            'status' => $status,
            'quality' => $quality,
            'qualityCounts' => $registry->getQualityCounts($metadata),
            'qualityFilters' => $registry->getSupportedQualityFilters($metadata),
        ]);
    }

    /**
     * Creates a new manual record for the selected administrative resource.
     */
    #[Route('/admin/{resource}/new', name: 'app_admin_resource_new', requirements: ['resource' => DataManagementRegistry::ROUTE_REQUIREMENT], methods: ['GET', 'POST'])]
    public function new(string $resource, Request $request, EntityManagerInterface $entityManager, DataManagementRegistry $registry): Response
    {
        $metadata = $registry->get($resource);
        $entity = new ($metadata['class'])();
        $form = $this->createEntityForm($metadata, $entity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $registry->fillSlugIfMissing($entity, $metadata);

            $entityManager->persist($entity);
            $entityManager->flush();
            $this->addFlash('success', sprintf('%s criado com sucesso.', $metadata['singular']));

            return $this->redirectToRoute('app_admin_resource_show', [
                'resource' => $resource,
                'id' => $this->getEntityId($entity),
            ], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/data_management/resource_form.html.twig', [
            'resource' => $resource,
            'metadata' => $metadata,
            'registry' => $registry,
            'form' => $form,
            'entity' => $entity,
            'isEdit' => false,
        ]);
    }

    /**
     * Shows the details and hygiene state for a single record.
     */
    #[Route('/admin/{resource}/{id<\d+>}', name: 'app_admin_resource_show', requirements: ['resource' => DataManagementRegistry::ROUTE_REQUIREMENT], methods: ['GET'])]
    public function show(string $resource, int $id, DataManagementRegistry $registry, EntityManagerInterface $entityManager): Response
    {
        $metadata = $registry->get($resource);
        $entity = $this->findEntity($entityManager, $metadata['class'], $id);

        return $this->render('admin/data_management/resource_show.html.twig', [
            'resource' => $resource,
            'metadata' => $metadata,
            'registry' => $registry,
            'entity' => $entity,
            'detailRows' => $registry->getDetailRows($entity, $metadata),
        ]);
    }

    /**
     * Updates an existing manual record.
     */
    #[Route('/admin/{resource}/{id<\d+>}/edit', name: 'app_admin_resource_edit', requirements: ['resource' => DataManagementRegistry::ROUTE_REQUIREMENT], methods: ['GET', 'POST'])]
    public function edit(string $resource, int $id, Request $request, EntityManagerInterface $entityManager, DataManagementRegistry $registry): Response
    {
        $metadata = $registry->get($resource);
        $entity = $this->findEntity($entityManager, $metadata['class'], $id);
        $form = $this->createEntityForm($metadata, $entity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $registry->fillSlugIfMissing($entity, $metadata);
            $entityManager->flush();
            $this->addFlash('success', sprintf('%s atualizado com sucesso.', $metadata['singular']));

            return $this->redirectToRoute('app_admin_resource_edit', [
                'resource' => $resource,
                'id' => $id,
            ], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/data_management/resource_form.html.twig', [
            'resource' => $resource,
            'metadata' => $metadata,
            'registry' => $registry,
            'form' => $form,
            'entity' => $entity,
            'isEdit' => true,
        ]);
    }

    /**
     * Deletes a record after explicit confirmation and CSRF validation.
     */
    #[Route('/admin/{resource}/{id<\d+>}/delete', name: 'app_admin_resource_delete', requirements: ['resource' => DataManagementRegistry::ROUTE_REQUIREMENT], methods: ['POST'])]
    public function delete(string $resource, int $id, Request $request, EntityManagerInterface $entityManager, DataManagementRegistry $registry): Response
    {
        $metadata = $registry->get($resource);
        $entity = $this->findEntity($entityManager, $metadata['class'], $id);
        $token = (string) $request->request->get('_token', '');

        if (!$this->isCsrfTokenValid(sprintf('delete_%s_%d', $resource, $id), $token)) {
            $this->addFlash('warning', 'Não foi possível validar a exclusão do registro.');

            return $this->redirectToRoute('app_admin_resource_index', ['resource' => $resource], Response::HTTP_SEE_OTHER);
        }

        $entityManager->remove($entity);
        $entityManager->flush();
        $this->addFlash('success', sprintf('%s excluído com sucesso.', $metadata['singular']));

        return $this->redirectToRoute('app_admin_resource_index', ['resource' => $resource], Response::HTTP_SEE_OTHER);
    }

    /**
     * Creates the configured Symfony form for a managed entity.
     *
     * @param array<string, mixed> $metadata
     */
    private function createEntityForm(array $metadata, object $entity): FormInterface
    {
        return $this->createForm($metadata['form_type'], $entity);
    }

    /**
     * Loads an entity instance or raises a 404 when not found.
     */
    private function findEntity(EntityManagerInterface $entityManager, string $className, int $id): object
    {
        $entity = $entityManager->getRepository($className)->find($id);

        if (null === $entity) {
            throw $this->createNotFoundException('Registro administrativo não encontrado.');
        }

        return $entity;
    }

    /**
     * Reads the identifier from a managed entity after persistence.
     */
    private function getEntityId(object $entity): int
    {
        $id = null;

        if (method_exists($entity, 'getId')) {
            $id = $entity->getId();
        } elseif (property_exists($entity, 'id')) {
            $id = $entity->id;
        }

        if (!is_int($id)) {
            throw new \LogicException('The administrative entity did not expose an integer identifier after persistence.');
        }

        return $id;
    }
}