<?php

namespace App\Command\DataCollection;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Stopwatch\Stopwatch;

// Generated by GitHub Copilot
abstract class AbstractDataCollectionCommand extends Command
{
    /**
     * Simulates a future collection execution and documents the operational intent.
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $stopwatch = new Stopwatch();

        $io->title($this->getRoutineTitle());
        $io->writeln(sprintf('Fonte monitorada: <info>%s</info>', $this->getSourceName()));
        $io->note('Coleta simulada. A integracao real sera implementada depois e devera atualizar a entidade BatchRoutine.');

        $stopwatch->start('data-collection');
        usleep($this->getSimulatedDelayInMicroseconds());
        $event = $stopwatch->stop('data-collection');

        $io->success(sprintf('Execucao simulada concluida em %.2f ms.', $event->getDuration()));
        $io->comment(sprintf('Proximo passo: conectar %s ao provedor real e persistir telemetria operacional.', $this->getRoutineTitle()));

        return Command::SUCCESS;
    }

    /**
     * Returns the routine title shown in console feedback.
     */
    abstract protected function getRoutineTitle(): string;

    /**
     * Returns the monitored source name.
     */
    abstract protected function getSourceName(): string;

    /**
     * Defines the simulated command delay without busy looping.
     */
    protected function getSimulatedDelayInMicroseconds(): int
    {
        return 250000;
    }
}