<?php

namespace App\Command\DataCollection;

use Symfony\Component\Console\Attribute\AsCommand;

// Generated by GitHub Copilot
#[AsCommand(
    name: 'olinda360:collect:ibge',
    description: 'Simula a coleta batch do IBGE',
)]
final class CollectIbgeDataCommand extends AbstractDataCollectionCommand
{
    /**
     * Returns the routine title shown in console feedback.
     */
    protected function getRoutineTitle(): string
    {
        return 'Coleta IBGE';
    }

    /**
     * Returns the monitored source name.
     */
    protected function getSourceName(): string
    {
        return 'IBGE Cidades';
    }
}