<?php

namespace App\Command\DataCollection;

use Symfony\Component\Console\Attribute\AsCommand;

// Generated by GitHub Copilot
#[AsCommand(
    name: 'olinda360:collect:cadastur',
    description: 'Simula a coleta batch da base Cadastur',
)]
final class CollectCadasturDataCommand extends AbstractDataCollectionCommand
{
    /**
     * Returns the routine title shown in console feedback.
     */
    protected function getRoutineTitle(): string
    {
        return 'Coleta Cadastur';
    }

    /**
     * Returns the monitored source name.
     */
    protected function getSourceName(): string
    {
        return 'Ministerio do Turismo / Cadastur';
    }
}