<?php

namespace App\Command\DataCollection;

use Symfony\Component\Console\Attribute\AsCommand;

// Generated by GitHub Copilot
#[AsCommand(
    name: 'olinda360:collect:recife-open-data',
    description: 'Simula a coleta batch do portal Recife Open Data',
)]
final class CollectRecifeOpenDataCommand extends AbstractDataCollectionCommand
{
    /**
     * Returns the routine title shown in console feedback.
     */
    protected function getRoutineTitle(): string
    {
        return 'Coleta Dados Abertos Recife';
    }

    /**
     * Returns the monitored source name.
     */
    protected function getSourceName(): string
    {
        return 'Portal de Dados Abertos Recife';
    }
}