<?php

namespace App\Command\DataCollection;

use Symfony\Component\Console\Attribute\AsCommand;

// Generated by GitHub Copilot
#[AsCommand(
    name: 'olinda360:collect:osm',
    description: 'Simula a coleta batch do OpenStreetMap',
)]
final class CollectOpenStreetMapDataCommand extends AbstractDataCollectionCommand
{
    /**
     * Returns the routine title shown in console feedback.
     */
    protected function getRoutineTitle(): string
    {
        return 'Coleta OpenStreetMap';
    }

    /**
     * Returns the monitored source name.
     */
    protected function getSourceName(): string
    {
        return 'OpenStreetMap / Overpass API';
    }

    /**
     * Defines the simulated command delay without busy looping.
     */
    protected function getSimulatedDelayInMicroseconds(): int
    {
        return 320000;
    }
}