<?php

namespace App\Command\DataCollection;

use Symfony\Component\Console\Attribute\AsCommand;

// Generated by GitHub Copilot
#[AsCommand(
    name: 'olinda360:collect:fnrh',
    description: 'Simula a coleta batch da FNRH',
)]
final class CollectFnrhDataCommand extends AbstractDataCollectionCommand
{
    /**
     * Returns the routine title shown in console feedback.
     */
    protected function getRoutineTitle(): string
    {
        return 'Coleta FNRH';
    }

    /**
     * Returns the monitored source name.
     */
    protected function getSourceName(): string
    {
        return 'Ficha Nacional de Registro de Hospedes';
    }
}