<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\BooleanFilter;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

// Generated by GitHub Copilot
#[ORM\Entity]
#[ORM\HasLifecycleCallbacks]
#[ApiResource]
#[ApiFilter(SearchFilter::class, properties: ['name' => 'partial', 'category' => 'exact'])]
#[ApiFilter(BooleanFilter::class, properties: ['active', 'wifi', 'parking', 'accessibility'])]
#[ApiFilter(OrderFilter::class, properties: ['createdAt' => 'DESC', 'name' => 'ASC'])]
class Accommodation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    public ?int $id = null;

    #[ORM\Column(length: 255)]
    public string $name;

    #[ORM\Column(length: 191, unique: true)]
    public string $slug;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    public ?string $description = null;

    #[ORM\Column(length: 100)]
    public string $category;

    #[ORM\Column(length: 100, nullable: true)]
    public ?string $cadasturCode = null;

    #[ORM\Column(length: 255)]
    public string $address;

    #[ORM\Column(length: 100, nullable: true)]
    public ?string $district = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 8, nullable: true)]
    public ?string $latitude = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 11, scale: 8, nullable: true)]
    public ?string $longitude = null;

    #[ORM\Column(nullable: true)]
    public ?int $rooms = null;

    #[ORM\Column(nullable: true)]
    public ?int $beds = null;

    #[ORM\Column(options: ['default' => false])]
    public bool $wifi = false;

    #[ORM\Column(options: ['default' => false])]
    public bool $parking = false;

    #[ORM\Column(options: ['default' => false])]
    public bool $accessibility = false;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $website = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $instagram = null;

    #[ORM\Column(length: 50, nullable: true)]
    public ?string $phone = null;

    #[ORM\Column(length: 180, nullable: true)]
    public ?string $email = null;

    #[ORM\Column(options: ['default' => true])]
    public bool $active = true;

    #[ORM\ManyToOne(inversedBy: 'accommodations')]
    #[ORM\JoinColumn(nullable: true)]
    public ?Organization $organization = null;

    #[ORM\Column]
    public \DateTimeImmutable $createdAt;

    #[ORM\Column(nullable: true)]
    public ?\DateTimeImmutable $updatedAt = null;

    /**
     * Initializes creation timestamp.
     */
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    /**
     * Updates the last change timestamp before updating rows.
     */
    #[ORM\PreUpdate]
    public function touch(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }
}
