<?php

namespace App\Entity;

use App\Repository\BatchRoutineRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

// Generated by GitHub Copilot
#[ORM\Entity(repositoryClass: BatchRoutineRepository::class)]
#[ORM\HasLifecycleCallbacks]
class BatchRoutine
{
    public const STATUS_SUCCESS = 'success';
    public const STATUS_RUNNING = 'running';
    public const STATUS_WARNING = 'warning';
    public const STATUS_FAILED = 'failed';
    public const STATUS_PENDING = 'pending';
    public const STATUS_DISABLED = 'disabled';

    /**
     * Lists every allowed monitoring status.
     *
     * @return list<string>
     */
    public static function getAvailableStatuses(): array
    {
        return [
            self::STATUS_SUCCESS,
            self::STATUS_RUNNING,
            self::STATUS_WARNING,
            self::STATUS_FAILED,
            self::STATUS_PENDING,
            self::STATUS_DISABLED,
        ];
    }

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private string $name;

    #[ORM\Column(length: 191, unique: true)]
    #[Assert\NotBlank]
    private string $slug;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private string $sourceName;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank]
    private string $sourceType;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $apiUrl = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $cronExpression = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $scheduledTime = null;

    #[ORM\Column(length: 50, options: ['default' => self::STATUS_PENDING])]
    #[Assert\Choice(callback: [self::class, 'getAvailableStatuses'])]
    private string $status = self::STATUS_PENDING;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $lastExecutionAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $nextExecutionAt = null;

    #[ORM\Column(options: ['default' => 0])]
    private int $recordsProcessed = 0;

    #[ORM\Column(options: ['default' => 0])]
    private int $recordsCreated = 0;

    #[ORM\Column(options: ['default' => 0])]
    private int $recordsUpdated = 0;

    #[ORM\Column(options: ['default' => 0])]
    private int $recordsFailed = 0;

    #[ORM\Column(nullable: true)]
    private ?float $executionTimeSeconds = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $lastMessage = null;

    #[ORM\Column(options: ['default' => true])]
    private bool $active = true;

    #[ORM\Column]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    /**
     * Initializes timestamps and default monitoring state.
     */
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    /**
     * Keeps the update timestamp in sync before persistence updates.
     */
    #[ORM\PreUpdate]
    public function touch(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    /**
     * Returns the database identifier.
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Returns the routine display name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Updates the routine display name.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Returns the URL slug.
     */
    public function getSlug(): string
    {
        return $this->slug;
    }

    /**
     * Updates the URL slug.
     */
    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Returns the external source label.
     */
    public function getSourceName(): string
    {
        return $this->sourceName;
    }

    /**
     * Updates the external source label.
     */
    public function setSourceName(string $sourceName): self
    {
        $this->sourceName = $sourceName;

        return $this;
    }

    /**
     * Returns the source classification.
     */
    public function getSourceType(): string
    {
        return $this->sourceType;
    }

    /**
     * Updates the source classification.
     */
    public function setSourceType(string $sourceType): self
    {
        $this->sourceType = $sourceType;

        return $this;
    }

    /**
     * Returns the functional description.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Updates the functional description.
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Returns the upstream endpoint URL.
     */
    public function getApiUrl(): ?string
    {
        return $this->apiUrl;
    }

    /**
     * Updates the upstream endpoint URL.
     */
    public function setApiUrl(?string $apiUrl): self
    {
        $this->apiUrl = $apiUrl;

        return $this;
    }

    /**
     * Returns the cron schedule expression.
     */
    public function getCronExpression(): ?string
    {
        return $this->cronExpression;
    }

    /**
     * Updates the cron schedule expression.
     */
    public function setCronExpression(?string $cronExpression): self
    {
        $this->cronExpression = $cronExpression;

        return $this;
    }

    /**
     * Returns the human-readable scheduled time.
     */
    public function getScheduledTime(): ?string
    {
        return $this->scheduledTime;
    }

    /**
     * Updates the human-readable scheduled time.
     */
    public function setScheduledTime(?string $scheduledTime): self
    {
        $this->scheduledTime = $scheduledTime;

        return $this;
    }

    /**
     * Returns the current monitoring status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Updates the current monitoring status.
     */
    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Returns the last execution timestamp.
     */
    public function getLastExecutionAt(): ?\DateTime
    {
        return $this->lastExecutionAt;
    }

    /**
     * Updates the last execution timestamp.
     */
    public function setLastExecutionAt(?\DateTime $lastExecutionAt): self
    {
        $this->lastExecutionAt = $lastExecutionAt;

        return $this;
    }

    /**
     * Returns the next scheduled execution timestamp.
     */
    public function getNextExecutionAt(): ?\DateTime
    {
        return $this->nextExecutionAt;
    }

    /**
     * Updates the next scheduled execution timestamp.
     */
    public function setNextExecutionAt(?\DateTime $nextExecutionAt): self
    {
        $this->nextExecutionAt = $nextExecutionAt;

        return $this;
    }

    /**
     * Returns the total processed record count.
     */
    public function getRecordsProcessed(): int
    {
        return $this->recordsProcessed;
    }

    /**
     * Updates the total processed record count.
     */
    public function setRecordsProcessed(int $recordsProcessed): self
    {
        $this->recordsProcessed = $recordsProcessed;

        return $this;
    }

    /**
     * Returns the created record count.
     */
    public function getRecordsCreated(): int
    {
        return $this->recordsCreated;
    }

    /**
     * Updates the created record count.
     */
    public function setRecordsCreated(int $recordsCreated): self
    {
        $this->recordsCreated = $recordsCreated;

        return $this;
    }

    /**
     * Returns the updated record count.
     */
    public function getRecordsUpdated(): int
    {
        return $this->recordsUpdated;
    }

    /**
     * Updates the updated record count.
     */
    public function setRecordsUpdated(int $recordsUpdated): self
    {
        $this->recordsUpdated = $recordsUpdated;

        return $this;
    }

    /**
     * Returns the failed record count.
     */
    public function getRecordsFailed(): int
    {
        return $this->recordsFailed;
    }

    /**
     * Updates the failed record count.
     */
    public function setRecordsFailed(int $recordsFailed): self
    {
        $this->recordsFailed = $recordsFailed;

        return $this;
    }

    /**
     * Returns the last execution duration in seconds.
     */
    public function getExecutionTimeSeconds(): ?float
    {
        return $this->executionTimeSeconds;
    }

    /**
     * Updates the last execution duration in seconds.
     */
    public function setExecutionTimeSeconds(?float $executionTimeSeconds): self
    {
        $this->executionTimeSeconds = $executionTimeSeconds;

        return $this;
    }

    /**
     * Returns the latest execution message.
     */
    public function getLastMessage(): ?string
    {
        return $this->lastMessage;
    }

    /**
     * Updates the latest execution message.
     */
    public function setLastMessage(?string $lastMessage): self
    {
        $this->lastMessage = $lastMessage;

        return $this;
    }

    /**
     * Indicates whether the routine is enabled.
     */
    public function isActive(): bool
    {
        return $this->active;
    }

    /**
     * Updates the routine enabled flag.
     */
    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    /**
     * Returns the creation timestamp.
     */
    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    /**
     * Returns the last update timestamp.
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }
}