<?php

namespace App\Entity;

use App\Entity\Data\RawFile;
use App\Repository\DatasetResourceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

// Generated by GitHub Copilot
#[ORM\Entity(repositoryClass: DatasetResourceRepository::class)]
#[ORM\Table(name: 'dataset_resources')]
#[ORM\UniqueConstraint(name: 'uniq_provider_resource', columns: ['provider_package_id', 'resource_id'])]
#[ORM\HasLifecycleCallbacks]
class DatasetResource
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'resources')]
    #[ORM\JoinColumn(name: 'provider_package_id', nullable: false, onDelete: 'CASCADE')]
    private ProviderPackage $providerPackage;

    #[ORM\Column(name: 'resource_id', length: 191)]
    private string $resourceId;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $format = null;

    #[ORM\Column(length: 2048)]
    private string $url;

    #[ORM\Column(nullable: true)]
    private ?int $size = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $hash = null;

    #[ORM\Column(name: 'created_at_source', nullable: true)]
    private ?\DateTimeImmutable $createdAtSource = null;

    #[ORM\Column(name: 'last_modified_source', nullable: true)]
    private ?\DateTimeImmutable $lastModifiedSource = null;

    #[ORM\Column(name: 'raw_metadata', type: Types::JSON)]
    private array $rawMetadata = [];

    #[ORM\Column(name: 'created_at')]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'updated_at', nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    /**
     * @var Collection<int, RawFile>
     */
    #[ORM\OneToMany(mappedBy: 'datasetResource', targetEntity: RawFile::class, orphanRemoval: true, cascade: ['persist'])]
    #[ORM\OrderBy(['downloadedAt' => 'DESC', 'id' => 'DESC'])]
    private Collection $rawFiles;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->rawFiles = new ArrayCollection();
    }

    #[ORM\PreUpdate]
    public function touch(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProviderPackage(): ProviderPackage
    {
        return $this->providerPackage;
    }

    public function setProviderPackage(ProviderPackage $providerPackage): self
    {
        $this->providerPackage = $providerPackage;

        return $this;
    }

    public function getResourceId(): string
    {
        return $this->resourceId;
    }

    public function setResourceId(string $resourceId): self
    {
        $this->resourceId = trim($resourceId);

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = null === $name ? null : trim($name);

        return $this;
    }

    public function getFormat(): ?string
    {
        return $this->format;
    }

    public function setFormat(?string $format): self
    {
        $this->format = null === $format ? null : strtoupper(trim($format));

        return $this;
    }

    public function getUrl(): string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = trim($url);

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(?int $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(?string $hash): self
    {
        $this->hash = null === $hash ? null : trim($hash);

        return $this;
    }

    public function getCreatedAtSource(): ?\DateTimeImmutable
    {
        return $this->createdAtSource;
    }

    public function setCreatedAtSource(?\DateTimeImmutable $createdAtSource): self
    {
        $this->createdAtSource = $createdAtSource;

        return $this;
    }

    public function getLastModifiedSource(): ?\DateTimeImmutable
    {
        return $this->lastModifiedSource;
    }

    public function setLastModifiedSource(?\DateTimeImmutable $lastModifiedSource): self
    {
        $this->lastModifiedSource = $lastModifiedSource;

        return $this;
    }

    /**
     * @return array<string, mixed>
     */
    public function getRawMetadata(): array
    {
        return $this->rawMetadata;
    }

    /**
     * @param array<string, mixed> $rawMetadata
     */
    public function setRawMetadata(array $rawMetadata): self
    {
        $this->rawMetadata = $rawMetadata;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    /**
     * @return Collection<int, RawFile>
     */
    public function getRawFiles(): Collection
    {
        return $this->rawFiles;
    }

    public function addRawFile(RawFile $rawFile): self
    {
        if (!$this->rawFiles->contains($rawFile)) {
            $this->rawFiles->add($rawFile);
            $rawFile->setDatasetResource($this);
        }

        return $this;
    }

    public function getLatestRawFile(): ?RawFile
    {
        $rawFile = $this->rawFiles->first();

        return false === $rawFile ? null : $rawFile;
    }
}