<?php

namespace App\Entity;

use App\Repository\DataProviderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

// Generated by GitHub Copilot
#[ORM\Entity(repositoryClass: DataProviderRepository::class)]
#[ORM\Table(name: 'data_providers')]
#[ORM\HasLifecycleCallbacks]
class DataProvider
{
    public const TYPE_CKAN = 'CKAN';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private string $name;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank]
    private string $type = self::TYPE_CKAN;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Url]
    private string $baseUrl;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private string $packageListPath = '/api/3/action/package_list';

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private string $packageShowPath = '/api/3/action/package_show?id={package_id}';

    #[ORM\Column(name: 'is_active', options: ['default' => true])]
    private bool $isActive = true;

    #[ORM\Column(name: 'last_synced_at', nullable: true)]
    private ?\DateTimeImmutable $lastSyncedAt = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notes = null;

    #[ORM\Column(name: 'created_at')]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'updated_at', nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    /**
     * @var Collection<int, ProviderPackage>
     */
    #[ORM\OneToMany(mappedBy: 'dataProvider', targetEntity: ProviderPackage::class, orphanRemoval: true, cascade: ['persist'])]
    #[ORM\OrderBy(['updatedAt' => 'DESC', 'packageId' => 'ASC'])]
    private Collection $packages;

    /**
     * @var Collection<int, IngestionRun>
     */
    #[ORM\OneToMany(mappedBy: 'dataProvider', targetEntity: IngestionRun::class, orphanRemoval: true)]
    #[ORM\OrderBy(['createdAt' => 'DESC'])]
    private Collection $ingestionRuns;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->packages = new ArrayCollection();
        $this->ingestionRuns = new ArrayCollection();
    }

    #[ORM\PreUpdate]
    public function touch(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = trim($name);

        return $this;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = strtoupper(trim($type));

        return $this;
    }

    public function getBaseUrl(): string
    {
        return $this->baseUrl;
    }

    public function setBaseUrl(string $baseUrl): self
    {
        $this->baseUrl = rtrim(trim($baseUrl), '/');

        return $this;
    }

    public function getPackageListPath(): string
    {
        return $this->packageListPath;
    }

    public function setPackageListPath(string $packageListPath): self
    {
        $this->packageListPath = $this->normalizePath($packageListPath);

        return $this;
    }

    public function getPackageShowPath(): string
    {
        return $this->packageShowPath;
    }

    public function setPackageShowPath(string $packageShowPath): self
    {
        $this->packageShowPath = $this->normalizePath($packageShowPath);

        return $this;
    }

    public function isActive(): bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getLastSyncedAt(): ?\DateTimeImmutable
    {
        return $this->lastSyncedAt;
    }

    public function setLastSyncedAt(?\DateTimeImmutable $lastSyncedAt): self
    {
        $this->lastSyncedAt = $lastSyncedAt;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = null === $notes ? null : trim($notes);

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    /**
     * @return Collection<int, ProviderPackage>
     */
    public function getPackages(): Collection
    {
        return $this->packages;
    }

    public function addPackage(ProviderPackage $package): self
    {
        if (!$this->packages->contains($package)) {
            $this->packages->add($package);
            $package->setDataProvider($this);
        }

        return $this;
    }

    public function removePackage(ProviderPackage $package): self
    {
        $this->packages->removeElement($package);

        return $this;
    }

    /**
     * @return Collection<int, IngestionRun>
     */
    public function getIngestionRuns(): Collection
    {
        return $this->ingestionRuns;
    }

    public function getPackageListUrl(): string
    {
        return $this->baseUrl.$this->packageListPath;
    }

    public function getPackageShowUrl(string $packageId): string
    {
        return $this->baseUrl.str_replace('{package_id}', rawurlencode($packageId), $this->packageShowPath);
    }

    private function normalizePath(string $path): string
    {
        $normalized = trim($path);

        if ('' === $normalized) {
            return '/';
        }

        return str_starts_with($normalized, '/') ? $normalized : '/'.$normalized;
    }
}