<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\BooleanFilter;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

// Generated by GitHub Copilot
#[ORM\Entity]
#[ApiResource]
#[ApiFilter(SearchFilter::class, properties: ['name' => 'partial', 'type' => 'exact'])]
#[ApiFilter(BooleanFilter::class, properties: ['active'])]
#[ApiFilter(OrderFilter::class, properties: ['createdAt' => 'DESC', 'name' => 'ASC'])]
class DataSource
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    public ?int $id = null;

    #[ORM\Column(length: 255)]
    public string $name;

    #[ORM\Column(length: 191, unique: true)]
    public string $slug;

    #[ORM\Column(length: 100)]
    public string $type;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $url = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    public ?string $description = null;

    #[ORM\Column(length: 100, nullable: true)]
    public ?string $updateFrequency = null;

    #[ORM\Column(options: ['default' => true])]
    public bool $active = true;

    #[ORM\Column]
    public \DateTimeImmutable $createdAt;

    /**
     * Initializes creation timestamp.
     */
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }
}
