<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

// Generated by GitHub Copilot
#[ORM\Entity]
#[ApiResource]
#[ApiFilter(SearchFilter::class, properties: ['title' => 'partial', 'category' => 'exact'])]
#[ApiFilter(OrderFilter::class, properties: ['referenceDate' => 'DESC', 'createdAt' => 'DESC'])]
class Indicator
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    public ?int $id = null;

    #[ORM\Column(length: 255)]
    public string $title;

    #[ORM\Column(length: 191, unique: true)]
    public string $slug;

    #[ORM\Column(length: 100)]
    public string $category;

    #[ORM\Column]
    public float $value;

    #[ORM\Column(length: 50, nullable: true)]
    public ?string $unit = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    public \DateTime $referenceDate;

    #[ORM\Column(length: 255)]
    public string $source;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    public ?string $description = null;

    #[ORM\Column]
    public \DateTimeImmutable $createdAt;

    /**
     * Initializes creation timestamp.
     */
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }
}
