<?php

namespace App\Entity;

use App\Repository\IngestionRunRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

// Generated by GitHub Copilot
#[ORM\Entity(repositoryClass: IngestionRunRepository::class)]
#[ORM\Table(name: 'ingestion_runs')]
#[ORM\HasLifecycleCallbacks]
class IngestionRun
{
    public const STATUS_PENDING = 'pending';
    public const STATUS_RUNNING = 'running';
    public const STATUS_SUCCESS = 'success';
    public const STATUS_WARNING = 'warning';
    public const STATUS_FAILED = 'failed';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'ingestionRuns')]
    #[ORM\JoinColumn(name: 'data_provider_id', nullable: false, onDelete: 'CASCADE')]
    private DataProvider $dataProvider;

    #[ORM\ManyToOne(inversedBy: 'ingestionRuns')]
    #[ORM\JoinColumn(name: 'provider_package_id', nullable: true, onDelete: 'CASCADE')]
    private ?ProviderPackage $providerPackage = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'dataset_resource_id', nullable: true, onDelete: 'CASCADE')]
    private ?DatasetResource $datasetResource = null;

    #[ORM\Column(length: 50)]
    private string $status = self::STATUS_PENDING;

    #[ORM\Column(name: 'started_at', nullable: true)]
    private ?\DateTimeImmutable $startedAt = null;

    #[ORM\Column(name: 'finished_at', nullable: true)]
    private ?\DateTimeImmutable $finishedAt = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $message = null;

    #[ORM\Column(type: Types::JSON)]
    private array $logs = [];

    #[ORM\Column(name: 'created_at')]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'updated_at', nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    #[ORM\PreUpdate]
    public function touch(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    /**
     * @return list<string>
     */
    public static function getAvailableStatuses(): array
    {
        return [
            self::STATUS_PENDING,
            self::STATUS_RUNNING,
            self::STATUS_SUCCESS,
            self::STATUS_WARNING,
            self::STATUS_FAILED,
        ];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDataProvider(): DataProvider
    {
        return $this->dataProvider;
    }

    public function setDataProvider(DataProvider $dataProvider): self
    {
        $this->dataProvider = $dataProvider;

        return $this;
    }

    public function getProviderPackage(): ?ProviderPackage
    {
        return $this->providerPackage;
    }

    public function setProviderPackage(?ProviderPackage $providerPackage): self
    {
        $this->providerPackage = $providerPackage;

        return $this;
    }

    public function getDatasetResource(): ?DatasetResource
    {
        return $this->datasetResource;
    }

    public function setDatasetResource(?DatasetResource $datasetResource): self
    {
        $this->datasetResource = $datasetResource;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeImmutable
    {
        return $this->startedAt;
    }

    public function setStartedAt(?\DateTimeImmutable $startedAt): self
    {
        $this->startedAt = $startedAt;

        return $this;
    }

    public function getFinishedAt(): ?\DateTimeImmutable
    {
        return $this->finishedAt;
    }

    public function setFinishedAt(?\DateTimeImmutable $finishedAt): self
    {
        $this->finishedAt = $finishedAt;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(?string $message): self
    {
        $this->message = null === $message ? null : trim($message);

        return $this;
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function getLogs(): array
    {
        return $this->logs;
    }

    /**
     * @param array<int, array<string, mixed>> $logs
     */
    public function setLogs(array $logs): self
    {
        $this->logs = $logs;

        return $this;
    }

    /**
     * @param array<string, mixed> $entry
     */
    public function addLog(array $entry): self
    {
        $this->logs[] = $entry;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }
}