<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\BooleanFilter;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

// Generated by GitHub Copilot
#[ORM\Entity]
#[ORM\HasLifecycleCallbacks]
#[ApiResource]
#[ApiFilter(SearchFilter::class, properties: ['name' => 'partial', 'type' => 'exact', 'city' => 'exact', 'state' => 'exact'])]
#[ApiFilter(BooleanFilter::class, properties: ['active'])]
#[ApiFilter(OrderFilter::class, properties: ['createdAt' => 'DESC', 'name' => 'ASC'])]
class Organization
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    public ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    public string $name;

    #[ORM\Column(length: 191, unique: true)]
    #[Assert\NotBlank]
    public string $slug;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    public ?string $description = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank]
    public string $type;

    #[ORM\Column(length: 30, nullable: true)]
    public ?string $documentNumber = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $website = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $instagram = null;

    #[ORM\Column(length: 50, nullable: true)]
    public ?string $phone = null;

    #[ORM\Column(length: 180, nullable: true)]
    public ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $address = null;

    #[ORM\Column(length: 100, nullable: true)]
    public ?string $district = null;

    #[ORM\Column(length: 100, options: ['default' => 'Olinda'])]
    public string $city = 'Olinda';

    #[ORM\Column(length: 2, options: ['default' => 'PE'])]
    public string $state = 'PE';

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 8, nullable: true)]
    public ?string $latitude = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 11, scale: 8, nullable: true)]
    public ?string $longitude = null;

    #[ORM\Column(options: ['default' => true])]
    public bool $active = true;

    #[ORM\Column]
    public \DateTimeImmutable $createdAt;

    #[ORM\Column(nullable: true)]
    public ?\DateTimeImmutable $updatedAt = null;

    /**
     * @var Collection<int, TouristSpot>
     */
    #[ORM\OneToMany(mappedBy: 'organization', targetEntity: TouristSpot::class)]
    public Collection $touristSpots;

    /**
     * @var Collection<int, TourismEvent>
     */
    #[ORM\OneToMany(mappedBy: 'organization', targetEntity: TourismEvent::class)]
    public Collection $tourismEvents;

    /**
     * @var Collection<int, Accommodation>
     */
    #[ORM\OneToMany(mappedBy: 'organization', targetEntity: Accommodation::class)]
    public Collection $accommodations;

    /**
     * @var Collection<int, TouristGuide>
     */
    #[ORM\OneToMany(mappedBy: 'organization', targetEntity: TouristGuide::class)]
    public Collection $touristGuides;

    /**
     * Initializes defaults and relationship collections.
     */
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->touristSpots = new ArrayCollection();
        $this->tourismEvents = new ArrayCollection();
        $this->accommodations = new ArrayCollection();
        $this->touristGuides = new ArrayCollection();
    }

    /**
     * Updates the last change timestamp before updating rows.
     */
    #[ORM\PreUpdate]
    public function touch(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }
}
