<?php

namespace App\Entity;

use App\Repository\ProviderPackageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

// Generated by GitHub Copilot
#[ORM\Entity(repositoryClass: ProviderPackageRepository::class)]
#[ORM\Table(name: 'provider_packages')]
#[ORM\UniqueConstraint(name: 'uniq_provider_package', columns: ['data_provider_id', 'package_id'])]
#[ORM\HasLifecycleCallbacks]
class ProviderPackage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'packages')]
    #[ORM\JoinColumn(name: 'data_provider_id', nullable: false, onDelete: 'CASCADE')]
    private DataProvider $dataProvider;

    #[ORM\Column(name: 'package_id', length: 191)]
    #[Assert\NotBlank]
    private string $packageId;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(name: 'is_monitored', options: ['default' => false])]
    private bool $isMonitored = false;

    #[ORM\Column(name: 'is_active', options: ['default' => true])]
    private bool $isActive = true;

    #[ORM\Column(name: 'last_checked_at', nullable: true)]
    private ?\DateTimeImmutable $lastCheckedAt = null;

    #[ORM\Column(name: 'raw_metadata', type: Types::JSON)]
    private array $rawMetadata = [];

    #[ORM\Column(name: 'created_at')]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'updated_at', nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    /**
     * @var Collection<int, DatasetResource>
     */
    #[ORM\OneToMany(mappedBy: 'providerPackage', targetEntity: DatasetResource::class, orphanRemoval: true, cascade: ['persist'])]
    #[ORM\OrderBy(['updatedAt' => 'DESC', 'name' => 'ASC'])]
    private Collection $resources;

    /**
     * @var Collection<int, IngestionRun>
     */
    #[ORM\OneToMany(mappedBy: 'providerPackage', targetEntity: IngestionRun::class, orphanRemoval: true)]
    private Collection $ingestionRuns;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->resources = new ArrayCollection();
        $this->ingestionRuns = new ArrayCollection();
    }

    #[ORM\PreUpdate]
    public function touch(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDataProvider(): DataProvider
    {
        return $this->dataProvider;
    }

    public function setDataProvider(DataProvider $dataProvider): self
    {
        $this->dataProvider = $dataProvider;

        return $this;
    }

    public function getPackageId(): string
    {
        return $this->packageId;
    }

    public function setPackageId(string $packageId): self
    {
        $this->packageId = trim($packageId);

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = null === $title ? null : trim($title);

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = null === $description ? null : trim($description);

        return $this;
    }

    public function isMonitored(): bool
    {
        return $this->isMonitored;
    }

    public function setIsMonitored(bool $isMonitored): self
    {
        $this->isMonitored = $isMonitored;

        return $this;
    }

    public function isActive(): bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getLastCheckedAt(): ?\DateTimeImmutable
    {
        return $this->lastCheckedAt;
    }

    public function setLastCheckedAt(?\DateTimeImmutable $lastCheckedAt): self
    {
        $this->lastCheckedAt = $lastCheckedAt;

        return $this;
    }

    /**
     * @return array<string, mixed>
     */
    public function getRawMetadata(): array
    {
        return $this->rawMetadata;
    }

    /**
     * @param array<string, mixed> $rawMetadata
     */
    public function setRawMetadata(array $rawMetadata): self
    {
        $this->rawMetadata = $rawMetadata;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    /**
     * @return Collection<int, DatasetResource>
     */
    public function getResources(): Collection
    {
        return $this->resources;
    }

    public function addResource(DatasetResource $resource): self
    {
        if (!$this->resources->contains($resource)) {
            $this->resources->add($resource);
            $resource->setProviderPackage($this);
        }

        return $this;
    }

    public function getDisplayTitle(): string
    {
        return $this->title ?: $this->packageId;
    }
}