<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\BooleanFilter;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

// Generated by GitHub Copilot
#[ORM\Entity]
#[ORM\HasLifecycleCallbacks]
#[ApiResource]
#[ApiFilter(SearchFilter::class, properties: ['title' => 'partial', 'category' => 'exact'])]
#[ApiFilter(BooleanFilter::class, properties: ['isFree'])]
#[ApiFilter(OrderFilter::class, properties: ['startDate' => 'ASC', 'createdAt' => 'DESC'])]
class TourismEvent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    public ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    public string $title;

    #[ORM\Column(length: 191, unique: true)]
    #[Assert\NotBlank]
    public string $slug;

    #[ORM\Column(type: Types::TEXT)]
    public string $description;

    #[ORM\Column(length: 100)]
    public string $category;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    public \DateTime $startDate;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    public ?\DateTime $endDate = null;

    #[ORM\Column(length: 255)]
    public string $location;

    #[ORM\Column(length: 100, nullable: true)]
    public ?string $district = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 8, nullable: true)]
    public ?string $latitude = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 11, scale: 8, nullable: true)]
    public ?string $longitude = null;

    #[ORM\Column(nullable: true)]
    public ?int $expectedAudience = null;

    #[ORM\Column(options: ['default' => true])]
    public bool $isFree = true;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $ticketUrl = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $website = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $instagram = null;

    #[ORM\Column(length: 100, nullable: true)]
    public ?string $source = null;

    #[ORM\ManyToOne(inversedBy: 'tourismEvents')]
    #[ORM\JoinColumn(nullable: true)]
    public ?Organization $organization = null;

    #[ORM\Column]
    public \DateTimeImmutable $createdAt;

    #[ORM\Column(nullable: true)]
    public ?\DateTimeImmutable $updatedAt = null;

    /**
     * Initializes creation timestamp.
     */
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    /**
     * Updates the last change timestamp before updating rows.
     */
    #[ORM\PreUpdate]
    public function touch(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }
}
