<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\BooleanFilter;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

// Generated by GitHub Copilot
#[ORM\Entity]
#[ORM\HasLifecycleCallbacks]
#[ApiResource]
#[ApiFilter(SearchFilter::class, properties: ['name' => 'partial', 'category' => 'exact'])]
#[ApiFilter(BooleanFilter::class, properties: ['active', 'accessibility', 'hasBathroom', 'hasParking'])]
#[ApiFilter(OrderFilter::class, properties: ['createdAt' => 'DESC', 'name' => 'ASC'])]
class TouristSpot
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    public ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    public string $name;

    #[ORM\Column(length: 191, unique: true)]
    #[Assert\NotBlank]
    public string $slug;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    public string $description;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    public ?string $history = null;

    #[ORM\Column(length: 100)]
    public string $category;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $address = null;

    #[ORM\Column(length: 100, nullable: true)]
    public ?string $district = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 8)]
    public string $latitude;

    #[ORM\Column(type: Types::DECIMAL, precision: 11, scale: 8)]
    public string $longitude;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $openingHours = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    public ?string $ticketPrice = null;

    #[ORM\Column(options: ['default' => false])]
    public bool $accessibility = false;

    #[ORM\Column(options: ['default' => false])]
    public bool $hasBathroom = false;

    #[ORM\Column(options: ['default' => false])]
    public bool $hasParking = false;

    #[ORM\Column(length: 50, nullable: true)]
    public ?string $safetyLevel = null;

    #[ORM\Column(length: 100, nullable: true)]
    public ?string $source = null;

    #[ORM\Column(options: ['default' => true])]
    public bool $active = true;

    #[ORM\ManyToOne(inversedBy: 'touristSpots')]
    #[ORM\JoinColumn(nullable: true)]
    public ?Organization $organization = null;

    #[ORM\Column]
    public \DateTimeImmutable $createdAt;

    #[ORM\Column(nullable: true)]
    public ?\DateTimeImmutable $updatedAt = null;

    /**
     * Initializes creation timestamp.
     */
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    /**
     * Updates the last change timestamp before updating rows.
     */
    #[ORM\PreUpdate]
    public function touch(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }
}
