<?php

namespace App\Repository;

use App\Entity\BatchRoutine;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

// Generated by GitHub Copilot
/**
 * Provides query helpers for batch monitoring dashboards.
 *
 * @extends ServiceEntityRepository<BatchRoutine>
 */
final class BatchRoutineRepository extends ServiceEntityRepository
{
    /**
     * Configures the repository for BatchRoutine access.
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, BatchRoutine::class);
    }

    /**
     * Returns every active routine ordered for dashboard display.
     *
     * @return list<BatchRoutine>
     */
    public function findActiveRoutines(): array
    {
        return $this->createQueryBuilder('routine')
            ->andWhere('routine.active = :active')
            ->setParameter('active', true)
            ->orderBy('routine.nextExecutionAt', 'ASC')
            ->addOrderBy('routine.name', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Returns routines filtered by status.
     *
     * @return list<BatchRoutine>
     */
    public function findByStatus(string $status): array
    {
        return $this->createQueryBuilder('routine')
            ->andWhere('routine.status = :status')
            ->setParameter('status', $status)
            ->orderBy('routine.name', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Counts routines grouped by status for summary cards.
     *
     * @return array<string, int>
     */
    public function countByStatus(): array
    {
        $rows = $this->createQueryBuilder('routine')
            ->select('routine.status AS status, COUNT(routine.id) AS total')
            ->groupBy('routine.status')
            ->getQuery()
            ->getArrayResult();

        $counts = array_fill_keys(BatchRoutine::getAvailableStatuses(), 0);

        foreach ($rows as $row) {
            $counts[(string) $row['status']] = (int) $row['total'];
        }

        return $counts;
    }

    /**
     * Sums all processed records from every routine.
     */
    public function getTotalRecordsProcessed(): int
    {
        $result = $this->createQueryBuilder('routine')
            ->select('COALESCE(SUM(routine.recordsProcessed), 0) AS total')
            ->getQuery()
            ->getSingleScalarResult();

        return (int) $result;
    }

    /**
     * Calculates the average execution time for completed runs.
     */
    public function getAverageExecutionTime(): float
    {
        $result = $this->createQueryBuilder('routine')
            ->select('AVG(routine.executionTimeSeconds) AS averageTime')
            ->andWhere('routine.executionTimeSeconds IS NOT NULL')
            ->getQuery()
            ->getSingleScalarResult();

        return null === $result ? 0.0 : (float) $result;
    }
}