<?php

namespace App\Admin;

use App\Entity\Accommodation;
use App\Entity\BatchRoutine;
use App\Entity\DataSource;
use App\Entity\Indicator;
use App\Entity\Organization;
use App\Entity\TourismEvent;
use App\Entity\TouristGuide;
use App\Entity\TouristSpot;
use App\Form\AccommodationType;
use App\Form\BatchRoutineType;
use App\Form\DataSourceType;
use App\Form\IndicatorType;
use App\Form\OrganizationType;
use App\Form\TourismEventType;
use App\Form\TouristGuideType;
use App\Form\TouristSpotType;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;
use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\PropertyAccess\PropertyAccessorInterface;

// Generated by GitHub Copilot
final class DataManagementRegistry
{
    public const ROUTE_REQUIREMENT = 'organizations|tourist-spots|events|accommodations|guides|tourist-guides|indicators|data-sources|batch-routines';

    private readonly PropertyAccessorInterface $propertyAccessor;

    /**
     * Builds the resource registry used by the manual administration area.
     */
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
    ) {
        $this->propertyAccessor = PropertyAccess::createPropertyAccessor();
    }

    /**
     * Returns the dashboard cards for each managed entity.
     *
     * @return list<array<string, mixed>>
     */
    public function getDashboardCards(): array
    {
        $cards = [];

        foreach ($this->all() as $resource => $metadata) {
            $counts = $this->getQualityCounts($metadata);

            $cards[] = [
                'resource' => $resource,
                'label' => $metadata['label'],
                'singular' => $metadata['singular'],
                'description' => $metadata['description'],
                'icon' => $metadata['icon'],
                'total' => $this->entityManager->getRepository($metadata['class'])->count([]),
                'needsReview' => $counts['incomplete'],
                'inactive' => $counts['inactive'],
            ];
        }

        return $cards;
    }

    /**
     * Returns the quick actions displayed in the management dashboard.
     *
     * @return list<array<string, mixed>>
     */
    public function getQuickActions(): array
    {
        return [
            [
                'label' => 'Novo Ponto Turístico',
                'icon' => 'tabler:map-plus',
                'route' => 'app_admin_resource_new',
                'params' => ['resource' => 'tourist-spots'],
                'tone' => 'primary',
            ],
            [
                'label' => 'Novo Evento',
                'icon' => 'tabler:calendar-plus',
                'route' => 'app_admin_resource_new',
                'params' => ['resource' => 'events'],
                'tone' => 'success',
            ],
            [
                'label' => 'Nova Hospedagem',
                'icon' => 'tabler:building-estate',
                'route' => 'app_admin_resource_new',
                'params' => ['resource' => 'accommodations'],
                'tone' => 'warning',
            ],
            [
                'label' => 'Novo Guia',
                'icon' => 'tabler:user-star',
                'route' => 'app_admin_resource_new',
                'params' => ['resource' => 'tourist-guides'],
                'tone' => 'info',
            ],
            [
                'label' => 'Nova Fonte de Dados',
                'icon' => 'tabler:database-plus',
                'route' => 'app_admin_resource_new',
                'params' => ['resource' => 'data-sources'],
                'tone' => 'dark',
            ],
            [
                'label' => 'Ver Monitoramento Batch',
                'icon' => 'tabler:activity',
                'route' => 'app_batch_monitor',
                'params' => [],
                'tone' => 'outline-primary',
            ],
        ];
    }

    /**
     * Returns all managed resources metadata.
     *
     * @return array<string, array<string, mixed>>
     */
    public function all(): array
    {
        return [
            'organizations' => [
                'class' => Organization::class,
                'form_type' => OrganizationType::class,
                'label' => 'Organizações',
                'singular' => 'Organização',
                'icon' => 'tabler:building-community',
                'description' => 'Cadastro institucional de órgãos, operadores e entidades estratégicas do ecossistema turístico.',
                'title_field' => 'name',
                'slug_field' => 'slug',
                'search_fields' => ['name', 'description', 'type', 'city'],
                'description_field' => 'description',
                'source_field' => null,
                'active_field' => 'active',
                'geo_fields' => ['latitude', 'longitude'],
                'review_fields' => ['website'],
                'secondary_fields' => ['type', 'city', 'state'],
                'default_order' => ['name' => 'ASC'],
                'detail_fields' => [
                    'name' => 'Nome',
                    'slug' => 'Slug',
                    'type' => 'Tipo',
                    'documentNumber' => 'Documento',
                    'website' => 'Website',
                    'instagram' => 'Instagram',
                    'phone' => 'Telefone',
                    'email' => 'E-mail',
                    'address' => 'Endereço',
                    'district' => 'Bairro',
                    'city' => 'Cidade',
                    'state' => 'UF',
                    'latitude' => 'Latitude',
                    'longitude' => 'Longitude',
                    'description' => 'Descrição',
                    'createdAt' => 'Criado em',
                    'updatedAt' => 'Atualizado em',
                ],
            ],
            'tourist-spots' => [
                'class' => TouristSpot::class,
                'form_type' => TouristSpotType::class,
                'label' => 'Pontos Turísticos',
                'singular' => 'Ponto Turístico',
                'icon' => 'tabler:map-pin',
                'description' => 'Curadoria manual de atrativos, infraestrutura de visitação e informações de apoio ao visitante.',
                'title_field' => 'name',
                'slug_field' => 'slug',
                'search_fields' => ['name', 'description', 'category', 'district'],
                'description_field' => 'description',
                'source_field' => 'source',
                'active_field' => 'active',
                'geo_fields' => ['latitude', 'longitude'],
                'review_fields' => ['openingHours'],
                'secondary_fields' => ['category', 'district', 'organization.name'],
                'default_order' => ['name' => 'ASC'],
                'detail_fields' => [
                    'name' => 'Nome',
                    'slug' => 'Slug',
                    'category' => 'Categoria',
                    'address' => 'Endereço',
                    'district' => 'Bairro',
                    'latitude' => 'Latitude',
                    'longitude' => 'Longitude',
                    'openingHours' => 'Horário',
                    'ticketPrice' => 'Ingresso',
                    'accessibility' => 'Acessibilidade',
                    'hasBathroom' => 'Banheiro',
                    'hasParking' => 'Estacionamento',
                    'safetyLevel' => 'Segurança',
                    'source' => 'Fonte',
                    'organization.name' => 'Organização',
                    'description' => 'Descrição',
                    'history' => 'Histórico',
                    'createdAt' => 'Criado em',
                    'updatedAt' => 'Atualizado em',
                ],
            ],
            'events' => [
                'class' => TourismEvent::class,
                'form_type' => TourismEventType::class,
                'label' => 'Eventos',
                'singular' => 'Evento',
                'icon' => 'tabler:calendar-event',
                'description' => 'Programação turística, agendas sazonais e eventos estratégicos com curadoria institucional.',
                'title_field' => 'title',
                'slug_field' => 'slug',
                'search_fields' => ['title', 'description', 'category', 'location'],
                'description_field' => 'description',
                'source_field' => 'source',
                'active_field' => null,
                'geo_fields' => ['latitude', 'longitude'],
                'review_fields' => ['website'],
                'secondary_fields' => ['category', 'location', 'organization.name'],
                'default_order' => ['startDate' => 'ASC'],
                'detail_fields' => [
                    'title' => 'Título',
                    'slug' => 'Slug',
                    'category' => 'Categoria',
                    'startDate' => 'Início',
                    'endDate' => 'Fim',
                    'location' => 'Local',
                    'district' => 'Bairro',
                    'latitude' => 'Latitude',
                    'longitude' => 'Longitude',
                    'expectedAudience' => 'Público esperado',
                    'isFree' => 'Gratuito',
                    'ticketUrl' => 'Link de ingresso',
                    'website' => 'Website',
                    'instagram' => 'Instagram',
                    'source' => 'Fonte',
                    'organization.name' => 'Organização',
                    'description' => 'Descrição',
                    'createdAt' => 'Criado em',
                    'updatedAt' => 'Atualizado em',
                ],
            ],
            'accommodations' => [
                'class' => Accommodation::class,
                'form_type' => AccommodationType::class,
                'label' => 'Hospedagens',
                'singular' => 'Hospedagem',
                'icon' => 'tabler:building-estate',
                'description' => 'Gestão manual de meios de hospedagem, infraestrutura e dados de contato operacionais.',
                'title_field' => 'name',
                'slug_field' => 'slug',
                'search_fields' => ['name', 'description', 'category', 'address'],
                'description_field' => 'description',
                'source_field' => null,
                'active_field' => 'active',
                'geo_fields' => ['latitude', 'longitude'],
                'review_fields' => ['phone'],
                'secondary_fields' => ['category', 'district', 'organization.name'],
                'default_order' => ['name' => 'ASC'],
                'detail_fields' => [
                    'name' => 'Nome',
                    'slug' => 'Slug',
                    'category' => 'Categoria',
                    'cadasturCode' => 'Cadastur',
                    'address' => 'Endereço',
                    'district' => 'Bairro',
                    'latitude' => 'Latitude',
                    'longitude' => 'Longitude',
                    'rooms' => 'Quartos',
                    'beds' => 'Leitos',
                    'wifi' => 'Wi-Fi',
                    'parking' => 'Estacionamento',
                    'accessibility' => 'Acessibilidade',
                    'website' => 'Website',
                    'instagram' => 'Instagram',
                    'phone' => 'Telefone',
                    'email' => 'E-mail',
                    'organization.name' => 'Organização',
                    'description' => 'Descrição',
                    'createdAt' => 'Criado em',
                    'updatedAt' => 'Atualizado em',
                ],
            ],
            'tourist-guides' => [
                'class' => TouristGuide::class,
                'form_type' => TouristGuideType::class,
                'label' => 'Guias Turísticos',
                'singular' => 'Guia Turístico',
                'icon' => 'tabler:user-star',
                'description' => 'Cadastro humano de profissionais, especialidades e áreas de atendimento para o destino.',
                'title_field' => 'name',
                'slug_field' => null,
                'search_fields' => ['name', 'serviceRegion', 'email'],
                'description_field' => null,
                'source_field' => null,
                'active_field' => 'active',
                'geo_fields' => null,
                'review_fields' => ['serviceRegion'],
                'secondary_fields' => ['serviceRegion', 'organization.name'],
                'default_order' => ['name' => 'ASC'],
                'detail_fields' => [
                    'name' => 'Nome',
                    'cadasturCode' => 'Cadastur',
                    'languages' => 'Idiomas',
                    'specialties' => 'Especialidades',
                    'phone' => 'Telefone',
                    'email' => 'E-mail',
                    'instagram' => 'Instagram',
                    'serviceRegion' => 'Região de atuação',
                    'organization.name' => 'Organização',
                    'createdAt' => 'Criado em',
                    'updatedAt' => 'Atualizado em',
                ],
            ],
            'indicators' => [
                'class' => Indicator::class,
                'form_type' => IndicatorType::class,
                'label' => 'Indicadores',
                'singular' => 'Indicador',
                'icon' => 'tabler:chart-histogram',
                'description' => 'Séries estratégicas, métricas oficiais e indicadores de desempenho com revisão editorial.',
                'title_field' => 'title',
                'slug_field' => 'slug',
                'search_fields' => ['title', 'description', 'category', 'source'],
                'description_field' => 'description',
                'source_field' => 'source',
                'active_field' => null,
                'geo_fields' => null,
                'review_fields' => ['unit'],
                'secondary_fields' => ['category', 'unit', 'source'],
                'default_order' => ['referenceDate' => 'DESC'],
                'detail_fields' => [
                    'title' => 'Título',
                    'slug' => 'Slug',
                    'category' => 'Categoria',
                    'value' => 'Valor',
                    'unit' => 'Unidade',
                    'referenceDate' => 'Data de referência',
                    'source' => 'Fonte',
                    'description' => 'Descrição',
                    'createdAt' => 'Criado em',
                ],
            ],
            'data-sources' => [
                'class' => DataSource::class,
                'form_type' => DataSourceType::class,
                'label' => 'Fontes de Dados',
                'singular' => 'Fonte de Dados',
                'icon' => 'tabler:database',
                'description' => 'Inventário das bases integradas ou curadas manualmente pela governança de dados do Olinda360.',
                'title_field' => 'name',
                'slug_field' => 'slug',
                'search_fields' => ['name', 'description', 'type', 'url'],
                'description_field' => 'description',
                'source_field' => null,
                'active_field' => 'active',
                'geo_fields' => null,
                'review_fields' => ['updateFrequency'],
                'secondary_fields' => ['type', 'updateFrequency', 'url'],
                'default_order' => ['name' => 'ASC'],
                'detail_fields' => [
                    'name' => 'Nome',
                    'slug' => 'Slug',
                    'type' => 'Tipo',
                    'url' => 'URL',
                    'description' => 'Descrição',
                    'updateFrequency' => 'Frequência de atualização',
                    'createdAt' => 'Criado em',
                ],
            ],
            'batch-routines' => [
                'class' => BatchRoutine::class,
                'form_type' => BatchRoutineType::class,
                'label' => 'Rotinas Batch',
                'singular' => 'Rotina Batch',
                'icon' => 'tabler:activity-heartbeat',
                'description' => 'Supervisão manual das rotinas automatizadas, seus cronogramas e sinais de qualidade operacional.',
                'title_field' => 'name',
                'slug_field' => 'slug',
                'search_fields' => ['name', 'sourceName', 'sourceType', 'description'],
                'description_field' => 'description',
                'source_field' => 'sourceName',
                'active_field' => 'active',
                'geo_fields' => null,
                'status_field' => 'status',
                'review_fields' => ['cronExpression'],
                'secondary_fields' => ['sourceType', 'sourceName', 'scheduledTime'],
                'default_order' => ['active' => 'DESC', 'name' => 'ASC'],
                'detail_fields' => [
                    'name' => 'Nome',
                    'slug' => 'Slug',
                    'sourceName' => 'Fonte',
                    'sourceType' => 'Tipo de fonte',
                    'description' => 'Descrição',
                    'apiUrl' => 'Endpoint',
                    'cronExpression' => 'Cron',
                    'scheduledTime' => 'Agendamento',
                    'status' => 'Status',
                    'lastExecutionAt' => 'Última execução',
                    'nextExecutionAt' => 'Próxima execução',
                    'recordsProcessed' => 'Processados',
                    'recordsCreated' => 'Criados',
                    'recordsUpdated' => 'Atualizados',
                    'recordsFailed' => 'Falhas',
                    'executionTimeSeconds' => 'Tempo (s)',
                    'lastMessage' => 'Última mensagem',
                    'createdAt' => 'Criado em',
                    'updatedAt' => 'Atualizado em',
                ],
            ],
        ];
    }

    /**
     * Returns a single resource metadata definition.
     *
     * @return array<string, mixed>
     */
    public function get(string $resource): array
    {
        if ('guides' === $resource) {
            $resource = 'tourist-guides';
        }

        $metadata = $this->all();

        if (!isset($metadata[$resource])) {
            throw new \InvalidArgumentException(sprintf('Unknown data management resource "%s".', $resource));
        }

        return $metadata[$resource];
    }

    /**
     * Builds the query builder used by the manual CRUD index pages.
     */
    public function createIndexQueryBuilder(array $metadata, string $search = '', ?string $status = null, ?string $quality = null): QueryBuilder
    {
        $repository = $this->entityManager->getRepository($metadata['class']);
        $queryBuilder = $repository->createQueryBuilder('entity');

        if ('' !== $search) {
            $or = $queryBuilder->expr()->orX();

            foreach ($metadata['search_fields'] as $index => $field) {
                $parameter = sprintf('search_%d', $index);
                $or->add(sprintf('LOWER(entity.%s) LIKE :%s', $field, $parameter));
                $queryBuilder->setParameter($parameter, '%'.mb_strtolower($search).'%');
            }

            $queryBuilder->andWhere($or);
        }

        if ($this->supportsActiveFilter($metadata) && in_array($status, ['active', 'inactive'], true)) {
            $queryBuilder
                ->andWhere(sprintf('entity.%s = :activeStatus', $metadata['active_field']))
                ->setParameter('activeStatus', 'active' === $status)
            ;
        }

        $this->applyQualityFilter($queryBuilder, $metadata, $quality);

        foreach ($metadata['default_order'] as $field => $direction) {
            $queryBuilder->addOrderBy(sprintf('entity.%s', $field), $direction);
        }

        return $queryBuilder;
    }

    /**
     * Returns whether the resource supports an active/inactive filter.
     *
     * @param array<string, mixed> $metadata
     */
    public function supportsActiveFilter(array $metadata): bool
    {
        return isset($metadata['active_field']) && null !== $metadata['active_field'];
    }

    /**
     * Returns the quality filters supported by the resource.
     *
     * @param array<string, mixed> $metadata
     *
     * @return array<string, string>
     */
    public function getSupportedQualityFilters(array $metadata): array
    {
        $filters = [
            'incomplete' => 'Registros incompletos',
        ];

        if (isset($metadata['geo_fields']) && null !== $metadata['geo_fields']) {
            $filters['no_geo'] = 'Sem coordenadas';
        }

        if (isset($metadata['description_field']) && null !== $metadata['description_field']) {
            $filters['no_description'] = 'Sem descrição';
        }

        if (isset($metadata['source_field']) && null !== $metadata['source_field']) {
            $filters['no_source'] = 'Sem fonte';
        }

        if ($this->supportsActiveFilter($metadata)) {
            $filters['inactive'] = 'Inativos';
        }

        return $filters;
    }

    /**
     * Returns quality counters used in cards and hygiene indicators.
     *
     * @param array<string, mixed> $metadata
     *
     * @return array<string, int>
     */
    public function getQualityCounts(array $metadata): array
    {
        $counts = [
            'incomplete' => $this->countByFilter($metadata, null, 'incomplete'),
            'inactive' => $this->supportsActiveFilter($metadata) ? $this->countByFilter($metadata, 'inactive', null) : 0,
        ];

        if (isset($metadata['geo_fields']) && null !== $metadata['geo_fields']) {
            $counts['no_geo'] = $this->countByFilter($metadata, null, 'no_geo');
        }

        if (isset($metadata['description_field']) && null !== $metadata['description_field']) {
            $counts['no_description'] = $this->countByFilter($metadata, null, 'no_description');
        }

        if (isset($metadata['source_field']) && null !== $metadata['source_field']) {
            $counts['no_source'] = $this->countByFilter($metadata, null, 'no_source');
        }

        return $counts;
    }

    /**
     * Returns the display title for a resource instance.
     *
     * @param array<string, mixed> $metadata
     */
    public function getDisplayTitle(object $entity, array $metadata): string
    {
        $title = $this->readProperty($entity, $metadata['title_field']);

        if (is_string($title) && '' !== trim($title)) {
            return $title;
        }

        $id = $this->readProperty($entity, 'id');

        return sprintf('%s #%s', $metadata['singular'], (string) ($id ?? 'novo'));
    }

    /**
     * Returns a concise summary line for list cards and tables.
     *
     * @param array<string, mixed> $metadata
     */
    public function getSummary(object $entity, array $metadata): string
    {
        $values = [];

        foreach ($metadata['secondary_fields'] as $field) {
            $value = $this->formatValue($this->readProperty($entity, $field));

            if ('Não informado' !== $value) {
                $values[] = $value;
            }
        }

        if ([] !== $values) {
            return implode(' • ', array_slice($values, 0, 3));
        }

        if (isset($metadata['description_field']) && null !== $metadata['description_field']) {
            $description = $this->readProperty($entity, $metadata['description_field']);

            if (is_string($description) && '' !== trim($description)) {
                return $this->truncate($description, 120);
            }
        }

        return 'Sem resumo operacional disponível.';
    }

    /**
     * Returns the data quality badges for a resource instance.
     *
     * @param array<string, mixed> $metadata
     *
     * @return list<array{label: string, tone: string}>
     */
    public function getQualityBadges(object $entity, array $metadata): array
    {
        $badges = [];

        if ($this->hasMissingGeo($entity, $metadata)) {
            $badges[] = ['label' => 'Sem geolocalização', 'tone' => 'warning'];
        }

        if ($this->hasMissingSource($entity, $metadata)) {
            $badges[] = ['label' => 'Sem fonte', 'tone' => 'secondary'];
        }

        if ($this->needsReview($entity, $metadata)) {
            $badges[] = ['label' => 'Precisa revisão', 'tone' => 'danger'];
        }

        if ([] === $badges) {
            return [['label' => 'Completo', 'tone' => 'success']];
        }

        array_unshift($badges, ['label' => 'Incompleto', 'tone' => 'warning']);

        return $badges;
    }

    /**
     * Returns the status badge for active state or batch processing state.
     *
     * @param array<string, mixed> $metadata
     *
     * @return array{label: string, tone: string}|null
     */
    public function getStatusBadge(object $entity, array $metadata): ?array
    {
        if (isset($metadata['status_field']) && null !== $metadata['status_field']) {
            $status = (string) $this->readProperty($entity, $metadata['status_field']);

            return match ($status) {
                BatchRoutine::STATUS_SUCCESS => ['label' => 'Finalizado', 'tone' => 'success'],
                BatchRoutine::STATUS_RUNNING => ['label' => 'Executando', 'tone' => 'primary'],
                BatchRoutine::STATUS_WARNING => ['label' => 'Alerta', 'tone' => 'warning'],
                BatchRoutine::STATUS_FAILED => ['label' => 'Falha', 'tone' => 'danger'],
                BatchRoutine::STATUS_DISABLED => ['label' => 'Desativado', 'tone' => 'secondary'],
                default => ['label' => 'Pendente', 'tone' => 'secondary'],
            };
        }

        if (!$this->supportsActiveFilter($metadata)) {
            return null;
        }

        return true === $this->readProperty($entity, $metadata['active_field'])
            ? ['label' => 'Ativo', 'tone' => 'success']
            : ['label' => 'Inativo', 'tone' => 'secondary'];
    }

    /**
     * Returns the rows displayed in the detail view.
     *
     * @param array<string, mixed> $metadata
     *
     * @return list<array{label: string, value: string}>
     */
    public function getDetailRows(object $entity, array $metadata): array
    {
        $rows = [];

        foreach ($metadata['detail_fields'] as $field => $label) {
            $rows[] = [
                'label' => $label,
                'value' => $this->formatValue($this->readProperty($entity, $field)),
            ];
        }

        return $rows;
    }

    /**
     * Automatically generates a slug when the entity supports it and none was provided.
     *
     * @param array<string, mixed> $metadata
     */
    public function fillSlugIfMissing(object $entity, array $metadata): void
    {
        if (!isset($metadata['slug_field']) || null === $metadata['slug_field']) {
            return;
        }

        $currentSlug = $this->readProperty($entity, $metadata['slug_field']);

        if (is_string($currentSlug) && '' !== trim($currentSlug)) {
            return;
        }

        $title = (string) $this->readProperty($entity, $metadata['title_field']);
        $normalized = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $title);
        $normalized = false === $normalized ? $title : $normalized;
        $normalized = preg_replace('/[^a-z0-9]+/i', '-', strtolower(trim($normalized))) ?? '';

        $this->writeProperty($entity, $metadata['slug_field'], trim($normalized, '-'));
    }

    /**
     * Counts records for a given hygiene or status filter.
     *
     * @param array<string, mixed> $metadata
     */
    private function countByFilter(array $metadata, ?string $status, ?string $quality): int
    {
        $queryBuilder = $this->createIndexQueryBuilder($metadata, '', $status, $quality);

        return (int) $queryBuilder
            ->select('COUNT(entity.id)')
            ->resetDQLPart('orderBy')
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }

    /**
     * Applies the selected hygiene filter to a query builder.
     *
     * @param array<string, mixed> $metadata
     */
    private function applyQualityFilter(QueryBuilder $queryBuilder, array $metadata, ?string $quality): void
    {
        if (null === $quality || '' === $quality) {
            return;
        }

        if ('inactive' === $quality && $this->supportsActiveFilter($metadata)) {
            $queryBuilder
                ->andWhere(sprintf('entity.%s = :qualityInactive', $metadata['active_field']))
                ->setParameter('qualityInactive', false)
            ;

            return;
        }

        if ('no_geo' === $quality && isset($metadata['geo_fields']) && null !== $metadata['geo_fields']) {
            [$latitudeField, $longitudeField] = $metadata['geo_fields'];
            $queryBuilder->andWhere(sprintf('entity.%s IS NULL OR entity.%s IS NULL', $latitudeField, $longitudeField));

            return;
        }

        if ('no_description' === $quality && isset($metadata['description_field']) && null !== $metadata['description_field']) {
            $descriptionField = $metadata['description_field'];
            $queryBuilder->andWhere(sprintf('entity.%s IS NULL OR entity.%s = :emptyDescription', $descriptionField, $descriptionField));
            $queryBuilder->setParameter('emptyDescription', '');

            return;
        }

        if ('no_source' === $quality && isset($metadata['source_field']) && null !== $metadata['source_field']) {
            $sourceField = $metadata['source_field'];
            $queryBuilder->andWhere(sprintf('entity.%s IS NULL OR entity.%s = :emptySource', $sourceField, $sourceField));
            $queryBuilder->setParameter('emptySource', '');

            return;
        }

        if ('incomplete' !== $quality) {
            return;
        }

        $conditions = [];

        if (isset($metadata['geo_fields']) && null !== $metadata['geo_fields']) {
            [$latitudeField, $longitudeField] = $metadata['geo_fields'];
            $conditions[] = sprintf('entity.%s IS NULL OR entity.%s IS NULL', $latitudeField, $longitudeField);
        }

        if (isset($metadata['description_field']) && null !== $metadata['description_field']) {
            $conditions[] = sprintf('entity.%s IS NULL OR entity.%s = :emptyIncompleteDescription', $metadata['description_field'], $metadata['description_field']);
            $queryBuilder->setParameter('emptyIncompleteDescription', '');
        }

        if (isset($metadata['source_field']) && null !== $metadata['source_field']) {
            $conditions[] = sprintf('entity.%s IS NULL OR entity.%s = :emptyIncompleteSource', $metadata['source_field'], $metadata['source_field']);
            $queryBuilder->setParameter('emptyIncompleteSource', '');
        }

        if (isset($metadata['review_fields']) && is_array($metadata['review_fields'])) {
            foreach ($metadata['review_fields'] as $index => $field) {
                $parameter = sprintf('emptyReviewField_%d', $index);
                $conditions[] = sprintf('entity.%s IS NULL OR entity.%s = :%s', $field, $field, $parameter);
                $queryBuilder->setParameter($parameter, '');
            }
        }

        if ([] === $conditions) {
            return;
        }

        $queryBuilder->andWhere('('.implode(') OR (', $conditions).')');
    }

    /**
     * Determines whether the record is missing geolocation data.
     *
     * @param array<string, mixed> $metadata
     */
    private function hasMissingGeo(object $entity, array $metadata): bool
    {
        if (!isset($metadata['geo_fields']) || null === $metadata['geo_fields']) {
            return false;
        }

        [$latitudeField, $longitudeField] = $metadata['geo_fields'];

        return $this->isEmpty($this->readProperty($entity, $latitudeField)) || $this->isEmpty($this->readProperty($entity, $longitudeField));
    }

    /**
     * Determines whether the record is missing source data.
     *
     * @param array<string, mixed> $metadata
     */
    private function hasMissingSource(object $entity, array $metadata): bool
    {
        if (!isset($metadata['source_field']) || null === $metadata['source_field']) {
            return false;
        }

        return $this->isEmpty($this->readProperty($entity, $metadata['source_field']));
    }

    /**
     * Determines whether the record needs editorial review.
     *
     * @param array<string, mixed> $metadata
     */
    private function needsReview(object $entity, array $metadata): bool
    {
        if (isset($metadata['description_field']) && null !== $metadata['description_field']) {
            if ($this->isEmpty($this->readProperty($entity, $metadata['description_field']))) {
                return true;
            }
        }

        if (isset($metadata['review_fields']) && is_array($metadata['review_fields'])) {
            foreach ($metadata['review_fields'] as $field) {
                if ($this->isEmpty($this->readProperty($entity, $field))) {
                    return true;
                }
            }
        }

        if ($this->supportsActiveFilter($metadata)) {
            return true !== $this->readProperty($entity, $metadata['active_field']);
        }

        return false;
    }

    /**
     * Safely reads a public property, getter or nested property path.
     */
    private function readProperty(object $entity, string $propertyPath): mixed
    {
        return $this->propertyAccessor->getValue($entity, $propertyPath);
    }

    /**
     * Safely writes a public property or setter-backed property.
     */
    private function writeProperty(object $entity, string $propertyPath, mixed $value): void
    {
        $this->propertyAccessor->setValue($entity, $propertyPath, $value);
    }

    /**
     * Formats values for detail views and summaries.
     */
    private function formatValue(mixed $value): string
    {
        if (null === $value) {
            return 'Não informado';
        }

        if (is_bool($value)) {
            return $value ? 'Sim' : 'Não';
        }

        if ($value instanceof \DateTimeInterface) {
            return $value->format('d/m/Y H:i');
        }

        if (is_array($value)) {
            return [] === $value ? 'Não informado' : implode(', ', $value);
        }

        if (is_object($value)) {
            foreach (['name', 'title'] as $property) {
                if ($this->propertyAccessor->isReadable($value, $property)) {
                    $resolved = $this->propertyAccessor->getValue($value, $property);

                    if (is_string($resolved) && '' !== trim($resolved)) {
                        return $resolved;
                    }
                }
            }

            return 'Registro relacionado';
        }

        $stringValue = trim((string) $value);

        return '' === $stringValue ? 'Não informado' : $stringValue;
    }

    /**
     * Determines whether a scalar value should be considered empty for hygiene rules.
     */
    private function isEmpty(mixed $value): bool
    {
        if (null === $value) {
            return true;
        }

        if (is_string($value)) {
            return '' === trim($value);
        }

        if (is_array($value)) {
            return [] === $value;
        }

        return false;
    }

    /**
     * Truncates long strings while preserving a readable summary.
     */
    private function truncate(string $value, int $limit): string
    {
        $normalized = trim(preg_replace('/\s+/', ' ', strip_tags($value)) ?? '');

        if (mb_strlen($normalized) <= $limit) {
            return $normalized;
        }

        return rtrim(mb_substr($normalized, 0, $limit - 1)).'…';
    }
}