<?php

namespace App\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

// Generated by GitHub Copilot
final class AnalyticsControllerTest extends WebTestCase
{
    /**
     * Verifies that the analytics route renders the executive analytics center.
     */
    public function testAnalyticsDashboardLoads(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/analytics');

        $this->assertResponseIsSuccessful();
        $this->assertStringContainsString('Analytics Territorial e Turistico', $crawler->filter('body')->text());
        $this->assertStringContainsString('Painel Analitico Comparativo', $crawler->filter('body')->text());
        $this->assertSelectorExists('#analyticsTourismFlowChart');
        $this->assertSelectorExists('#analyticsHotelOccupancyChart');
        $this->assertSelectorExists('#analyticsMaturityRadarChart');
    }
}