<?php

namespace App\Tests\Controller;

use App\Repository\BatchRoutineRepository;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

// Generated by GitHub Copilot
final class BatchMonitorControllerTest extends WebTestCase
{
    /**
     * Verifies that the batch monitoring dashboard loads successfully.
     */
    public function testIndexLoads(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/batch-monitor');

        $this->assertResponseIsSuccessful();
        $this->assertStringContainsString('Monitoramento Batch', $crawler->filter('body')->text());
    }

    /**
     * Verifies that the routine detail page loads for a persisted routine.
     */
    public function testShowLoads(): void
    {
        $client = static::createClient();

        /** @var BatchRoutineRepository $repository */
        $repository = $client->getContainer()->get(BatchRoutineRepository::class);
        $routine = $repository->findOneBy([]);

        $this->assertNotNull($routine);

        $client->request('GET', sprintf('/batch-monitor/%d', $routine->getId()));
        $this->assertResponseIsSuccessful();
    }

    /**
     * Verifies that the CSV export endpoint responds with download headers.
     */
    public function testExportCsvReturnsDownload(): void
    {
        $client = static::createClient();
        $client->request('GET', '/batch-monitor/export.csv');

        $this->assertResponseIsSuccessful();
        $this->assertResponseHeaderSame('Content-Type', 'text/csv; charset=UTF-8');
    }
}