<?php

namespace App\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

// Generated by GitHub Copilot
final class IndicatorsControllerTest extends WebTestCase
{
    /**
     * Verifies that the indicators route renders the executive analytics dashboard.
     */
    public function testIndicatorsDashboardLoads(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/indicators');

        $this->assertResponseIsSuccessful();
        $this->assertStringContainsString('Indicadores Estratégicos', $crawler->filter('body')->text());
        $this->assertSelectorExists('#monthlyVisitorsChart');
        $this->assertSelectorExists('#districtComparisonChart');
    }
}