<?php

namespace App\Tests\Controller;

use App\Entity\Accommodation;
use App\Entity\DataSource;
use App\Entity\Indicator;
use App\Entity\Organization;
use App\Entity\TourismEvent;
use App\Entity\TouristGuide;
use App\Entity\TouristSpot;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\SchemaTool;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

// Generated by GitHub Copilot
final class McpControllerTest extends WebTestCase
{
    /**
     * Verifies the MCP home and docs endpoints.
     */
    public function testHomeAndDocsEndpointsWork(): void
    {
        $client = static::createClient();

        $client->request('GET', '/mcp/v1');
        $this->assertResponseIsSuccessful();

        $payload = json_decode($client->getResponse()->getContent(), true, 512, JSON_THROW_ON_ERROR);
        $this->assertSame('success', $payload['status']);
        $this->assertSame('home', $payload['type']);
        $this->assertSame('Olinda360 MCP Gateway', $payload['data']['name']);

        $crawler = $client->request('GET', '/mcp/v1/docs');
        $this->assertResponseIsSuccessful();
        $this->assertStringContainsString('MCP / IA', $crawler->filter('body')->text());
    }

    /**
     * Verifies MCP resources, tools and contexts with a minimal schema.
     */
    public function testResourcesToolsAndContextsWork(): void
    {
        $client = static::createClient();

        /** @var EntityManagerInterface $entityManager */
        $entityManager = $client->getContainer()->get(EntityManagerInterface::class);
        $this->ensureSchema($entityManager);

        $organization = new Organization();
        $organization->name = 'Turismo Olinda';
        $organization->slug = 'turismo-olinda';
        $organization->type = 'Publica';

        $spot = new TouristSpot();
        $spot->name = 'Alto da Se';
        $spot->slug = 'alto-da-se';
        $spot->description = 'Mirante turistico e patrimonial';
        $spot->category = 'Cultural';
        $spot->latitude = '-8.00800000';
        $spot->longitude = '-34.85500000';
        $spot->source = 'Base manual';
        $spot->organization = $organization;

        $event = new TourismEvent();
        $event->title = 'Seresta na Praca';
        $event->slug = 'seresta-na-praca';
        $event->description = 'Programacao musical no sitio historico';
        $event->category = 'Cultural';
        $event->location = 'Praca do Carmo';
        $event->startDate = new \DateTime('+1 day');
        $event->source = 'Agenda cultural';
        $event->organization = $organization;

        $accommodation = new Accommodation();
        $accommodation->name = 'Pousada Colonial';
        $accommodation->slug = 'pousada-colonial';
        $accommodation->category = 'Pousada';
        $accommodation->address = 'Rua do Amparo';
        $accommodation->description = 'Hospedagem no centro historico';
        $accommodation->active = true;
        $accommodation->organization = $organization;

        $guide = new TouristGuide();
        $guide->name = 'Guia Maria';
        $guide->serviceRegion = 'Sitio Historico';
        $guide->languages = ['Português', 'English'];
        $guide->active = true;
        $guide->organization = $organization;

        $indicator = new Indicator();
        $indicator->title = 'Fluxo turistico mensal';
        $indicator->slug = 'fluxo-turistico-mensal';
        $indicator->category = 'Demanda';
        $indicator->value = 12500;
        $indicator->referenceDate = new \DateTime('2026-05-01');
        $indicator->source = 'Observatorio';

        $dataSource = new DataSource();
        $dataSource->name = 'Observatorio Municipal';
        $dataSource->slug = 'observatorio-municipal';
        $dataSource->type = 'Institucional';

        $entityManager->persist($organization);
        $entityManager->persist($spot);
        $entityManager->persist($event);
        $entityManager->persist($accommodation);
        $entityManager->persist($guide);
        $entityManager->persist($indicator);
        $entityManager->persist($dataSource);
        $entityManager->flush();

        $client->request('GET', '/mcp/v1/resources/tourist-spots', ['search' => 'Alto']);
        $this->assertResponseIsSuccessful();
        $resourcePayload = json_decode($client->getResponse()->getContent(), true, 512, JSON_THROW_ON_ERROR);
        $this->assertSame('resource', $resourcePayload['type']);
        $this->assertSame('tourist-spots', $resourcePayload['resource']);
        $this->assertSame('Alto da Se', $resourcePayload['data'][0]['name']);

        $client->request(
            'POST',
            '/mcp/v1/tools/search-tourism',
            [],
            [],
            ['CONTENT_TYPE' => 'application/json'],
            json_encode(['query' => 'Alto', 'limit' => 5], JSON_THROW_ON_ERROR),
        );
        $this->assertResponseIsSuccessful();
        $toolPayload = json_decode($client->getResponse()->getContent(), true, 512, JSON_THROW_ON_ERROR);
        $this->assertSame('tool', $toolPayload['type']);
        $this->assertSame('search-tourism', $toolPayload['tool']);
        $this->assertNotEmpty($toolPayload['data']);

        $client->request('GET', '/mcp/v1/context/city');
        $this->assertResponseIsSuccessful();
        $contextPayload = json_decode($client->getResponse()->getContent(), true, 512, JSON_THROW_ON_ERROR);
        $this->assertSame('context', $contextPayload['type']);
        $this->assertSame('city', $contextPayload['context']);
        $this->assertSame('Olinda', $contextPayload['data']['city']);
    }

    /**
     * Creates the minimum schema required by the MCP tests.
     */
    private function ensureSchema(EntityManagerInterface $entityManager): void
    {
        $metadata = [
            $entityManager->getClassMetadata(Organization::class),
            $entityManager->getClassMetadata(TouristSpot::class),
            $entityManager->getClassMetadata(TourismEvent::class),
            $entityManager->getClassMetadata(Accommodation::class),
            $entityManager->getClassMetadata(TouristGuide::class),
            $entityManager->getClassMetadata(Indicator::class),
            $entityManager->getClassMetadata(DataSource::class),
        ];

        $schemaTool = new SchemaTool($entityManager);
        $schemaTool->dropSchema($metadata);
        $schemaTool->createSchema($metadata);
        $entityManager->clear();
    }
}