<?php

namespace App\Tests\Controller;

use App\Entity\Organization;
use App\Entity\TouristGuide;
use Doctrine\ORM\Tools\SchemaTool;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

// Generated by GitHub Copilot
final class PublicApiControllerTest extends WebTestCase
{
    /**
     * Verifies the public API status endpoint.
     */
    public function testStatusEndpointWorks(): void
    {
        $client = static::createClient();
        $client->request('GET', '/public-api/v1/status');

        $this->assertResponseIsSuccessful();
        $this->assertResponseHeaderSame('Content-Type', 'application/json');

        $payload = json_decode($client->getResponse()->getContent(), true, 512, JSON_THROW_ON_ERROR);
        $this->assertSame('online', $payload['status']);
        $this->assertSame('Olinda360 Public API', $payload['name']);
    }

    /**
     * Verifies the dedicated public OpenAPI document endpoint.
     */
    public function testOpenApiDocumentEndpointWorks(): void
    {
        $client = static::createClient();
        $client->request('GET', '/public-api/v1/openapi.json');

        $this->assertResponseIsSuccessful();

        $payload = json_decode($client->getResponse()->getContent(), true, 512, JSON_THROW_ON_ERROR);
        $this->assertSame('3.0.3', $payload['openapi']);
        $this->assertSame('Olinda360 Public API', $payload['info']['title']);
        $this->assertArrayHasKey('/tourist-spots', $payload['paths']);
        $this->assertArrayHasKey('/guides', $payload['paths']);
    }

    /**
     * Verifies the public API documentation page.
     */
    public function testDocsPageLoads(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/public-api/v1/docs');

        $this->assertResponseIsSuccessful();
        $this->assertStringContainsString('API Pública de Dados Abertos', $crawler->filter('body')->text());
        $this->assertStringContainsString('/public-api/v1/openapi.json', $crawler->filter('body')->text());
    }

    /**
     * Verifies filtering, pagination and sensitive-field removal on guides.
     */
    public function testGuidesEndpointOnlyExposesActivePublicData(): void
    {
        $client = static::createClient();

        /** @var EntityManagerInterface $entityManager */
        $entityManager = $client->getContainer()->get(EntityManagerInterface::class);
        $this->ensureGuideSchema($entityManager);

        $visibleGuide = new TouristGuide();
        $visibleGuide->name = 'Guia Publico Teste';
        $visibleGuide->serviceRegion = 'Olinda Historica';
        $visibleGuide->instagram = '@guia.publico';
        $visibleGuide->languages = ['Português'];
        $visibleGuide->specialties = ['Patrimônio'];
        $visibleGuide->phone = '(81) 99999-9999';
        $visibleGuide->email = 'privado@example.com';
        $visibleGuide->active = true;

        $hiddenGuide = new TouristGuide();
        $hiddenGuide->name = 'Guia Inativo Teste';
        $hiddenGuide->serviceRegion = 'Olinda Historica';
        $hiddenGuide->active = false;

        $entityManager->persist($visibleGuide);
        $entityManager->persist($hiddenGuide);
        $entityManager->flush();

        $client->request('GET', '/public-api/v1/guides', ['search' => 'Guia', 'page' => 1, 'limit' => 10]);

        $this->assertResponseIsSuccessful();
        $payload = json_decode($client->getResponse()->getContent(), true, 512, JSON_THROW_ON_ERROR);

        $this->assertSame(1, $payload['meta']['page']);
        $this->assertSame(10, $payload['meta']['limit']);
        $this->assertGreaterThanOrEqual(1, $payload['meta']['total']);
        $this->assertNotEmpty($payload['data']);
        $this->assertSame('Guia Publico Teste', $payload['data'][0]['name']);
        $this->assertArrayNotHasKey('phone', $payload['data'][0]);
        $this->assertArrayNotHasKey('email', $payload['data'][0]);

        $client->request('GET', sprintf('/public-api/v1/guides/%d', $visibleGuide->id));
        $this->assertResponseIsSuccessful();
    }

    /**
     * Verifies that mutation methods are not exposed on the public API.
     */
    public function testPublicApiDoesNotExposeMutationMethods(): void
    {
        $client = static::createClient();

        $client->request('POST', '/public-api/v1/guides');
        $this->assertSame(405, $client->getResponse()->getStatusCode());

        $client->request('PATCH', '/public-api/v1/guides/999999');
        $this->assertSame(405, $client->getResponse()->getStatusCode());

        $client->request('DELETE', '/public-api/v1/guides/999999');
        $this->assertSame(405, $client->getResponse()->getStatusCode());
    }

    /**
     * Creates the minimum schema required by the guide endpoint tests.
     */
    private function ensureGuideSchema(EntityManagerInterface $entityManager): void
    {
        $metadata = [
            $entityManager->getClassMetadata(Organization::class),
            $entityManager->getClassMetadata(TouristGuide::class),
        ];

        $schemaTool = new SchemaTool($entityManager);
        $schemaTool->dropSchema($metadata);
        $schemaTool->createSchema($metadata);
        $entityManager->clear();
    }
}