<?php

namespace App\Tests\Controller\Admin;

use App\Entity\Accommodation;
use App\Entity\BatchRoutine;
use App\Entity\DataSource;
use App\Entity\Indicator;
use App\Entity\Organization;
use App\Entity\TourismEvent;
use App\Entity\TouristGuide;
use App\Entity\TouristSpot;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\SchemaTool;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

// Generated by GitHub Copilot
final class DataManagementControllerTest extends WebTestCase
{
    /**
     * Verifies that the management dashboard and a manual CRUD listing load successfully.
     */
    public function testManagementDashboardAndOrganizationListLoad(): void
    {
        $client = static::createClient();

        /** @var EntityManagerInterface $entityManager */
        $entityManager = $client->getContainer()->get(EntityManagerInterface::class);
        $this->ensureSchema($entityManager);

        $organization = new Organization();
        $organization->name = 'Secretaria de Turismo de Olinda';
        $organization->slug = 'secretaria-turismo-olinda';
        $organization->type = 'Pública';
        $entityManager->persist($organization);
        $entityManager->flush();

        $crawler = $client->request('GET', '/admin/data-management');

        $this->assertResponseIsSuccessful();
        $this->assertStringContainsString('Gestão de Dados', $crawler->filter('body')->text());
        $this->assertSelectorExists('a[href="/admin/organizations"]');

        $crawler = $client->request('GET', '/admin/organizations', ['q' => 'Secretaria']);

        $this->assertResponseIsSuccessful();
        $this->assertStringContainsString('Secretaria de Turismo de Olinda', $crawler->filter('body')->text());

        $client->request('GET', '/admin/organizations/new');
        $this->assertResponseIsSuccessful();
    }

    /**
     * Creates the minimum schema required by the data management screens.
     */
    private function ensureSchema(EntityManagerInterface $entityManager): void
    {
        $metadata = [
            $entityManager->getClassMetadata(Organization::class),
            $entityManager->getClassMetadata(TouristSpot::class),
            $entityManager->getClassMetadata(TourismEvent::class),
            $entityManager->getClassMetadata(Accommodation::class),
            $entityManager->getClassMetadata(TouristGuide::class),
            $entityManager->getClassMetadata(Indicator::class),
            $entityManager->getClassMetadata(DataSource::class),
            $entityManager->getClassMetadata(BatchRoutine::class),
        ];

        $schemaTool = new SchemaTool($entityManager);
        $schemaTool->dropSchema($metadata);
        $schemaTool->createSchema($metadata);
        $entityManager->clear();
    }
}